### ISSUE TITLE
Why are devDependencies included in dependencies?

### ISSUE THREAD

**Issue by kklash** [solana-labs/solana-web3.js#1000]
Seems like there are a few dependencies listed in `package.json` that should be in `devDependencies`:
- `esdoc-inject-style-plugin` - documentation build plugin?
- `mz` - only used in a test file
- `npm-run-all` - only used for development workflows

Were these mistakes? is there a reason why consumers of `@solana/web3.js` would need those packages to be installed in their `node_modules`?

**Comment by mvines** [comment]
Na, not intentional.  Looks like we just need some dependency cleanup here
