### ISSUE TITLE
TypeError: connection.sendTransaction is not a function

### ISSUE THREAD

**Issue by decefi** [solana-labs/solana-web3.js#1003]
Hello, trying to run js client, but getting this error, here is my code, it's same as in hello world example:
```
  console.log(connection.sendTransaction)
  await sendAndConfirmTransaction(
    'createAccount',
    connection,
    new Transaction().add(instruction),
    [payerAccount],
  );
```
Output:
```
[Function: sendTransaction]
TypeError: connection.sendTransaction is not a function
    at _callee$ (decefi-solana/node_modules/@solana/web3.js/src/util/send-and-confirm-transaction.js:31:38)
    at tryCatch (decefi-solana/node_modules/regenerator-runtime/runtime.js:63:40)
```

`"@solana/web3.js": "^0.87.1"`

**Comment by jstarry** [comment]
Hey @decefi, it looks like you are misusing the `sendAndConfirmTransaction` function. The first argument should be the `connection`, see [here](https://solana-labs.github.io/solana-web3.js/function/index.html#static-function-sendAndConfirmTransaction). Confusingly, the hello world example uses a custom `sendAndConfirmTransaction` function which takes a string.
