### ISSUE TITLE
How do I send an arbitary message to a Solana address?

### ISSUE THREAD

**Issue by jumpersdevice** [solana-labs/solana-web3.js#1005]
Good day, how can I send a message to another Solana address? And how would that user receiving know that it's a message? And what is the max size I can send? Thank you!

**Comment by mvines** [comment]
Hey, it's probably best to discuss this on our Discord, please join at https://solana.com/discord.  It might help to describe what you're attempting to do at a high level.  I'm not really sure what you mean by a "message".
