### ISSUE TITLE
Add `getMultipleAccounts` method

### ISSUE THREAD

**Issue by beautyfree** [solana-labs/solana-web3.js#1006]
Implement method https://docs.solana.com/developing/clients/jsonrpc-api#getmultipleaccounts

**Comment by shkschneider** [comment]
Much like https://github.com/project-serum/spl-token-wallet/blob/master/src/utils/connection.tsx#L127 ?

**Comment by alice-the-sender** [comment]
Anchor has an implementation: https://github.com/project-serum/anchor/blob/2f780e0d274f47e442b3f0d107db805a41c6def0/ts/src/utils/rpc.ts#L4

**Comment by steveluscher** [comment]
https://github.com/solana-labs/solana-web3.js/commit/8ee1be43d6da96397fa36ec690a35f8d0be8120c
