### ISSUE TITLE
[Unhandled Runtime Error] TypeError: this._agent.destroy is not a function

### ISSUE THREAD

**Issue by wan-nyan-wan** [solana-labs/solana-web3.js#1010]
I tried solana-web3.js on React and I got this error, but I succeed in the transfer of a transaction that says hello world. I don't know why I time out. Do you know something to resolve this error?
![image](https://user-images.githubusercontent.com/63966451/107505257-c318e600-6bdf-11eb-92ce-b4ffe7311317.png)

**Comment by jstarry** [comment]
Thanks for the report @wan-nyan-wan, which version of `@solana/web3.js` are you using?

**Comment by wan-nyan-wan** [comment]
Thanks for replying! I use `@solana/web3.js@0.91.0`. I seem the error is the cause of empty of `Agent`.

**Comment by jstarry** [comment]
Yeah you're right. In this case, React is picking the wrong module. Do you have a simple example project that I can test a fix on?

**Comment by wan-nyan-wan** [comment]
This is a my project that occurs the error. please check it.
https://github.com/wan-nyan-wan/solana-hello-world-ui

**Comment by jstarry** [comment]
@wan-nyan-wan should have the fix deployed within an hour or so. If you have time, can you please try it out by pointing at my branch: 
```
    "@solana/web3.js": "github:jstarry/solana-web3.js#fix-bundle",
```

**Comment by wan-nyan-wan** [comment]
@jstarry Thank you for quick response! I will try the fix.
