### ISSUE TITLE
Ethereum public key is 64 bytes, but it's defined as 65 bytes

### ISSUE THREAD

**Issue by enriquefynn** [solana-labs/solana-web3.js#1012]
What to expect of the extra byte?
Am I missing something?

The reference code:
https://github.com/solana-labs/solana-web3.js/blob/6441b4d202b40f260d7502f16f56ac22cae21939/src/secp256k1-program.js#L16

Thanks :-)

**Comment by jstarry** [comment]
@enriquefynn sorry about that, looks like an implementation detail of our chosen secp256k1 library slipped in. It should be 64 bytes. Working on a fix now

**Comment by enriquefynn** [comment]
Since we're here:
Would be great to have a function `createInstructionWithAddress`. Since most clients out there do not give access to the public key directly. This function can be called within `createInstructionWithPublicKey` once the address is derived.

**Comment by jstarry** [comment]
> Would be great to have a function createInstructionWithAddress

@enriquefynn for this would you expect the address to be passed as a hex string rather than 20 byte buffer?

**Comment by enriquefynn** [comment]
@jstarry Both are ok. I think as a 20 byte buffer is fine.
The problem is that the method requires an ethereum **public key** and not an address.
The Solana instruction requires an address. When crafting the instruction the address is derived anyway. Since most APIs for Ethereum do not provide an RPC to get the public key directly, a workaround that I found was to sign a message and then recover the public key out of the signature.
Would be much better to have a method that returns the Solana instruction given an Ethereum address.

**Comment by jstarry** [comment]
> @jstarry Both are ok. I think as a 20 byte buffer is fine.

Which one is better?

**Comment by jstarry** [comment]
@enriquefynn I'm going to allow both for convenience :)

**Comment by jstarry** [comment]
Fix here: https://github.com/solana-labs/solana/pull/15626

**Comment by jstarry** [comment]
@enriquefynn done!
