### ISSUE TITLE
`naclLowLevel.gf is not a function`

### ISSUE THREAD

**Issue by faustbrian** [solana-labs/solana-web3.js#1014]
Receiving the error message `naclLowLevel.gf is not a function` when trying to use the `PublicKey` class from `node_modules/@solana/web3.js/src/publickey.js:197`. Using yarn berry if that matters and tried to rebuild the package multiple times.

**Comment by jstarry** [comment]
Hey @faustbrian thanks for the report! Can you please provide a minimal project setup which reproduces this problem?

**Comment by faustbrian** [comment]
@jstarry below are steps to reproduce the issue, the project requires the use of yarn.

```
git clone git@github.com:ArkEcosystem/platform-sdk.git -b nacl-repro
cd platform-sdk
yarn install
yarn test src/services/identity.test.ts
```

<img width="1998" alt="Screenshot 2021-03-01 at 5 38 23" src="https://user-images.githubusercontent.com/22145591/109449130-58c1cb80-7a50-11eb-8951-52baacaae606.png">

**Comment by jstarry** [comment]
Ah, it's a TypeScript error, good to know! I'll make sure this is fixed when finishing up this: https://github.com/solana-labs/solana/pull/15484

**Comment by jstarry** [comment]
new typescript PR: https://github.com/solana-labs/solana/pull/15858

**Comment by faustbrian** [comment]
That seems to have resolved the issue, thanks!

**Comment by jstarry** [comment]
Great to hear!
