### ISSUE TITLE
Assertion failed error on recent versions

### ISSUE THREAD

**Issue by aaronovz1** [solana-labs/solana-web3.js#1018]
Seeing another regression since 0.90.5:

This happens after a few minutes on https://github.com/project-serum/oyster-swap after connecting the Sollet wallet.
![image](https://user-images.githubusercontent.com/20787054/113174478-424d9200-91ff-11eb-824d-415419a2ce4e.png)

**Comment by jstarry** [comment]
@aaronovz1 which version of web3 is happening on?

**Comment by aaronovz1** [comment]
@jstarry  The latest version 1.2.5

**Comment by jstarry** [comment]
@aaronovz1 check https://github.com/project-serum/oyster-swap/pull/41 for the fix

**Comment by aaronovz1** [comment]
Thanks!
