### ISSUE TITLE
@solana/web3.js - Version 1.2.5: UnhandledPromiseRejectionWarning when running `onLog` listener

### ISSUE THREAD

**Issue by mgild** [solana-labs/solana-web3.js#1019]
Upon opening a websocket to listen for program log events, the program log becomes bloated with the following error:
```
(node:41479) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node p
rocess on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
(node:41479) UnhandledPromiseRejectionWarning: StructError: At path: result.value.err -- Expected an object, but received: "AccountInUse"
    at validate (/xyz/node_modules/superstruct/src/struct.ts:184:19)
    at Object.create (/xyz/node_modules/superstruct/src/struct.ts:135:18)
    at Connection._wsOnLogsNotification (/xyz/node_modules/@solana/web3.js/src/connection.ts:3208:17)
    at Client.emit (/xyz/node_modules/eventemitter3/index.js:181:35)
    at /xyz/node_modules/rpc-websockets/dist/lib/client.js:425:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jstarry** [comment]
Thanks for the report @mgild! I'm a little surprised that you managed to get an `AccountInUse` error, I didn't think those would get reported. What parameters are you passing to the `onLogs` method and which endpoint are you using?

**Comment by mgild** [comment]
Happy to help :)

Im doing a very vanilla call to the onLogs listener:

`connection.onLogs(aggregatorPid, async function (logs, context){...});`

From within the callback, I do trigger a number of follow up transactions, which seems to be associated with occurrence of the errors popping up in the logs.

**Comment by mgild** [comment]
These tests are running on localnet (now `solana-test-validator`)

**Comment by jstarry** [comment]
Thanks for the context @mgild! I have a fix here: https://github.com/solana-labs/solana/pull/16348 and the real fix will be to filter those errors out on the server here: https://github.com/solana-labs/solana/issues/16339

**Comment by mgild** [comment]
Thanks @jstarry for the quick turnaround :)

The exception is fixed now but there is still a great deal of log bloat from `DuplicateSignature` `AccountInUse`.

Can these logs be disabled as well?

**Comment by jstarry** [comment]
Definitely, that has already been fixed and will be released soon
