### ISSUE TITLE
PublicKey::findProgramAddress can generate nonce + address data which is invalid on-chain

### ISSUE THREAD

**Issue by bonedaddy** [solana-labs/solana-web3.js#1021]
Ocassionally I will run into issues when attempting to find a program address off-chain that results in nonce data that when used to find the same address on-chain fails to find a correct address producing the error 

```
 Program failed to complete: Could not create program address with signer seeds: Provided seeds do not result in a valid address
```

For example my unit tests generated the address `EDEskHykrfDMkQsFMwkkuPTVBsZeuBYqL9ApN2To6tyj` but attempting to use this address with the provided seed + nonce on-chain results in an error `Program failed to complete: Could not create program address with signer seeds: Provided seeds do not result in a valid address`

**Comment by jstarry** [comment]
@bonedaddy could you provide an example of this with the generated address and nonce along with the program id and seeds you used.

**Comment by jstarry** [comment]
I believe this was due to using different seeds in JS from what was used in the Rust program
