### ISSUE TITLE
Add support for custom headers

### ISSUE THREAD

**Issue by linuskendall** [solana-labs/solana-web3.js#1023]
For RPC services, it would be helpful if developers could add custom HTTP headers to outgoing requests. The headers would take the form `X-<Custom Header Name>`. 

The headers could be used by for example loadbalancers to provide server affinity or to identify particular requests (i.e. `X-Affinity: <identifier>`). A further example of the type of behaviours we could implement with custom headers could be:
https://github.com/solana-labs/solana/issues/15705

If there can be an optional argument to `createRpcClient` and the constructor of the connection object that allows the header dict to be expanded with custom values. This may even be a generic way to support authorization/bearer tokens described in issue #1022.

**Comment by jstarry** [comment]
@oJshua this was fixed right?

**Comment by oJshua** [comment]
@jstarry Yes it was. It'd be helpful if we added some documentation. I can look into that this week.
