### ISSUE TITLE
Expose filter parameter on onProgramAccountChange 

### ISSUE THREAD

**Issue by aaronovz1** [solana-labs/solana-web3.js#1024]
Currently, there isn't a way to filter accounts when subscribing to the program account changes. The underlying RPC supports this but it is not exposed in the web3 API. This is causing a lot of extra load on the RPC nodes for our use case.

https://docs.solana.com/developing/clients/jsonrpc-api#programsubscribe

**Comment by CriesofCarrots** [comment]
@oJshua , follow-up to https://github.com/solana-labs/solana/pull/16448?

**Comment by oJshua** [comment]
@CriesofCarrots sure, I'll grab it.

**Comment by thanhnguyennguyen** [comment]
Can you give an example of using `onProgramAccountChange` ?

**Comment by steveluscher** [comment]
Fixed by https://github.com/solana-labs/solana/pull/16448.
