### ISSUE TITLE
Can not build web3.js using `esbuild`

### ISSUE THREAD

**Issue by nonken** [solana-labs/solana-web3.js#1025]
I have a simple `client.js`

```js
import { Connection, SystemProgram, clusterApiUrl } from '@solana/web3.js';
```

And create a bundle using

```bash
esbuild ./client.js --bundle --outfile=./build/js/client.js
```

When including the bundled file on a simple page I am getting a bunch of bundling issues and can not use the output bundle. 

```
Uncaught TypeError: require_elliptic2(...) is not a function
```

The issue is likely coming from https://github.com/cryptocoinjs/secp256k1-node/blob/master/elliptic.js 

**Fix:**

When using `elliptic` directly instead of `secp256k1`, the bundle works: https://github.com/solana-labs/solana-web3.js/blob/171c73ee938c2bd12f0a0785e52d076c3f58649d/src/secp256k1-program.ts#L3 I don't know if this is a possible fix though or if `secp256k1` is needed for node envs?

**Comment by NorbertBodziony** [comment]
Maybe is better to get full support esbuild bundlers like Vite/Snowpack https://github.com/solana-labs/solana-web3.js/issues/1036 out of the box ?
