### ISSUE TITLE
Transaction history for account

### ISSUE THREAD

**Issue by PeterBenc** [solana-labs/solana-web3.js#1028]
Hi, I have one question regarding the API. 

How would one proceed to get a transaction history for an account?

From what I get from the API documentation, it seems the only way is to get transaction history is to call 

```
const confirmedSignatures = (await connection.getConfirmedSignaturesForAddress2(publicKey)).map(
    ((x) => x.signature),
  )
const confirmedTxs = await connection.getParsedConfirmedTransactions(confirmedSignatures)
  ```
  
  and then for every tx map accounts to preBalances and postBalances.
 ```
const accountAddresses = tx.transaction.message.accountKeys.map((account) => account.pubkey.toString())
  const addressEffects = accountAddresses.map((address, i) => {
    return {
      address,
      preBalance: tx.meta?.preBalances[i],
      postBalance: tx.meta?.postBalances[i],
    }
  })
  ``` 
  
  
 Is this the way? Seems strange to me for and blockchain API to not have transaction history call. Am I missing something? 
 
 Thnx in advance.

**Comment by PeterBenc** [comment]
Found probably the answer here #992

**Comment by jstarry** [comment]
@PeterBenc yeah it's annoying to have to call two separate methods. Feel free to chime in https://github.com/solana-labs/solana/issues/12411 here to bubble this issue up again. Going to close this issue in favour of that one

**Comment by PeterBenc** [comment]
I see, thanks for the reply :+1:
