### ISSUE TITLE
How to decode base64 binary?

### ISSUE THREAD

**Issue by narco1epsy** [solana-labs/solana-web3.js#1029]
I'm using connection.onAccountChange() method.
I receive Buffer data.
How can I get correct string?

Node.js v14.15.1
My code:
connection.onAccountChange(marketAddress, (accountInfo) => {
        console.log(accountInfo.data.toString('base64'));
        console.log(accountInfo.data.toString());
    });

--
Output:
c2VydW0DAAAAAAAAAB0iBqHmqsuQv/vlgbIYd468j5sECE+8lQ4cJgGH3wbVAAAAAAAAAAA3mYzL8tBFi2FcvMaxo2fEdJ6f73MGYi4bG1iRASC8msb6evO+2606PWXzaqvJdDGxu+TC0vbg5HymAgNFL11h4t9Nx4farJ4Sb0/nfUS+0VDffl2c0F2hT0/XPY/JCkUgVZFLHAAAAAAAAAAAAAAAD00WHI8bhHooVGwnIGPDQbd5VjC4DEevth+4Ds3V/r10AEl6tAEAAPIM068EAAAAZAAAAAAAAAAf9gbPJSEbCeqGXWDf1cV5CTd6CePz5Gjigcsyjs9lI+/w+9BSeuQye7FyvFs3KivCx8WjrB88Rj5JqCKgP+85938MyW7rz0Hk8HyYjIIeWvh/34J2ia06tG5iuGP36bq1HfX+RznsrPsoFrjx4ioT9mCS60PPfmTyP2AgaFUQXaCGAQAAAAAAZAAAAAAAAAAAAAAAAAAAAIeSRtIBAAAAcGFkZGluZw==
serum"��ː��偲w���O��&���7�����E�a\�Ʊ�g�t���sb.� ����z�ۭ:=e�j��t1��������|�E/]a��MǇڬ�oO�}D��P�~]��]�OO�=��
E U�KM���z(Tl' c�A�yV0�
                       G�������tIz��
                                    ӯd��%!�]`���y	7z	���h��2��e#����Rz�2{�r�[7*+��ţ�<F>I�"�?�9�
                                                                                                           �n��A��|���Z�߂v��:�nb�c�麵��G9��(���*�`��C�~d�?` hU]��d��F�padding

**Comment by jstarry** [comment]
Is this a Serum market account? If so, you can use the serum js library to decode the data I believe. https://github.com/project-serum/serum-ts

**Comment by narco1epsy** [comment]
I see, thanks for the reply👍
