### ISSUE TITLE
`Connection._subscribe` swallows critical errors

### ISSUE THREAD

**Issue by mgild** [solana-labs/solana-web3.js#1031]
https://t.ly/gP0K

Please propagate this exception to the user for graceful program handling.

This currently breaks long running services.

**Comment by jstarry** [comment]
> This currently breaks long running services.

Can you elaborate on the breakage that you're seeing? If the websocket disconnects, it should re-subscribe everything

**Comment by mgild** [comment]
I should have added the exact error in the original report.  Apologies:

The exact error I receive is:

```
signatureSubscribe error for argument [
    '<REDACTED_PUBKEY>',
   { commitment: 'confirmed' }
] socket not ready.
``` 

Perhaps the re-subscription is failing here?

**Comment by steveluscher** [comment]
This was fixed in https://github.com/solana-labs/solana/pull/29195.
