### ISSUE TITLE
TypeError: publicKey.toBase58 is not a function

### ISSUE THREAD

**Issue by downygg** [solana-labs/solana-web3.js#1032]
Hallo, I try run in js client, but I gettting this error. 

> const solanaWeb3 = require('@solana/web3.js');
const connect = new solanaWeb3.Connection("https://api.testnet.solana.com/")
connect.getBalance("3WSMGFzXAxszGUZHwvERutrGxTMfLx9F5G1VVqvj225E")
.then(function(data) {
  console.log(data)
})
.catch(function(err) {
  console.log(err)
})

Output
`TypeError: publicKey.toBase58 is not a function
    at C:\lab\solana\node_modules\@solana\web3.js\lib\index.cjs.js:3371:71
    at async Connection.getBalance (C:\lab\solana\node_modules\@solana\web3.js\l
ib\index.cjs.js:3370:12)
`

**Comment by jstarry** [comment]
The `getBalance` method accepts a `PublicKey` object so you must change this line
```js
connect.getBalance("3WSMGFzXAxszGUZHwvERutrGxTMfLx9F5G1VVqvj225E")
```
to this:
```js
connect.getBalance(new PublicKey("3WSMGFzXAxszGUZHwvERutrGxTMfLx9F5G1VVqvj225E"))
```
