### ISSUE TITLE
TypeError: Found non-callable @@iterator

### ISSUE THREAD

**Issue by downygg** [solana-labs/solana-web3.js#1034]
I try to send SOL to another account using this lib, but I getting this error while sending transcation. Anyone have any suggestion to send SOL ?

> const to = new solanaWeb3.PublicKey("XXXXXX")
 const from = new solanaWeb3.PublicKey("XXXXX")
const connect = new solanaWeb3.Connection("https://api.testnet.solana.com/")
const trans = new solanaWeb3.Transaction()

> const data = {"from_pubkey" : from,"to_pubkey" : to,"lamports" : 1000}
const tx = trans.add({"TransferParams" : data})
 connect.sendTransaction(tx,from)
 .then(function(datas) {
   console.log(datas)
 })
 .catch(function(err) {
   console.log(err)
 })

Output : 
`TypeError: Found non-callable @@iterator
    at Connection.sendTransaction (C:\lab\solana\node_modules\@solana\web3.js\lib
\index.cjs.js:4497:21)`

**Comment by jstarry** [comment]
which version of node.js and which version of `@solana/web3.js` are you using

**Comment by downygg** [comment]
`Node JS` version v12.16.3
`@solana/web3.js` version 1.12.0
