### ISSUE TITLE
Unable to find a viable program address nonce

### ISSUE THREAD

**Issue by cryptoboole** [solana-labs/solana-web3.js#1035]
I am running a local version of the raydium-ui and running into the error message in the title. Is there any documentation or any information that someone could point me to debug this issue? 

It originates to `findProgramAddress` in this file [src/publickey.ts](https://github.com/solana-labs/solana-web3.js/blob/326d800281e5df4c4f0fcfd9905a6d3316fdcbf5/src/publickey.ts#L163)

Thank you kindly!

**Comment by jstarry** [comment]
Hey @cryptoboole, if I were you I would log the errors here: https://github.com/solana-labs/solana-web3.js/blob/326d800281e5df4c4f0fcfd9905a6d3316fdcbf5/src/publickey.ts#L174

There must be something going wrong inside the try / catch

**Comment by cryptoboole** [comment]
@jstarry thank you kindly for your reply, let me check it out

**Comment by underscorepeter** [comment]
I'm experiencing the same issue and it first started at approximately the same time you created this ticket. Before then, I could  run a local version with no problems.

**Comment by jstarry** [comment]
It might be due to seeds are that too long. Try updating `@solana/web3.js` to `1.10.1` or later (current version is `1.16.1`)

**Comment by cryptoboole** [comment]
@jstarry that did the trick. I am left with CORS issues but that is more pertaining to the https://github.com/raydium-io/raydium-ui repository
