### ISSUE TITLE
Generating program address

### ISSUE THREAD

**Issue by zdbrig** [solana-labs/solana-web3.js#1037]
Hi Solana experts!

I am trying to generate Program address to make an **cross program** instruction invocation.

Not systematically , I am getting this error sometimes : 
**Error: Invalid seeds, address must fall off the curve**
The only fix I have is to change the seed, which may not work either, until I chose another seed.

Thanks

**Comment by t-nelson** [comment]
Github is not for support requests. Please visit our Discord server and ask in #developer-support. https://solana.com/discord

**Comment by jstarry** [comment]
For anyone who finds this issue later, program derived addresses need to be off the ed25519 curve and there's a 50% chance of a random address being off the curve. You can use this method: https://solana-labs.github.io/solana-web3.js/classes/publickey.html#findprogramaddress to find a nonce value that can be appended to your seeds such that the address is off the curve
