### ISSUE TITLE
transaction.compileMessage() error

### ISSUE THREAD

**Issue by xianggy** [solana-labs/solana-web3.js#1038]
Using transaction.compileMessage() to parse receiver address at block height 79949969 get errors:
`Error: No instructions provided`

How to fix it?

**Comment by jstarry** [comment]
Yes, this transaction has no instructions which is allowed: https://explorer.solana.com/tx/3f84szbYiaMd8qhaqVAYYPEsmhfaWBE1bLgVXcBAzrcJgK2Kuiv2pMvxZsHakQFdBMW7BhHJGbdSi5bizX2eNS2M

The error should be fixed soon, thanks for reporting
