### ISSUE TITLE
Example on how to airdrop some SOL to an address?

### ISSUE THREAD

**Issue by alexiskattan** [solana-labs/solana-web3.js#1044]
I was able to create the address and the token, however I'm a bit confused about where to get started using the web3 library to airdrop some tokens so I can play around with the api a bit more.  I was able to do it using the command line but am not sure about how to do it in the js lib.

**Comment by jstarry** [comment]
Thanks for the issue @alexiskattan, I just submitted a PR to add an example for this: https://github.com/solana-labs/solana/pull/17770, hope this clears things up! The web3 docs have historically been too light on examples, any help would be really appreciated. If you have the time, feel free to add more examples following the example set in the linked PR.

**Comment by alexiskattan** [comment]
Thanks for looking into it.  I would be happy to do a PR.  I wasn't able to figure out how to do it though.  Could you point me an the right direction, or where to look? I googled and search the code but there was no airdrop reference like there was in the command line version.

**Comment by jstarry** [comment]
@alexiskattan the example is live here: https://solana-labs.github.io/solana-web3.js/classes/connection.html#requestairdrop

**Comment by alexiskattan** [comment]
Thank you! Really appreciate it.  I have a better understanding of how the API fits together now and will make developing easier to people not familiar with the nitty gritty of the system.

**Comment by alexiskattan** [comment]
I tried running the code in the example and then checking the balance of the given address in the command line, but it didn't increment the value.  

used this->`solana balance  2nr1bHFT86W9tGnyvmYW4vcHKsQB3sVQfnddasz4kExM`
and made sure both were on `api.testnet.solana.com`

So I don't think that the example works. (https://solana-labs.github.io/solana-web3.js/classes/connection.html#requestairdrop)

**Comment by jstarry** [comment]
@alexiskattan I see lots of airdrops (I assume from your testing) on that account here: https://explorer.solana.com/address/2nr1bHFT86W9tGnyvmYW4vcHKsQB3sVQfnddasz4kExM?cluster=testnet

Note that the "Age" says 3 days but they are from today

**Comment by alexiskattan** [comment]
Ah got it.  When I switched the API url, I wasn't careful enough paying attention to the new dev/test url.  It works now.  Thank you for the help.

**Comment by jstarry** [comment]
Do you mean the new `api.*` URLs?

**Comment by alexiskattan** [comment]
Yes
