### ISSUE TITLE
Create New Address [RPC]

### ISSUE THREAD

**Issue by bytrislasis** [solana-labs/solana-web3.js#1046]
hello, I thought of using solana in a project.
I'm working with RPC everything is ok.
I'm trying to give each user a different address
Could you please share a sample RPC code with me?
Thank you very much in advance

**Comment by mvines** [comment]
Please join us on Discord at https://discordapp.com/invite/pquxPsq and ask your questions in the #developer-support channel. We don't provide developer support over Github Issues. Thanks!

**Comment by bytrislasis** [comment]
It says you are not authorized to post on this channel.

**Comment by mvines** [comment]
Use the #welcome channel to select a role
