### ISSUE TITLE
[web3.js] Add `getRecentPrioritizationFees` API

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1095]
See details of new method in https://github.com/solana-labs/solana/pull/27278.

**Comment by jeivardan** [comment]
@steveluscher  Is anyone currently working on this issue? Just wanted to check before starting to work on this.

**Comment by steveluscher** [comment]
Go for it! Write tests! :)

**Comment by jeivardan** [comment]
@steveluscher could you please review my changes

**Comment by jeivardan** [comment]
> @steveluscher could you please review my changes

Where do I write documentation for this new API?

**Comment by jeivardan** [comment]
Where do I write documentation for this new API?

**Comment by jeivardan** [comment]
@steveluscher could you please review my changes
