### ISSUE TITLE
Add a transaction prioritization API to the JavaScript library (@solana/web3.js)

### ISSUE THREAD

**Issue by tao-stones** [solana-labs/solana-web3.js#1099]
#### Problem

JavaScript library to utilize prioritization fee

#### Proposed Solution

TBD

**Comment by jnwng** [comment]
> whether we should create a helper prioritizeTransaction(transaction: Transaction, additionalFee: number): Transaction that does the work of prepending the right instruction to an existing transaction.

this sounds right to me—positionally, a priority fee is going to end up being different than the deterministic fees-per-signature as well as any rent exemption fees. plus since we're mutating the transaction we're gonna return a new Transaction anyway
