### ISSUE TITLE
web3.js `confirmTransaction()` must check the current status of a signature before subscribing for updates or throwing expiry errors

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1107]
#### Problem

If you call `confirmTransaction` for a signature that has _already_ been processed, the `signatureSubscribe` subscription will never fire a notification. This will certainly mean that `confirmTransaction()` will throw an expiry error for a transaction that is, in actual fact, confirmed.

First reported here: https://twitter.com/CryptoLothar/status/1536530448976863232

#### Proposed Solution

1. Before subscribing or honouring expiry signals, check the signature status using the `getSignatureStatuses` method.
2. If the signature has not been confirmed _and_ you have not received an expiry signal, subscribe for status updates.
3. Race the expiry strategy and the confirmation strategy.

**Comment by Fahad-pnw** [comment]
thank you for working on this but has this been resolved yet?

**Comment by steveluscher** [comment]
I believe so! We shipped #28290.
