### ISSUE TITLE
multiple package manager lockfiles in web3.js

### ISSUE THREAD

**Issue by wentokay** [solana-labs/solana-web3.js#1108]
#### Problem

There's a `yarn.lock` and a `package-lock.json` in web3.js

#### Proposed Solution

Pick one package manager for the project and remove the lockfile that's associated with the other one

**Comment by steveluscher** [comment]
https://github.com/solana-labs/solana-web3.js/commit/2da8c8fdbcbf720cd56ef8c4feea84bd7f6a2dcd
