### ISSUE TITLE
JSON RPC API using (u)int64 whereas JS can only handle int53

### ISSUE THREAD

**Issue by linuskendall** [solana-labs/solana-web3.js#1116]
#### Problem

The JSON API uses int64 for fields like lamports. However, the maximum safe integer in browsers is 2^53-1

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

#### Proposed Solution

Make lamports a string in the HTTP/RPC API and parse with BigInt on the web3.js client side?

**Comment by steveluscher** [comment]
I removed the ‘good first issue’ tag. I think this is rather extremely complicated, and will require a months' (years'?) long deprecation strategy for the old fields, and possibly a version bump of the RPC itself.

Some of the groundwork is already being laid in the new web3 rewrite through the use of [`bigint` at the outer edge](https://github.com/solana-labs/solana-web3.js/pull/1205) of the interface. This should let people who program apps using the new RPC to seamlessly upgrade to the new RPC methods (when we cut them over) without changing their app's code or upgrading their other dependencies.

**Comment by steveluscher** [comment]
@lorisleiva has a devilishly clever solution for this, coming to `@solana/web3.js` 2.0 (see #3196).

**Comment by steveluscher** [comment]
I can't believe this is done.
