### ISSUE TITLE
Deno Support for Web3.js API

### ISSUE THREAD

**Issue by zicklag** [solana-labs/solana-web3.js#1120]
#### Problem

I would like to use [Deno](https://deno.land) to interface with the Solana chain, but the `web3.js` API cannot import properly into deno.

#### Proposed Solution

I'm not 100% sure the best strategy for supporting Deno yet, but I might be investigating and I'll post here if I find any promising strategies.

I have tried solutions such as `esm.sh` and other Deno ESM module proxies to NPM, but none of them have been successful.

It may actually be easier to port the browser build to Deno, because Deno implements many of the browser APIs such a `fetch()`, etc.

**Comment by whymidnight** [comment]
gravedigging this to report that Deno support is somewhat functional with `esm.sh`. unfortunately, `skypack.dev` did not work for me. there are of course some things broken/incomplete like opening a websocket and lsp type definitions. at the very least, submitting transactions work.

for reference, here is a working submission of a transaction:
```typescript
// adapted from `https://stackoverflow.com/a/68167035`
import {
  Connection,
  Keypair,
  Transaction,
  clusterApiUrl,
  SystemProgram,
  LAMPORTS_PER_SOL,
} from "https://esm.sh/v111/@solana/web3.js@1.73.3/deno/web3.js";

const DEMO_FROM_SECRET_KEY = new Uint8Array([
  37, 21, 197, 185, 105, 201, 212, 148, 164, 108, 251, 159, 174, 252, 43, 246,
  225, 156, 38, 203, 99, 42, 244, 73, 252, 143, 34, 239, 15, 222, 217, 91, 132,
  167, 105, 60, 17, 211, 120, 243, 197, 99, 113, 34, 76, 127, 190, 18, 91, 246,
  121, 93, 189, 55, 165, 129, 196, 104, 25, 157, 209, 168, 165, 149,
]);
export async function TestSolTransfer() {
  // Connect to cluster
  const connection = new Connection(clusterApiUrl("devnet"));
  // Construct a `Keypair` from secret key
  const from = Keypair.fromSecretKey(DEMO_FROM_SECRET_KEY);
  // Generate a new random public key
  const to = Keypair.generate();
  // Add transfer instruction to transaction
  const transaction = new Transaction().add(
    SystemProgram.transfer({
      fromPubkey: from.publicKey,
      toPubkey: to.publicKey,
      lamports: LAMPORTS_PER_SOL / 100,
    })
  );
  // Sign transaction, broadcast, and confirm
  const signature = await connection.sendTransaction(transaction, [from]);

  console.log("SIGNATURE", signature);
  console.log("SUCCESS");
}
```
<img width="695" alt="image" src="https://user-images.githubusercontent.com/45319061/223625516-b220ca34-69c9-400e-887a-b8262b9ecd54.png">

**Comment by steveluscher** [comment]
Seems to work to me! You have to use the `npm:` specifier when importing the library.

```ts
// index.ts
import { Connection } from 'npm:@solana/web3.js';

const connection = new Connection('https://api.mainnet-beta.solana.com');
const blockHeight = await connection.getBlockHeight();

console.log('blockHeight', blockHeight);
```

…then

```shell
deno index.ts
```

🎉
