### ISSUE TITLE
web3.js: library is not tree-shakeable

### ISSUE THREAD

**Issue by johnrees** [solana-labs/solana-web3.js#1122]
#### Problem

`@solana/web3.js` is not [tree-shakeable](https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking).

I've created an [example repo](https://github.com/johnrees/treeshake-example#readme) with a short README demonstrating this issue. To summarise it very briefly...

Currently bundlers such as webpack and rollup cannot extract specific sections of code from web3.js, including the .esm.js build. This means that any project that using it will either be including the entire library or at least a significant portion of it.

Some of the issues I think this raises -

- increased bundle size means there's up to approximately 0.5MB minified JS overhead for end users to download and process
- dependencies and/or polyfills (e.g. window.crypto) which can be tricky to configure with tools like React Native, Vite/WMR, are always loaded, even if they're not required by the code that was imported by the developer
- the unused code adds more noise for auditors who try to identify 'rugs' when examining compiled bundle code

#### Proposed Solution

Perhaps the esm build could be produced by typescript's `tsc` and then be verified to be tree-shakeable with something like [agadoo](https://github.com/Rich-Harris/agadoo) as an extra CI step before publishing. I did make a quick attempt at this but it looks like it's going to need more work than just building with tsc.

The [recommended steps](https://github.com/Rich-Harris/agadoo#help-my-library-isnt-tree-shakeable-and-im-not-sure-why) by Rich Harris (rollup creator) in the Agadoo README are -

> If tree-shaking still fails, it's because Rollup thinks that there are side-effects somewhere in your code. Follow these guidelines:
> - Avoid transpilers like Babel and Bublé (and if you're using TypeScript, target a modern version of JavaScript)
> - Export plain functions
> - Don't create instances of things on initial evaluation — instantiate lazily, when the functions you export are called

**Comment by petrucioinica99** [comment]
any updates on this? i am trying to bundle a package that has solana web3 as a dependency with rollup and i keep jumping from one error to another.

**Comment by steveluscher** [comment]
The tack I'm taking at the moment is to rewrite web3.js entirely, with tree-shakeability as a core tenet. You can follow along as I build it up, piece by piece, https://github.com/solana-labs/solana-web3.js/tree/master/packages/library.
