### ISSUE TITLE
[web3.js][request] Throw custom Solana Errors instead of generic Errors

### ISSUE THREAD

**Issue by paul-schaaf** [solana-labs/solana-web3.js#1133]
#### Problem
In some places in the web3 js library, errors are thrown that could be extended with more info for downstream users of the library that want to handle and parse the error, instead of having to write code to parse the error msg for required info.

e.g. here

https://github.com/solana-labs/solana/blob/2f374df494f6a5ca8e5cbe8801b61e07a0540247/web3.js/src/connection.js#L2227

The tx signature is in the string but it could also be added to the error itself as a property.

#### Proposed Solution

Different exceptions could result in different custom errors
something like this could work for a transaction exception.

```javascript
class TransactionError extends Error {
   signature: TransactionSignature;
   commitment: Commitment;

   constructor(msg: string, signature: TransactionSignature, commitmentUsed: Commitment) {
       super(msg);
       this.signature = signature;
       this.commitment = commitmentUsed;
   }
}
```

**Comment by titouanfreville** [comment]
Hello, any news/info arround this issue ? Current errors does not seems designed to be handled as we need to parse the message to find what happen and that's a bit frustrating :) 

I am not used to JS way to handle errors so both throw custom errors or respond with dedicated messages will do, but in both case it would be nice if you provided a way to identify the errors easily. 

Thanks a lot for your work on the lib. :)

**Comment by steveluscher** [comment]
`SolanaError` lays this foundation. Follow along in #2118.
