### ISSUE TITLE
web3: Rate limiting backoff is not connection scoped

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-web3.js#1137]
#### Problem
The `Connection` class doesn't track rate limit status, rate limiting is only done on a per request basis. This means that if one request gets stuck in a rate-limit induced retry loop, other requests are unaware and contribute to further rate limiting.

#### Proposed Solution
Add connection scoped rate limiter so that any RPC request first checks if the client is being rate limited before sending a request. Add a request queue to hold requests until rate limit is lifted.

**Comment by steveluscher** [comment]
This will newly, trivially be possible in the new web3.js. Folks can create a wrapper transport that detects rate limits, and decides what to do with requests (eg. retrying) before passing them on to the client or fataling the client.

See here:

https://github.com/solana-labs/solana-web3.js/blob/7adc22b1a57cff867d2f735301725dc6384c3e5e/packages/library/src/rpc-transport.ts#L23-L33
