### ISSUE TITLE
web3.js Roadmap – February 2023 – Discussion thread

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1143]
What do you want to see accomplished in `@solana/web3.js` in the month of February 2023?

Milestone:  https://github.com/solana-labs/solana-web3.js/milestone/1

**Comment by mPaella** [comment]
Wanted to get thoughts on implementing a MultiConnection/ConcurrentConnection class, which allows the dev to specify multiple RPC URLs.

We have an implementation of this, and found it essential for reliability. Considering compression as well, with many RPCs not supporting it (at least not yet), having this would be helpful

**Comment by steveluscher** [comment]
> Wanted to get thoughts on implementing a MultiConnection/ConcurrentConnection class, which allows the dev to specify multiple RPC URLs.

You're probably really going to like what I'm cooking up for the web3.js rewrite. I'll try to remember to tag you when I have a PR ready that's relevant to this.

In the meantime, say more. How do you use multiple RPC URLs? Are the extra URLs fallbacks for a primary one? Do you round-robin them? Are some dedicated for use with certain methods? Tell me all the use cases, @mPaella.

**Comment by mPaella** [comment]
Awesome, excited to see it. Is there a central place tracking the rewrite?

The main use case for us is just protection from upstream outages; This used to be a much larger problem when RPCs/Solana were less mature, but has gotten a lot better over time. Using a simple `Promise.any()` has been sufficient in most cases, and we use it for pretty much every method.

**Comment by steveluscher** [comment]
> Is there a central place tracking the rewrite?

For background on the principles off which the rewrite will hang, take a look at #1111. For everything else just watch the `packages/library` directory, and all of the micropackages springing up around it.

**Comment by steveluscher** [comment]
Alright, that's a wrap on February. Let's take it to March! https://github.com/solana-labs/solana-web3.js/issues/1186
