### ISSUE TITLE
getTransaction(transactionId, { commitment: 'confirmed', maxSupportedTransactionVersion: 0 }) hangs sometimes

### ISSUE THREAD

**Issue by lewilewilewi** [solana-labs/solana-web3.js#1166]
I'm not sure what the cause is, but this function seems to silently hang *I think* if the transaction is too recent.

**Comment by steveluscher** [comment]
Interesting. Which encoding are you using?

Our implementation of `getTransaction()` is pretty uncontroversial – it doesn't do much beyond just calling the RPC and waiting for a response.

Are you able to produce a repro of this _just_ using the command line?

```shell
curl https://your.rpc.here.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getTransaction",
    "params": [
      "2nBhEBYYvfaAe16UMNqRHre4YNSskvuYgx3M6E4JP1oDYvZEJHvoPzyUidNgNX5r9sTyN1J9UxtbCXy2rqYcuyuv",
      "json"
    ]
  }
'
```

…filling in the signature and the encoding of course.

If you're able to reproduce this stall that way, then it's worth opening an issue [here](https://github.com/solana-labs/solana/issues/new).
