### ISSUE TITLE
getBlockHeight RPC method leaks long after confirmTransaction ends

### ISSUE THREAD

**Issue by Jac0xb** [solana-labs/solana-web3.js#1182]
**Problem:**

We noticed millions of getBlockHeight RPC calls after deploying a long-lived service to broadcast transactions for our customers. However, we only broadcast thousands of transactions a week. 

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/5273873/221097861-9ab1186a-f91d-4c4b-a222-0dd54939ac90.png">
 

Putting this wrapper on the connection showed that long after some transactions were confirmed getBlockHeight was being called.

```

      /// @ts-ignore
      const oldRequest = connection._rpcRequest;

      /// @ts-ignore
      connection._rpcRequest = function (...args) {
        const url = new URL(connection.rpcEndpoint);
        console.log(`rpc request: ${url.hostname} `, args);
        return oldRequest(...args);
      };

```

**Proposal:** 

Cache and throttle calls to getBlockHeight so multiple calls to confirmTransaction share the cached blockheight.

and/or

Find source of leak.

**Comment by Jac0xb** [comment]
My theory is that if you have too many concurrent confirmTransaction processes going, they will flood 429's which is caught and returns -1. Causing a retry and further flooding.

**Comment by steveluscher** [comment]
Love it. I just need to do some simple coalescing of these calls. Thanks for the intel!
