### ISSUE TITLE
TransactionExpiredBlockheightExceededError when using ```sendAndConfirmTransaction()``` for transferring SPL tokens in the mainnet

### ISSUE THREAD

**Issue by serginogal** [solana-labs/solana-web3.js#1197]
Problem

I am encountering an issue when using ```sendAndConfirmTransaction()``` to transfer an SPL token from one wallet to another in the mainnet. Sometimes I receive the following error: `TransactionExpiredBlockheightExceededError: Signature XXXXXXXXX has expired: block height exceeded`.
However, when I check the signature in Solscan or Solana Explorer, the transaction appears to be successful. 
I have tried using both "confirmed" and "finalized" commitment levels, but the problem still occurs.
So far I have not encountered this issue when using the devnet.

Checking around i saw this issue https://github.com/solana-labs/solana-web3.js/issues/1107 and thought this kind of problem was solved but even after upgrading to the latest version (1.73.3 at the time of posting this issue) I'm still having the problem above.

Here's a sample of the code: 

```javascript
    const instruction = createTransferInstruction(
      fromTokenAccount,
      toTokenAccount.address,
      fromWalletPublicKey,
      amount,
      [],
      TOKEN_PROGRAM_ID,
    )

    const latestBlockHash = await connection.getLatestBlockhash()
    const transaction = new Transaction().add(instruction)

    transaction.feePayer = fromWalletPublicKey
    transaction.recentBlockhash = latestBlockHash.blockhash

    const signature = await web3.sendAndConfirmTransaction(
      connection,
      transaction,
      [fromWallet],
      { commitment: 'finalized' },
    )
```

I was wondering if anyone else encountered this issue and found a solution or knows anything else I can try to troubleshoot this issue.

Thank you

**Comment by steveluscher** [comment]
Thanks for this! Can you tell me what the value of `transaction.lastValidBlockHeight` is the moment before you pass it to `sendAndConfirmTransaction`? I want to make sure that it is indeed `null`.

**Comment by serginogal** [comment]
Thank you for looking into this issue.

While the error is not consistently reproducible, I have not encountered an ```undefined``` value when retrieving ```transaction.lastValidBlockHeight``` in my testing.

Another possible reason for the error that comes to my mind could be related to the RPC node being used. I'm using Solana's public node for mainnet. 

Since ```sendAndConfirmTransaction``` involves two separate calls (```connection.sendTransaction``` and ```connection.confirmTransaction```), it is possible that if there are many requests and the RPC is slow or needs to make retries, there may be a discrepancy between the two calls, resulting in the error?

**Comment by steveluscher** [comment]
Hey @serginogal. Something's up, for sure!

* Nowhere in your sample code do you make use of `latestBlockHash.lastValidBlockHeight`, so I _expect_ `transaction. lastValidBlockHeight` to be `undefined`. The fact that you say `lastValidBlockHeight` is _not_ `undefined` on your transaction is problematic. Figure out where and why that is getting set, and to what.
* If `lastValidBlockHeight` is `undefined` on your transaction, there's no way for it to fall into the codepath that throws `TransactionExpiredBlockheightExceededError`.

Unless you can produce a repro that shows this is a bug with the library itself, let's take this to https://solana.stackexchange.com and get some more eyes on it!
