### ISSUE TITLE
Versioned transactions: Skip signature verification option

### ISSUE THREAD

**Issue by mPaella** [solana-labs/solana-web3.js#1198]
**Problem:** The keys for a compressed NFT transfer ix [don't require any signers](https://github.com/metaplex-foundation/metaplex-program-library/blob/ecb0dcd82274b8e70dacd171e1a553b6f6dab5c6/bubblegum/js/idl/bubblegum.json#L846), as either the leaf owner _or_ the leaf delegate is allowed to sign and the signature [is checked in the bubblegum program](https://github.com/metaplex-foundation/metaplex-program-library/blob/ecb0dcd82274b8e70dacd171e1a553b6f6dab5c6/bubblegum/program/src/lib.rs#L1208).

So, when using a `VersionedTransaction` you must override the instructions keys like so in order to avoid the signature verification failing
<img width="478" alt="image" src="https://user-images.githubusercontent.com/93682696/224856937-da480a6b-1f28-4d37-8554-17e672da05d1.png">

**Comment by jordansexton** [comment]
A screenshot of code isn't very easy to work with to determine where a fix should happen. Can you provide a reproduction repo with this?

**Comment by steveluscher** [comment]
cc/ @ngundotra

**Comment by ngundotra** [comment]
This is probably true. I have never used VersionedTransactions for anything involving compressed nfts

**Comment by ngundotra** [comment]
@mPaella yes you are correct. The right place to surface this issue is at the SDK level for Metaplex's Bubblegum SDK.

This is not a web3.js issue @steveluscher
