### ISSUE TITLE
Figure out how to write a test for `getInflationReward`

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1240]
Right now it's not possible to test `getInflationReward` with a local test validator because:

* Need to be able to fast-forward the validator to have at least one epoch.
* Need to prepare a fixture address that is owed an inflation/staking reward.

Figure out how to exercise this functionality and then implement the `it.todo()` blocks here:

https://github.com/solana-labs/solana-web3.js/blob/ecdf2a7b2332861871250cd5fec6c2927a2a9939/packages/rpc-transport/src/json-rpc-transport/__tests__/json-rpc-method-get-inflation-reward-test.ts#L23-L27

**Comment by AlberErre** [comment]
Hey @steveluscher I would love to deep dive on this 👀, could you assign me the issue?
