### ISSUE TITLE
web3.js Roadmap – April 2023 – Discussion thread

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1251]
What do you want to see accomplished in `@solana/web3.js` in the month of April 2023?

Milestone: https://github.com/solana-labs/solana-web3.js/milestone/3

**Comment by paulmillr** [comment]
`@noble/ed25519` can be replaced with `@noble/curves/ed25519` which is already included

`@noble/curves` can be bumped to 1.0.0

`@noble/hashes` can be bumped to 1.3.0 which will is the same version used in curves

**Comment by steveluscher** [comment]
Alright! Over to May! #1290
