### ISSUE TITLE
getProgramAccounts field withContext is not exposed

### ISSUE THREAD

**Issue by kulych** [solana-labs/solana-web3.js#1285]
## Motivation

It seems that a field `withContext` available in `getProgramAccounts` http method is not exposed via `solana-web3.js`.

## Example use case

I am working on a synchronization mechanism between http request and websocket data.
The synchronization mechanism will use `slot` as a revision field, will first connect to websocket,  save all updates and simultaneously send a request. The request response should also return `slot` so that only newer updates from websocket are then applied.

## Details

According to [getProgramAccounts documentation](https://docs.solana.com/api/http#getprogramaccounts), there is a `withContext` field available which will make the response contain `context`. 
Such field is however [not exposed by `solana-web3js`](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#getProgramAccounts).  

Similarly to the pair
- [getMultipleAccountsInfo](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#getMultipleAccountsInfo)
- [getMultipleAccountsInfoAndContext](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#getMultipleAccountsInfoAndContext)

I would expect the same for `getProgramAccounts` and (does not exist) `getProgramAccountsAndContext`.
Or adding the `withContext` boolean to the function signature. As the result type depends on this value a separate function is imo better.

**Comment by steveluscher** [comment]
> As the result type depends on this value a separate function is imo better.

Separate functions are one of the most regrettable things about this library. With Typescript, you can modulate the return type of a function depending on its inputs. Take a look how we're doing this in the new web3.js library.

https://github.com/solana-labs/solana-web3.js/blob/21cfcdda44be872192121653f0c42d0393c62f2c/packages/rpc-core/src/rpc-methods/getAccountInfo.ts#L77-L116
