### ISSUE TITLE
web3.js Roadmap – May 2023 – Discussion thread

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1290]
What do you want to see accomplished in `@solana/web3.js` in the month of May 2023?

Milestone: https://github.com/solana-labs/solana-web3.js/milestone/4

**Comment by kind3r** [comment]
Any chance of implementing [blockSubscribe](https://docs.solana.com/api/websocket#blocksubscribe) ?
I know it's marked unstable but would like to try it out to see if it's faster for our use case.

If it's acceptable I could also create an issue + PR myself.

**Comment by buffalojoec** [comment]
On to June! https://github.com/solana-labs/solana-web3.js/milestone/5

**Comment by buffalojoec** [comment]
On to June! #1352
