### ISSUE TITLE
v1.77.0 unpkg version depends on process.ENV

### ISSUE THREAD

**Issue by AntonKrutikov** [solana-labs/solana-web3.js#1315]
## Overview

<img width="779" alt="image" src="https://github.com/solana-labs/solana-web3.js/assets/440799/d66fb1df-b06d-439c-885e-8a274fff7fea">

## Steps to reproduce

1. Include https://unpkg.com/@solana/web3.js@1.77.0/lib/index.iife.js on page
2. Try access `solanaWeb3` in browser window context

## Description of bug

`process.env.TEST_LIVE` used in client build.

**Comment by steveluscher** [comment]
Ugh. I knew something was going to go wrong with that. Thanks for catching that!
