### ISSUE TITLE
ComputeBudgetInstruction.decodeInstructionType requires deprecated TransactionInstruction type as argument

### ISSUE THREAD

**Issue by mschneider** [solana-labs/solana-web3.js#1333]
TransactionInstruction is by now a legacy format, but the ComputeBudgetInstruction parser still requires it. Probably worth triaging if other functionality has the same issue. For ComputeBudget this can be solved trivially by creating an unnamed struct with the right interface, as no accountKeys are required, but for more complex instructions, having a LUT-Resolved-Message type would probably be helpful. Was already requested here https://github.com/solana-labs/solana-web3.js/issues/1098

**Comment by steveluscher** [comment]
You're absolutely right. The move to versioned transactions left the program and instruction parsers behind. I'm presently working on the transaction and instruction design of the new library, and will keep this sort of thing in mind as I design them.
