### ISSUE TITLE
VersionedTransactionMeta still uses numbers for some fields

### ISSUE THREAD

**Issue by mschneider** [solana-labs/solana-web3.js#1334]
fee, preBalances, postBalances specifically, the tokenBalances are already using bigint and string typed fields

**Comment by mschneider** [comment]
yeah exactly, do you have a reference PR how this kind of upgrade in json rpc was previously handled?

**Comment by steveluscher** [comment]
Oh, sorry, I had trouble parsing the OP. I see what you meant now.

There's no choice with these situations but to make a new field for forward compatibility and to deprecate the old.

This is basically covered by (and must start with) https://github.com/solana-labs/solana/issues/30741.
