### ISSUE TITLE
connecting to my github account, it sending request to localhost:..

### ISSUE THREAD

**Issue by QalbeHabib** [solana-labs/solana-web3.js#1357]
[http://localhost:3000/api/social-connect/github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=%2Fsettings%2F](url)

In User Setting -> connect to my github account.
it sending request to this url, please fix it. 
I realy like the new version of learnWeb3.io :)

**Comment by mcintyre94** [comment]
This is a bug in learnweb3.io which is not our website
There's nothing we can do about it and you'll need to contact them, sorry!
