### ISSUE TITLE
Experimental web3js: RPC methods with no inputs are typed `unknown`

### ISSUE THREAD

**Issue by mcintyre94** [solana-labs/solana-web3.js#1389]
## Overview

I'm trying to use `getFirstAvailableBlock`, `getEpochInfo` and `getEpochSchedule` in a refactor of Explorer. I've found that the return of `getFirstAvailableBlock` and `getEpochSchedule` are typed as `unknown` by TypeScript. However `getEpochInfo` is typed correctly even when called with no parameters, I think because it has an optional parameter. 

## Steps to reproduce

See replit: https://replit.com/@mcintyre94/web3js-unknown#index.ts 

See how TypeScript types these incorrectly:
<img width="519" alt="Screenshot 2023-07-10 at 17 39 02" src="https://github.com/solana-labs/solana-web3.js/assets/1711350/3d382cad-516c-4527-92e1-70dd5cab76e9">
<img width="519" alt="Screenshot 2023-07-10 at 17 39 15" src="https://github.com/solana-labs/solana-web3.js/assets/1711350/7082b9a6-d03c-4d2e-830c-4e2d10dd3be2">
<img width="558" alt="Screenshot 2023-07-10 at 17 39 25" src="https://github.com/solana-labs/solana-web3.js/assets/1711350/8fbdca50-6a29-4016-9c96-6985926a8bba">

We also see this in the autocomplete:
<img width="672" alt="Screenshot 2023-07-10 at 17 39 59" src="https://github.com/solana-labs/solana-web3.js/assets/1711350/0e1eca2f-f2a2-44a0-8bda-670099080639">
<img width="675" alt="Screenshot 2023-07-10 at 17 40 05" src="https://github.com/solana-labs/solana-web3.js/assets/1711350/8f0ffc91-d10f-4c2b-9939-cd7c8affd312">

I've also seen this locally using VSCode so it's not a Replit issue 

## Description of bug

As far as I can tell this only happens with RPC methods that take no inputs, either optional or required

I'm guessing we need to tighten up the proxy a bit to correctly type this case

The full message when autocompleting `getEpochSchedule` is:

```
(method) getEpochSchedule(...args: unknown[]): PendingRpcRequest<unknown> (+1 overload)
```

**Comment by steveluscher** [comment]
Shit. This is ringing some {I filed this bug with TypeScript} bells that I hoped never to hear again.

**Comment by steveluscher** [comment]
This? https://github.com/microsoft/TypeScript/issues/53508

**Comment by mcintyre94** [comment]
That looks like the one and doesn't seem to have a fix

A hacky workaround that would probably work would be adding an optional empty config object to these functions. Easy for a caller to ignore when they write the call (and for us to document in typedocs), and then should just work like everything else from there. Think that's worth doing?

**Comment by steveluscher** [comment]
Yes please! Add it and liberally `// FIXME` it with a reference back here.
