### ISSUE TITLE
Remove hardcoded "Infinity" for WebSockets reconnect retries

### ISSUE THREAD

**Issue by c4b4d4** [solana-labs/solana-web3.js#1391]
## Motivation

What's the reason of having `Infinity` harcoded as `max_reconnects` for web sockets? 

Thanks to this, the connecting method sent 2M requests to an RPC in a very small window (the RPC was bugged, and was disconnecting all the time), and because it has `Infinity` hardcoded as `max_reconnects` the method never stopped trying.

Here is what is hardcoded, and what I suggest to change:

https://github.com/solana-labs/solana-web3.js/blob/4539c77a5a961bd25bbde078f3678325bfe15550/packages/library-legacy/src/connection.ts#L3158

## Details

Just add an extra option/parameter in the config to be able to pass the `max_reconnects`, and remove `Infinity` as the default

**Comment by avijeetpandey** [comment]
I want to work on this enhancement can some-one please assign this to me ?

**Comment by steveluscher** [comment]
Which RPC was this, @c4b4d4? Was this Helius, a week ago?

**Comment by c4b4d4** [comment]
> Which RPC was this, @c4b4d4? Was this Helius, a week ago?

Yes, I found out about the hardcoded `Infinity` in the retries while debugging its last week incident.

**Comment by steveluscher** [comment]
Yeah, fun fact, I actually was the one who diagnosed the bug down to the RPC returning a status code 1005 on explicit close rather than 1000.

Sorry about the network spam.

That said, we can't remove this or make it configurable without a recovery strategy (eg. a coded error that gets thrown once the retries are exhausted). I'll keep this in mind while rewriting the subscriptions infra for web3.js; I don't think it's worth implementing in the current library.

**Comment by c4b4d4** [comment]
Well, isn't it the same case for non-websocket connections. Those already throw an error when the retries are exhausted, don't they?

Anyways, regardless of the decision, thanks for clarifying it.

And to have it addressed on my side, while an update to the library comes, I'm overriding it like this:

```
connection._rpcWebSocket.max_reconnects = 15;
connection._rpcWebSocket.reconnect_interval = 1500;
```

Based on the Helius incident and normal network disconnections... Do you think having `max_reconnects` set to `15` would get me in a bad scenario? I'm not aware what makes the websocket to close and reconnect, aside a network failure.
