### ISSUE TITLE
bug: getRecentPrioritizationFees with commitment setting in constructor would always fail

### ISSUE THREAD

**Issue by ZhengYuTay** [solana-labs/solana-web3.js#1417]
## Overview
getRecentPrioritizationFees with commitment setting in constructor would always fail

## Steps to reproduce
this would work
```
new Connection(connection.rpcEndpoint).getRecentPrioritizationFees({
      lockedWritableAccounts: [WRAPPED_SOL_MINT],
});
```

this would fail with `SolanaJSONRPCError: failed to get recent prioritization fees: Invalid parameters: Expected from 0 to 1 parameters.`
```
 new Connection(connection.rpcEndpoint, 'confirmed').getRecentPrioritizationFees({
      lockedWritableAccounts: [WRAPPED_SOL_MINT],
}); // failed
```

## Description of bug
-

**Comment by steveluscher** [comment]
I can't reproduce this: https://jsfiddle.net/xmhubeqw/

Make a JSFiddle that reproduces the bug, and I'll be happy to take another look!
