### ISSUE TITLE
JSON RPC HTTP Methods Missing from Experimental Lib

### ISSUE THREAD

**Issue by buffalojoec** [solana-labs/solana-web3.js#1449]
- [x] [`getBlock`](https://docs.solana.com/api/http#getblock)
- [x] [`getBlockCommitment`](https://docs.solana.com/api/http#getblockcommitment)
- [x] [`getBlocksWithLimit`](https://docs.solana.com/api/http#getblockswithlimit)
- [x] [`getClusterNodes`](https://docs.solana.com/api/http#getclusternodes)
- [x] [`getFeeforMessage`](https://docs.solana.com/api/http#getfeeformessage)
- [x] [`getGenesisHash`](https://docs.solana.com/api/http#getgenesishash)
- [x] [`getHealth`](https://docs.solana.com/api/http#gethealth)
- [x] [`getHighestSnapshotSlot`](https://docs.solana.com/api/http#gethighestsnapshotslot)
- [x] [`getIdentity`](https://docs.solana.com/api/http#getidentity)
- [x] [`getInflationGovernor`](https://docs.solana.com/api/http#getinflationgovernor)
- [x] [`getInflationRate`](https://docs.solana.com/api/http#getinflationrate)
- [x] [`getLargestAccounts`](https://docs.solana.com/api/http#getlargestaccounts)
- [x] [`getLeaderSchedule`](https://docs.solana.com/api/http#getleaderschedule)
- [x] [`getMinimumBalanceForRentExemption`](https://docs.solana.com/api/http#getminimumbalanceforrentexemption)
- [x] [`getMultipleAccounts`](https://docs.solana.com/api/http#getmultipleaccounts)
- [x] [`getProgramAccounts`](https://docs.solana.com/api/http#getprogramaccounts)
- [x] [`getRecentPrioritizationFees`](https://docs.solana.com/api/http#getrecentprioritizationfees)
- [x] [`getSignatureStatuses`](https://docs.solana.com/api/http#getsignaturestatuses)
- [x] [`getSlotLeader`](https://docs.solana.com/api/http#getslotleader)
- [x] [`getStakeActivation`](https://docs.solana.com/api/http#getstakeactivation)
- [x] [`getTokenAccountBalance`](https://docs.solana.com/api/http#gettokenaccountbalance)
- [x] [`getTokenAccountsByDelegate`](https://docs.solana.com/api/http#gettokenaccountsbydelegate)
- [x] [`getTokenAccountsByOwner`](https://docs.solana.com/api/http#gettokenaccountsbyowner)
- [x] [`getTokenSupply`](https://docs.solana.com/api/http#gettokensupply)
- [x] [`getVersion`](https://docs.solana.com/api/http#getversion)
- [x] [`simulateTransaction`](https://docs.solana.com/api/http#simulatetransaction)

**Comment by buffalojoec** [comment]
Current PRs:
- [ ] `getBlocksWithLimit`
- [ ] `getGenesisHash`
Local stuff I've got in progress:
- [ ] `getBlock`
- [ ] `getFeeForMessage`
- [ ] `getIdentity`
- [ ] `getInflationGovernor`
- [ ] `getInflationRate`

**Comment by mcintyre94** [comment]
`simulateTransaction` up next!

**Comment by buffalojoec** [comment]
I'll handle `getBlock`, and then we can close this bad boy!
