### ISSUE TITLE
web3.js Roadmap - August 2023 - Discussion Thread

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1469]
What do you want to see accomplished in `@solana/web3.js` in the month of August 2023?

Milestone: https://github.com/solana-labs/solana-web3.js/milestone/7

**Comment by redhair** [comment]
Hey @steveluscher would love to see continued work on the tree-shaking experimental lib.

**Comment by steveluscher** [comment]
Oh, we're doin' it! Transaction confirmation is next. Then probably subscriptions.

**Comment by steveluscher** [comment]
On to [September](https://github.com/solana-labs/solana-web3.js/milestone/8)!
