### ISSUE TITLE
Discuss: pick a single term between 'tokenAccount' and 'associatedTokenAccount' and use it consistently

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#1569]
## Motivation

Not strictly for this repo, also affects https://github.com/solana-foundation/developer-content, particularly [terminology](https://github.com/solana-foundation/developer-content/blob/main/docs/terminology.md) and https://github.com/solana-labs/solana-program-library.

We move between two terms that mean the same thing:

 - Associated Token Account, eg `getAssociatedTokenAddress()` from `@solana/spl-token.js`
 - Token account (ie, `connection.getTokenAccountBalance()` from `@solana.web3.js`)

Both mean a user's holdings of a particular token, a PDA derived from the user's pubkey and the token mint account.

Using two terms for the same term is confusing. Two different terms imply two different things.

We should chose either one of these words, and officially mark the other as deprecated.

## Example use case

A developer wishes to check the balance of something described in Solana educational materials as an 'associated token account'. They see in the docs that there is a function `connection.getTokenAccountBalance()` however the developer is are unsure if this function does what the developer wants.

### Benefits of consistently using `token account`

 - 'token account' is smaller than 'token mint account'
 - web3.js uses `tokenAccount` in its function names already

In this case, we'd add entries for 'associated token account' and ATA to terminology, tell people the preferred term is simply token account, and refer people to the definition for 'token account'

### Benefits of consistently using `associated token account`

 - Avoids confusion with 'token mint account' 
 - Existing docs frequent use 'associated token account' or ATA.

In this case we'd update function names to `getAssociatedTokenAccountBalance()` or `getATABalance()` etc. and mark the older names as deprecated.

**Comment by mikemaccana** [comment]
@jordansexton would be good to get this into some form of structure (parents and children and their relationships). 

```
term1
  owns
    term2
       consisting of
         term3
         term4
         
 term5
   creates
     term6
```


I tried to do that in this comment, but got stuck on:

> ATAs are a subset of token accounts, those derived from the ATA program. It's possible to derive an ATA using a different Token program (e.g. Token22)

If ATAs are a subset referring to those derived from ATA program, then there can't be ATAs derived from different programs.

**Comment by jordansexton** [comment]
> there can't be ATAs derived from different programs.

There can indeed. The ATA is derived by the ATA program using a provided Token program account ID as a seed.

https://github.com/solana-labs/solana-program-library/blob/f35dc5fdb6fc01d054afc51a6ea5a10307a48e3b/associated-token-account/program/src/processor.rs#L78C21-L78C21

This account can be any program, which is why Token22 doesn't have a different ATA program.

**Comment by mikemaccana** [comment]
> There can indeed. 

I didn't say there couldn't be, just that there couldn't be if ATAs are defined as "a subset of token accounts referring to those derived from ATA program" per your previous comment.

I appreciate you're trying to help though - let's do a call and get one single version of the truth. I'll buzz you on Slack.

**Comment by mikemaccana** [comment]
<img width="1157" alt="Screenshot 2023-09-04 at 17 53 53" src="https://github.com/solana-labs/solana-web3.js/assets/172594/3a589f06-22b4-4933-ac4d-93488ff97b97">

Pasting in @jordansexton 's for future reference by others - thanks Jordan!

**Comment by steveluscher** [comment]
Oof. Narrowly missed a great https://solana.stackexchange.com here. Copy paste all this as a Q&A (ie. open a question and answer it yourself)?

**Comment by mikemaccana** [comment]
@steveluscher Good idea and done https://solana.stackexchange.com/questions/7507/what-is-the-difference-between-a-token-account-and-an-associated-token-account cc @jordansexton
