### ISSUE TITLE
[experimental] API for transaction builder

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1573]
# Problem

Awesome things about the purely functional transaction builder interface in the new web3.js:

1. You only bundle the code that you _actually_ use. Don't use nonces in your transactions? Don't get any of that logic.
2. You can bake in certain values via currying, pass those functions around as values, and use them over and over.
    ```ts
    const makeStevePayTheFees = setTransactionFeePayer.bind(null, 'S1eV33JH21H32G312gHASDjksda4s');
    const paidTransactions = unpaidTransactions.map(makeStevePayTheFees);
    ```

Bad things:

1. TypeScript is MAX PAIN if you try to reassign like this:
    ```ts
    let tx = createTransaction({version: 0});
    tx = setTransactionFeePayer('S1eV33JH21H32G312gHASDjksda4s', tx); // `tx` is _not_ `ITransactionWithFeePayer` now.
    ```
2. The alternative is even worse:
    ```ts
    const tx = createTransaction({version: 0});
    const txWithFeesPaid = setTransactionFeePayer('S1eV33JH21H32G312gHASDjksda4s', tx);
    const txWithFeesPaidAndBlockhashLifetimeSet = setTransactionLifetimeUsingBlockhash({/* ... */}, tx);
    ```

# Solutions

## Stop time until the JS pipeline operator is ready

One day, you will interact with this API [like this](https://github.com/tc39/proposal-pipeline-operator):

```ts
const tx = createTransaction({version: 0})
  |> setTransactionFeePayer('S1eV33JH21H32G312gHASDjksda4s', %)
  |> setTransactionLifetimeUsingBlockhash({/* ... */}, %);
```

## Create a builder

Doing this would undo _all_ of the benefits of tree shaking. There would be no way to shake away the code that you don't use (eg. nonce builders) because _every_ function would be bound to the builder instance.

This API _kills_ the ability to customize the steps. It also makes it impossible for an async step sneak in the middle; it either has to be _all_ async or _not at all_. See the cool `blockhashMeTriton` example below, which is made impossible with this ‘fluent’ builder API.

```ts
const tx = createTransaction({version: 0})
  .setTransactionFeePayer('S1eV33JH21H32G312gHASDjksda4s')
  .setTransactionLifetimeUsingBlockhash({/* ... */});
```

## Create a builder into which you have to inject dependencies as ‘capabilities’

This would give you the API of a builder, but demand that you declare the dependencies explicitly to imbue it with ‘capabilities’. This will be an interesting TypeScript exercise, but we've already achieved the impossible with the RPC API, right?

This API might be more customizable than the one above, but there may be some rough edges when it comes to async code.

```ts
const createTransaction = makeTransactionBuilderWithCapabilities({
  setTransactionFeePayer,
  setTransactionLifetimeUsingBlockhash,
});
const tx = createTransaction({version: 0})
  .setTransactionFeePayer('S1eV33JH21H32G312gHASDjksda4s')
  .setTransactionLifetimeUsingBlockhash({/* ... */});
```

## Tell people to compose all of their transactions in pointfree style

LOL no.

```ts
const tx =
  setTransactionLifetimeUsingBlockhash({/* ... */},
    setTransactionFeePayer('S1eV33JH21H32G312gHASDjksda4s',
      createTransaction({version: 0}),
    ),
  );
```

## Ship a compose helper

This has all of the bad characteristics of composing functions in pointfree style, while also being able to confuse people who don't already know that compose operates from right-to-left.

```ts
const tx = compose(
  setTransactionLifetimeUsingBlockhash.bind(null, {/* ... */}),
  setTransactionFeePayer.bind(null, 'S1eV33JH21H32G312gHASDjksda4s'),
  createTransaction,
)({version: 0});
```

## Ship a pipe helper

Pipe is all the bad things about compose, except with the nice feature of at least reading left-to-right and taking in a value as the first argument.

```ts
const tx = pipe(
  createTransaction({version: 0}),
  setTransactionFeePayer.bind(null, 'S1eV33JH21H32G312gHASDjksda4s'),
  setTransactionLifetimeUsingBlockhash.bind(null, {/* ... */}),
);
```

Now at least you can do nice things and create ‘readable’ (for some definition) builders like this:

```ts
/**
 * All the setup code
 */
function makeStevePay(tx: Transaction) {
  return setTransactionFeePayer(
    'S1eV33JH21H32G312gHASDjksda4s' as Base58EncodedAddress,
    tx,
  );
}
async function blockhashMe(rpc: Rpc<GetLatestBlockhashApi>, tx: Transaction) {
  return setTransactionLifetimeUsingBlockhash(
    await rpc.getLatestBlockhash(),
    tx,
  );
}
const tritonDevnetTransport = createDefaultRpcTransport({ url: 'https://api.devnet.solana.com' });
const rpc = createSolanaRpc({transport: tritonDevnetTransport});
const blockhashMeTriton = blockhashMe.bind(null, rpc);

/**
 * Your actual app code
 */
const tx = await pipe(
  createTransaction({version: 0}),
  makeStevePay,
  blockhashMeTriton,
);
```

## Pipe, with autobinding

We could develop a custom syntax that expresses ‘take this value, and apply these functions with these arguments.’

```ts
const tx = pipe(
  createTransaction({version: 0}),
  [setTransactionFeePayer, 'S1eV33JH21H32G312gHASDjksda4s' as Base58EncodedAddress],
  [setTransactionLifetimeUsingBlockhash, await rpc.getLatestBlockhash()],
);
```

The implementation would look something like this, but with a whole ton of TypeScript magic:

```ts
function pipe(value, ...fnsToApply) {
  return fnsToApply.reduce(([fn, ...args], acc) => fn(...args, acc), value);
}
```

One drawback of this API is that you no longer get TypeScript _autocomplete_ for your function arguments (ie. `setTransactionFeePayer`)

## Edit this issue to suggest more!

**Comment by buffalojoec** [comment]
> ## Pipe, with autobinding
> We could develop a custom syntax that expresses ‘take this value, and apply these functions with these arguments.’
> 
> ```ts
> const tx = pipe(
>   createTransaction({version: 0}),
>   [setTransactionFeePayer, 'S1eV33JH21H32G312gHASDjksda4s' as Base58EncodedAddress],
>   [setTransactionLifetimeUsingBlockhash, await rpc.getLatestBlockhash()],
> );
> ```

This one is at least starting to look a bit more user-friendly. I'm assuming since the user is passing a function this doesn't cause tree-shake issues because the `reduce` only invokes the functions they provide?

I'm trying to wrap my head around preserving tree-shake while doing something a little more comfortable like:

```typescript
const tx = createTransaction({
  version: 0,
  feePayer: 'S1eV33JH21H32G312gHASDjksda4s' as Base58EncodedAddress,
  setTransactionLifetimeUsingBlockhash, await rpc.getLatestBlockhash(),
})
```

You could still reduce it with a mapping of `Object.keys()` but you'd need to have something like a switch case for all the functions, which makes them non-shakeable right?

Tricky

**Comment by buffalojoec** [comment]
> Now at least you can do nice things and create ‘readable’ (for some definition) builders like this:
> 
> ```ts
> /**
>  * All the setup code
>  */
> function makeStevePay(tx: Transaction) {
>   return setTransactionFeePayer(
>     'S1eV33JH21H32G312gHASDjksda4s' as Base58EncodedAddress,
>     tx,
>   );
> }
> async function blockhashMe(rpc: Rpc<GetLatestBlockhashApi>, tx: Transaction) {
>   return setTransactionLifetimeUsingBlockhash(
>     await rpc.getLatestBlockhash(),
>     tx,
>   );
> }
> const tritonDevnetTransport = createDefaultRpcTransport({ url: 'https://api.devnet.solana.com' });
> const rpc = createSolanaRpc({transport: tritonDevnetTransport});
> const blockhashMeTriton = blockhashMe.bind(null, rpc);
> 
> /**
>  * Your actual app code
>  */
> const tx = await pipe(
>   createTransaction({version: 0}),
>   makeStevePay,
>   blockhashMeTriton,
> );
> ```

I actually think this isn't bad, it's pretty clean. The drawback I see is moreso for beginner devs, where this might be a little confusing. However, that's not to say we can't just have good docs 🙈

**Comment by buffalojoec** [comment]
> This API might be more customizable than the one above, but there may be some rough edges when it comes to async code.
> 
> ```ts
> const createTransaction = makeTransactionBuilderWithCapabilities([
>   setTransactionFeePayer,
>   setTransactionLifetimeUsingBlockhash,
> ]);
> const tx = createTransaction({version: 0})
>   .setTransactionFeePayer('S1eV33JH21H32G312gHASDjksda4s')
>   .setTransactionLifetimeUsingBlockhash({/* ... */});
> ```

All right, last comment for now.

I think this might be my favorite one, albeit a bit redundant, but I think most people will appreciate the one setup step in exchange for the bundling benefits.

Almost seems like this thing would just have to be all `async` though. However, if key operations are going `async` and people are just about always asynchronously fetching a blockhash while building transactions, this might not be a big deal. Maybe we provide a nice little way to build multiple and `await` them all at once?

**Comment by mcintyre94** [comment]
Just for my understanding, can we improve the typing of eg `setTransactionFeePayer` so it's less painful to use like this? A lot of these solutions look like they'll require complex/clever typing, is there an option to do that on the base functions instead?

- I don't see the builder option being usable for async and losing the tree shaking sucks. It doesn't seem like a good fit here. But this looks the closest syntactically to where the pipeline operator ends up, which is nice! 
- The capabilities builder is a neat workaround for some of those issues, but I'm still not sure it'd work nicely with async code. It's nice that you could abstract functionality here (like make `setTransactionFeePayer` use whatever fee payer you always use), but doing it with this capabilities model wouldn't be super clear IMO - especially if you want to write a helper that does multiple things. 
- I like pipe! It'd also be much easier to debug this (put a breakpoint/log in your piped functions) than either of the builder options. And composability/abstractions seem to make a lot more sense here. I think this is the most 'just javascript' which is a good thing here
- Pipe with autobinding is clever, but I think it'd lose typescript autocomplete on the function calls? Especially if there were multiple parameters that could be a lot less nice to write.

Just to check, if you had pipe (without auto-binding) could you write your example more compactly if you wanted with arrow functions like this?

```ts
const tx = await pipe(
  createTransaction({version: 0}),
  tx => setTransactionFeePayer('S1eV33JH21H32G312gHASDjksda4s' as Base58EncodedAddress, tx),
  async tx => setTransactionLifetimeUsingBlockhash(await rpc.getLatestBlockhash(), tx),
);
```

And for the pipe with auto-binding could you write the example using the custom functions like this?

```ts
const tx = pipe(
  createTransaction({version: 0}),
  [makeStevePay],
  [blockhashMeTriton],
);
```

**Comment by 2501babe** [comment]
at the risk of being thrown out the window, why dont we just mutate the object?

**Comment by steveluscher** [comment]
> at the risk of being thrown out the window, why dont we just mutate the object?

```ts
const dinnerTx = createDinnerTransaction({michelinStars: 3});
const callumDinnerTx = setTransactionFeePayer('callum', dinnerTx);
const joeDinnerTx = setTransactionFeePayer('joe', dinnerTx);
const steveDinnerTx = setTransactionFeePayer('steve', dinnerTx);
const hanaDinnerTx = setTransactionFeePayer('hana', dinnerTx);
```

Oh btw thanks for dinner. :)

**Comment by steveluscher** [comment]
More seriously,

* You lose the ability to memoize; you can no longer tell if a transaction has been mutated using just a reference check (`===`) because the reference check will _always_ return `true`.
* You lose the ability to create copies with _structural sharing_. For instance with the immutable API we've created here you can change the fee payer on a transaction but the `instructions` array will still literally be the same object and `txHana.instructions === txSteve.instructions` will be `true` despite `txHana.feePayer === txSteve.feePayer` being `false`.
* Surprising, inscrutable bugs like in the dinner example above. Supercharged when you use a centralized data store like React state, Redux, etc; mutating the object will update it _all the way back_ to the data store which can cause extremely surprising effects (like memoized components failing to update, changes propagating across unrelated components, etc).

**Comment by 2501babe** [comment]
oh yea i didnt think about how side-effecty everything in react is, my usual flow is "create a transaction and add things to it immediately in the same function"

**Comment by buffalojoec** [comment]
Just to recap for anyone interested, we chatted offline about the various approaches here and I want to throw an update in here so it's available.

> Create a builder

We unanimously agreed that providing a builder with all sorts of functions that may or may not be used would go directly against the _massive_ tree-shaking work that's gone into this API. For that reason, a builder in the most native sense was written off.

> Create a builder into which you have to inject dependencies as ‘capabilities’

We went back & forth on this one for a little bit, but ultimately there was concern about potential widespread abuse of this capability. Specifically, it's likely we'd see a lot of libraries use the whole "kitchen sink" of builder methods, pass it around their bundle, and ultimately bloat their whole app.
While it's true that this is the problem of the developer who creates said kitchen sink, we felt that it was best to encourage best practices and remove the temptation for bad practices, at least from the base library/libraries.

> Tell people to compose all of their transactions in pointfree style

As @steveluscher's initial comment states: LOL no.

> Ship a compose helper

We deliberately skipped over this one in favor of `pipe` solely for the purpose of being able to read left-to-right.

> Pipe, with autobinding

As @steveluscher points out in the issue, and explored even further by @mcintyre94, the loss of TypeScript's autocomplete and/or IntelliSense for function parameters makes this one a less preferable approach.
Although is does serve the general purpose of a pipe, and it allows for some concise syntax, it's not worth losing those hints/helpers and any other type-checking fallout that may result.

> Ship a pipe helper

Ultimately, the pipe helper was the winner. We felt this approach allowed you to do pipe work with very little setup, as elaborated on by @steveluscher in the issue:

```typescript
/**
 * All the setup code
 */
function makeStevePay(tx: Transaction) {
  return setTransactionFeePayer(
    'S1eV33JH21H32G312gHASDjksda4s' as Base58EncodedAddress,
    tx,
  );
}
async function blockhashMe(rpc: Rpc<GetLatestBlockhashApi>, tx: Transaction) {
  return setTransactionLifetimeUsingBlockhash(
    await rpc.getLatestBlockhash(),
    tx,
  );
}
const tritonDevnetTransport = createDefaultRpcTransport({ url: 'https://api.devnet.solana.com' });
const rpc = createSolanaRpc({transport: tritonDevnetTransport});
const blockhashMeTriton = blockhashMe.bind(null, rpc);

/**
 * Your actual app code
 */
const tx = await pipe(
  createTransaction({version: 0}),
  makeStevePay,
  blockhashMeTriton,
);
```

However, @mcintyre94 also pointed out that you can use the pipe helper like so, which is also quite intuitive:

```typescript
const tritonDevnetTransport = createDefaultRpcTransport({ url: 'https://api.devnet.solana.com' });
const rpc = createSolanaRpc({transport: tritonDevnetTransport});

const recentBlockhash = await rpc.getLatestBlockhash();

const tx = await pipe(
  createTransaction({version: 0}),
  (tx) => setTransactionFeePayer('S1eV33JH21H32G312gHASDjksda4s' as Base58EncodedAddress, tx),
  (tx) => setTransactionLifetimeUsingBlockhash(recentBlockhash, tx),
);
```

### `async`

It's worth mentioning how we decided to handle `async` operations for building transactions.

In the first example _and_ @mcintyre94's comment above, you can see the use of `async` within the pipe itself for one or more transaction "mutation" functions.

Ultimately we decided that any async operations should be done outside the pipe helper, and everything within it should be synchronous.

That means:
- Gathering facts required to build the transaction _before_ it's built
  - Ex: Any required RPC calls, like fetching a recent blockhash
- Any asynchronous mutations that must be applied to the transaction _after_ it's built
  - Ex: Applying signatures using the `async` SubtleCrypto API

So things might look more like this:

```typescript
const tritonDevnetTransport = createDefaultRpcTransport({ url: 'https://api.devnet.solana.com' });
const rpc = createSolanaRpc({transport: tritonDevnetTransport});

const recentBlockhash = await rpc.getLatestBlockhash();

const tx = await pipe(
  createTransaction({version: 0}),
  (tx) => setTransactionFeePayer('S1eV33JH21H32G312gHASDjksda4s' as Base58EncodedAddress, tx),
  (tx) => setTransactionLifetimeUsingBlockhash(recentBlockhash, tx),
);
await signTransaction(key1, tx);
await signTransaction(key2, tx);
```

We can even sprinkle in some added sugar, like so:

```typescript
const tritonDevnetTransport = createDefaultRpcTransport({ url: 'https://api.devnet.solana.com' });
const rpc = createSolanaRpc({transport: tritonDevnetTransport});

const recentBlockhash = await rpc.getLatestBlockhash();

const tx = await pipe(
  createTransaction({version: 0}),
  (tx) => setTransactionFeePayer('S1eV33JH21H32G312gHASDjksda4s' as Base58EncodedAddress, tx),
  (tx) => setTransactionLifetimeUsingBlockhash(recentBlockhash, tx),
);
await signTransactionManyTimes([key1, key2, key3], tx);

// -------------------------------------------
async function signTransactionManyTimes(keys: CryptoKeyPair[], tx) {
   return Promise.all(keys.forEach(key => signTransaction(key, tx)))
}
```

### Pipe Typing

One more additional point discussed was the idea of introducing a `@solana/functional` library for functional programming helpers - such as `pipe` - that can be used to more easily interact with the new Web3 JS.

The goal is to provide a general-use pipe function that could be used for a wide range of chained-together operations, and then build onto that a transaction-specific pipe helper, that provides some type safety and autocomplete help for working specifically with a transaction.

It's up for debate as we see new use cases arise whether or not to introduce more specialized pipe helpers, but arguably one should be able to use the generalized one for anything.
