### ISSUE TITLE
Create ergonomic version of `requestAirdrop` that rolls transaction confirmation at a given finality into one

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#1579]
__Alternate title: "requestAirdrop() promise should be fulfilled when the airdrop is confirmed"__

## Motivation

Here's an excerpt from SolDev, our (Foundation's) best Solana resource:

```text
Now run the code and see if it works. You may end up with the following error in the console:

> Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.

If you get this error, it’s because your keypair is brand new and doesn’t have any SOL to cover the transaction fees. Let’s fix this by adding the following line before the call to sendPingTransaction():

await connection.requestAirdrop(payer.publicKey, web3.LAMPORTS_PER_SOL*1)
This will deposit 1 SOL into your account which you can use for testing. This won’t work on Mainnet where it would actually have value. But it's incredibly convenient for testing locally and on Devnet.
```

However this won't work - at least the first time round. The `Promise` is returned before the lamport transaction can be confirmed, and so the following `web3.sendAndConfirmTransaction()`  will run before the balance of the account being used has updated.

## Example use case

The feature will be used every time someone requests Lamports before running a transaction in devnet.

**This is important. Airdropping to get some test SOL is one of the first transactions new developers do on Solana and it should just 'work' with reasonable defaults, and without further explanation.**

## Details

Here's some code I've been using for a while. It would be very helpful to new Solana users to have something like this out of the box:

```
export const putSolIntoWallet = async (connection: Connection, publicKey: PublicKey, lamports: number) => {
  // Generate a new wallet keypair and airdrop SOL
  var airdropTransactionSignature = await connection.requestAirdrop(publicKey, lamports);

  const latestBlockHash = await connection.getLatestBlockhash();

  // Wait for airdrop confirmation
  await connection.confirmTransaction({
    blockhash: latestBlockHash.blockhash,
    lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
    signature: airdropTransactionSignature,
  });
};
```

Usage is just:

```
await putSolIntoWallet(connection, keyPair.publicKey, 1 * LAMPORTS_PER_SOL);
```

And then the user can just use the SOL they were airdropped.

What do you think? @steveluscher and @jamesrp13 in particular. 😊 The new web3.js Steve is working on might be a good time to change the defaults.

**Comment by steveluscher** [comment]
Having to understand both confirmation _and_ commitment just to get some devnet SOL to get started has definitely been annoying.

I will certainly be including a high-level wrapper like this one in the new web3.js library; I just need to finish transaction confirmation first, for which I have to finish the whole subscriptions API first. Soon. This week.

**Comment by mikemaccana** [comment]
Legend, this will make a massive different to people's first 30 mins of Solana development!

**Comment by jamesrp13** [comment]
This would be awesome! I was learning Solana development as I was writing the course. Didn't figure out that I should have added confirmations until a couple modules in, so there are definitely still some lessons that don't have the extra boilerplate code for confirming the airdrop. Even so, having a one-liner that does what those 5ish lines do would be amazing for first timers.

**Comment by mikemaccana** [comment]
For naming - `getAirdrop()` would be fine. I know we can request an airdrop and be refused, but we don't need to change the verb (same with the new `getProgramDerivedAddress()` rather than the old `findProgramAddress()`) and `get()` is more memorable.
