### ISSUE TITLE
`getAccountInfo` will error on default encoding for too large of account

### ISSUE THREAD

**Issue by buffalojoec** [solana-labs/solana-web3.js#1587]
This is not a problem with our API. This issue is merely to discuss how we should handle this potentially harmful RPC behavior.

From the documentation:

```
base58 is slow and limited to less than 129 bytes of Account data.
```

Even thought it's slow and limited, it's the default encoding. If a user does not specify encoding, `base58` is attempted, and if the account is too large, it will error.

Currently, our API exactly mimics the RPC, and thus is up-to-spec. I'm curious if it's worth exploring one of the two options:
1. Explicitly describe this behavior in our errors
2. Use a different default

**Comment by mcintyre94** [comment]
One option here would be to deprecate the overloads that either specify base58 or don't specify the encoding. We did that with `sendTransaction` and `simulateTransaction` for example: https://github.com/solana-labs/solana-web3.js/blob/25a15aa1f7d19bd97b372b2b6410c59f87ecc8f5/packages/rpc-core/src/rpc-methods/sendTransaction.ts#L15-L19

Then your code editor hopefully points you in a sensible direction! 

Though the RPC docs are a bit different between the methods. For `getAccountInfo` it says "base58 is slow and limited to less than 129 bytes of Account data." while `sendTransaction` says " base58 (slow, DEPRECATED), or base64.". So I guess we'd be deprecating a bit more aggressively than the RPC itself there.

**Comment by buffalojoec** [comment]
> Though the RPC docs are a bit different between the methods. For `getAccountInfo` it says "base58 is slow and limited to less than 129 bytes of Account data." while `sendTransaction` says " base58 (slow, DEPRECATED), or base64.". So I guess we'd be deprecating a bit more aggressively than the RPC itself there.

Yeah, I like the deprecate approach, but this was exactly my concern. I don't know if it's great that we would essentially be diverging behavior from the actual RPC.

We could either:
- Directly mimic the RPC
- Add deprecation to the JS lib to avoid this annoying error that will definitely trip people up
