### ISSUE TITLE
(code included) Add getExplorerTransactionLink() and getExplorerAddressLink()

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#1592]
## Motivation

This is the most boring code - literally string formatting - but chatting to both DevRel and Solana developers, a bunch of us are rewriting the same boilerplate code and having it out of the box would save us time during demos, debugging, etc.

Why add to web3.js? 

 - @steveluscher and I previously discussed what should be added to web3.js vs an external package, and decided that things that were node-specific - eg that use `fs`, `child_process` etc - belong in a separate package, so DevRel made https://github.com/solana-developers/node-helpers 
 - Getting an explorer link is relevant to both the browser and node, and doesn't depend on node APIs, so this belongs in web3.js.
 - There are 0 dependencies.

Possible arguments against:

 - There are other explorers (eg, helius, solana beach) and some have features official explorer we doesn't have - compressed NFTs, ANS domain names, etc - but a lot of those are being added to the official explorer.

## Example use case

A user wishes to inspect a given transaction signature on Solana Explorer

```typescript
const explorerTransactionLink = getExplorerTransactionLink(
    "3vx69kQRsn6NYd5zG5fZh5s9RcHZHfPgSNR4ykR11JTspMPi5WYNBYmnqXc3zwTvRUTsfEHNBaCNQSbmfVkcwm6w",
    "devnet"
  )
```

Returns: 

```typescript
https://explorer.solana.com/tx/3vx69kQRsn6NYd5zG5fZh5s9RcHZHfPgSNR4ykR11JTspMPi5WYNBYmnqXc3zwTvRUTsfEHNBaCNQSbmfVkcwm6w?cluster=devnet
```

## Details

Implementation below, using URLSearchParams to encode the query strings as that's correct:

```typescript
const getExplorerTransactionLink = (
  signature: string,
  cluster?: web3.Cluster
) => {
  const baseURL = `https://explorer.solana.com/tx/${signature}`;
  if (!cluster) {
    return baseURL;
  }
  const params = new URLSearchParams({ cluster });

  return `https://explorer.solana.com/tx/${signature}?${params}`;
};

const getExplorerAddressLink = (address: string, cluster?: web3.Cluster) => {
  const baseURL = `https://explorer.solana.com/address/${address}`;
  if (!cluster) {
    return baseURL;
  }
  const params = new URLSearchParams({ cluster });

  return `https://explorer.solana.com/address/${address}?${params}`;
};
```

**Comment by steveluscher** [comment]
`@solana-developers/helpers` is getting updated for `@solana/web3.js` 2.0. We'll leave it to them! https://github.com/solana-developers/helpers/blob/main/src/lib/explorer.ts
