### ISSUE TITLE
solana web3js module not found: can t resolve encoding in terminal

### ISSUE THREAD

**Issue by cSarcasme** [solana-labs/solana-web3.js#1637]
![Capture d’écran 2023-09-28 122059](https://github.com/solana-labs/solana-web3.js/assets/39191127/8983143d-3607-4ebb-aa26-1d89a6c7a836)

## Overview

Error in my next terminal.

## Steps to reproduce

For see the error just install solana web3js and node-fetch on your next application

## Description of bug

 ⚠ ./node_modules/@solana/web3.js/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in 'C:\Users\haatman\Documents\lottery2\dbq2lottery\node_modules\@solana\web3.js\node_modules\node-fetch\lib'

 ⚠ ./node_modules/@solana/web3.js/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in 'C:\Users\haatman\Documents\lottery2\dbq2lottery\node_modules\@solana\web3.js\node_modules\node-fetch\lib'

Import trace for requested module:
./node_modules/@solana/web3.js/node_modules/node-fetch/lib/index.js
./node_modules/@solana/web3.js/lib/index.cjs.js

I ty by advance for anyhelp i have really dont find any solution for that ty

**Comment by buffalojoec** [comment]
Hello, which version of `@solana/web3.js` are you using? Also which Node version?

**Comment by steveluscher** [comment]
This doesn’t affect the operation of the app or the build, right?
