### ISSUE TITLE
Suggestion: add Base58EncodedAddress constants to avoid unnecessary boilerplate

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#1689]
Right now people have to run something like:

```
const SYSTEM_PROGRAM =
  "11111111111111111111111111111111" as Base58EncodedAddress;

const MEMO_PROGRAM =
  "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr" as Base58EncodedAddress;

```

As a user that wants to send you 4 sol with a note saying 'Thanks!', I'd expect to be able to import `SYSTEM_PROGRAM`, `MEMO_PROGRAM`, `COMPUTE_BUDGET_PROGRAM` and similar from web3.js with the typing done for me.

## Motivation

Easier to do this once in web3.js rather than have every example contain the same boilerplate

## Example use case

```
import { SYSTEM_PROGRAM, MEMO_PROGRAM } from "@solana/web3.js";
```

**Comment by steveluscher** [comment]
@buffalojoec made this a lot better in #1619.

**Comment by steveluscher** [comment]
And also, @lorisleiva's codegen is going to produce generated constants that you can import with reckless abandon, for every program imaginable.
