### ISSUE TITLE
It should be easy to connect to an RPC 

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#1691]
## Motivation

If a user wishes to connect to an RPC, they should need to specify:
 - That they wish to connect
 - The cluster name or URL

Right now the current required code is a little verbose:

```
const rpc = createSolanaRpc({
  transport: createDefaultRpcTransport({
    url: "...",
  }),
});
```

I'm not sure `rpc` and `createSolanaRpc` are good names, since an RPC is the thing we're connecting to, rather than our RPC client. I'm concerned about confusion between the `rpc` object we are creating and the actual RPC run by the RPC maintainer. This distinction seems obvious to us as Solana users but would not be obvious to new Solana users.

### To connect to devnet 

Devnet is a safe default as devnet tokens have no value

```
const connection = connect();
```

### To connect to mainnet using Foundations's default RPCs:

```
const connection = connect('mainnet');
```

Would result in a connection to `https://api.mainnet-beta.solana.com/`

To connect to an RPC at an arbitrary URL:

```
const connection = connect('https://rpc.helius.xyz/?api-key=abcdef');
```

To connect to an RPC at an arbitrary URL with some non-default options:

```
const connection = connect('https://rpc.helius.xyz/?api-key=abcdef', {
  commitment: "finalized",
  disableRetryOnRateLimit: true
});
```

If we wanted to, we could make this neater by encoding URL params 

```
const connection = connect('https://rpc.helius.xyz/', {
  commitment: "finalized",
  disableRetryOnRateLimit: true,
  urlParams: {
    api-key: 'abcdef'
  }
});
```

We can then do any necessary encoding with`new URLSearchParams(urlParams)` and add that to the URL. Having `urlParams` makes connections to URLs with a lot of URL parameters a little easier to read, as the params are split over multiple lines rather than one massive string.

## Details

If the connection is not to one of the preset values (`testnet`, `devnet`, `mainnet`), it is tested to be an HTTPS URL. If not a valid HTTPS URL, `connect()` would throw an error.

I have used `mainnet` rather than `mainnet-beta` in these examples because my understanding is that `beta` is going away.

**Comment by buffalojoec** [comment]
What about moving toward "RPC Client" nomenclature, and then allowing the `createSolanaRpcClient` function to take _just_ a string URL _or_ the configs:

```typescript
const client = createSolanaRpcClient('https://api.devnet.solana.com')

const customClient = createSolanaRpcClient({
  transport: createDefaultRpcTransport({
    url: "https://my.custom.url",
  }),
});
```

I'm not 100% sure how I feel about defaulting to devnet, but I definitely see where you're coming from.

**Comment by mikemaccana** [comment]
- Yep `client` nomenclature seems nicer to me too. Specifically I think `client` is better than `connection` too since a connection often can be disconnected for example (eg like a DB connection), whereas I think what `createRpcClient()` returns is actually more stateless, from my understanding.
 
 - Just a string URL / RPC name or a full config sounds reasonable. 

 - Maybe just `createRpcClient` - no need for `Solana`, that's implied by the library name.  Insert Justin Timberlake 'it's cleaner' meme.

**Comment by mcintyre94** [comment]
I think there's definitely space for reducing the verbosity here for simple use cases, but the separation between `transport` and `rpc` does enable some really powerful new use cases that we haven't supported previously because of an overly locked down API

@steveluscher can talk more to this, but an example is this round-robin transport: https://x.com/steveluscher/status/1650794822687653888?s=20 

You can only do things like that if you allow people to initialise the transport independently, and then create an rpc from it. So we should make sure that whatever we do allows this flexibility to people that need it and doesn't end up limiting devs like we currently do.

**Comment by buffalojoec** [comment]
> whereas I think what createRpcClient() returns is actually more stateless, from my understanding.

Correct, it's just a payload builder that will return a pending request with said payload. No connection is made until you hit `.send()`, which will send the payload over HTTP.

> * Maybe just `createRpcClient` - no need for `Solana`, that's implied by the library name.  Insert Justin Timberlake 'it's cleaner' meme.

There are two! There's `createJsonRpc` and `createSolanaRpc`. The "Solana" one is simply driving `createJsonRpc` and adding all API methods from the Solana JSON RPC. If you instead use `createJsonRpc` you can specify whatever methods you want and don't need to use all of them.

**Comment by mikemaccana** [comment]
Thanks @mcintyre94 that helps add a lot of context around the RPC transport / client separation.

> You can only do things like that if you allow people to initialise the transport independently, and then create an rpc from it.

100% - I think @buffalojoec covered this with his example below. The idea should be we allow people to specify a cluster name, URL if they just need a default transport made for them, otherwise they can specify a transport:

```
const client = createSolanaRpcClient()
```

```
const client = createSolanaRpcClient('devnet')
```

```
const client = createSolanaRpcClient('https://api.devnet.solana.com')
```

Then with a full config per @buffalojoec's example, using Stephen's round robin technique:

```

const transports = [
  createRpcTransport({ url: "..." }),
  createRpcTransport({ url: "..." }),
  // ..
];

let nextTransport = 0;

async function roundRobinTransports(...args) {
  nextTransport = (nextTransport + 1) % transports.length;
  return await transport(...args);
}

const customClient = createSolanaRpcClient({
  transport: roundRobinTransports,
});
```

**Comment by haidarabdillah** [comment]
any update on this recomendation sir?
