### ISSUE TITLE
`rpc.sendTransaction().send()` doesn't make logical sense.

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#1692]
_I'm not sure if this is bug or a feature request. Essentially it feels like a DX bug._

## Overview

From [Stephen's refactor of Andy's code](https://github.com/loopcreativeandy/video-tutorial-resources/blob/9d22569106e45e663673ff5c21cf510385ea3a8b/web3v2/experimental.ts):

```
const signature = await rpc
  .sendTransaction(encodedTX, { encoding: "base64" })
  .send();
```

According to the function name `sendTransaction()`, the transaction has already been sent. It shouldn't be necessary or even possible to `send()` a transaction that was previously sent. On the surface, reading the function names, this looks like an attempt to double spend.

## Possible Solutions

On the surface - if `sendTransaction()` doesn't actually send the transaction - an immediate fix would be to rename the function to createTransaction:

```
const signature = await rpc
  .createTransaction(encodedTX, { encoding: "base64" })
  .send();
```

However the code for `sendTransaction()` says:

```
Submits a signed transaction to the cluster for processing.
``` 

and

```
The returned signature is the first signature in the transaction
```

Which seems to imply that the subsequent `send()` in Stephen's code isn't necessary.

**Comment by buffalojoec** [comment]
Technically `sendTransaction()` builds a request to send a transaction, and `.send()` actually sends that request.

Just like `getBalance` or `getTransaction` will build a request for a balance/transaction, and `.send()` will actually send those requests.

It might seem like a double spend looking at the names, but the idea is to treat the `rpc` variable as an API of all of the RPC methods available from the JSON RPC, and using each method in the API one can build a request for a specific method, and that request can be sent with the chained `.send()` function.

`sendTransaction` looks weird, but others make sense like `rpcClient.getBlock(..).send()`. The alternatives start to get a little weird on DX:

```typescript
const request = createSendTransactionRequest(tx);
const signature = await rpcClient.send(request);

// or

const request = rpcClient.requests.sendTransaction(tx);
const signature = await rpcClient.send(request);

// or

const request = rpcClient.createRequest({
   method: 'sendTransaction',
   parameters: {
      transaction, // Probably very difficult to have type help here
   }
});
const signature = await rpcClient.send(request);
```

**Comment by mcintyre94** [comment]
Yep there's definitely a naming clash here, but it's tricky to see a better option for either of the parts 

`sendTransaction` comes directly from the RPC method being used, and that's consistent for all methods. If you know the JSON RPC method, you know how to call it using the new web3js. So we wouldn't want to change that, and it's also essential that the names match for the proxy to work correctly. 

Likewise, for all of them you have that awaitable `send()` that actually sends the request when you're ready to. I don't think we'd want to lose that separation between constructing and sending a request, and I'm not sure if we can either way because of the abort signal that can be passed to `send`. And I'm not sure there's a better name than `send()` that doesn't clash with any of the RPC method names.

**Comment by mikemaccana** [comment]
Thanks. I suspected as much re: `sendTransaction ()` making a request and not sending it. 

Avoiding the use of the verb 'send', ie renaming `sendTransaction()` to `createTransactionRequest()` 

```
const request = createTransactionRequest(tx);
const signature = await rpcClient.send(request);
```

Seems clearer to me. WDYT?

**Comment by mcintyre94** [comment]
I think in isolation you're right that that looks better. I just think it would be confusing for every other RPC method to exactly match a Solana JSON RPC method and this one not to. I think that would be more confusing for developers once they learn this API a little bit, than seeing the same `.send()` that they see on every other call. I think the consistency is on balance more important than this reading a bit weirdly.

**Comment by mikemaccana** [comment]
Sorry @mcintyre94 I wrote my comment at the time as you were writing yours - I don't want you to think I ignored you!

I've since read your point about 

> sendTransaction comes directly from the RPC method being used, and that's consistent for all methods. 

Understood the needs to match the RPC name.

> And I'm not sure there's a better name than send() that doesn't clash with any of the RPC method names.

`.run()` or `.exec()`?

In context. 

```
const signature = await rpc
  .sendTransaction(encodedTX, { encoding: "base64" })
  .run();
```

or

```
const signature = await rpc
  .sendTransaction(encodedTX, { encoding: "base64" })
  .exec();
```

Maybe `exec()` feels a little nicer, since trades are executed more than they are ran. Eg "The broker executed the trade at the best available price.”

**Comment by mcintyre94** [comment]
Gotcha! `exec` does make sense in the context of transactions, but I'm not sure about some of the other RPC methods. The vast majority are `getXYZ` with very few actually changing state. Both `run` and `exec` feel a bit too active to me for most of the calls, but that's maybe a bit nitpicky! Technically we could have multiple aliases for this function FWIW, but I think that'd just make things more confusing. 

```ts
const block = await rpc.getBlock(430).run()
const block = await rpc.getBlock(430).exec()
```

**Comment by mikemaccana** [comment]
Excellent. 😃 Yep I do understand `exec` feeling a bit active when you're just `rpc.getSomething()`, but think of having a computer program retrieve a value (without changing anything) - the program is still 'executed'. If we think of blockchains as either slow databases (where transactions are executed) or distributed computing (where programs are run), `exec()` makes more sense than `send()` does. 

I feel the same as you re: aliases, would definitely want to have one, hopefully obvious way of running a transaction.

**Comment by buffalojoec** [comment]
Personally I think if we fixate on `sendTransaction` it _sounds_ a bit strange, but for every over method it makes sense, so I'm inclined to leave it as `send()`. `send()` makes more sense to me than any other alternative keyword for sending a payload across an HTTP transport.

Taking some inspiration from [Postman](https://blog.postman.com/wp-content/uploads/2020/07/Postman-for-the-web.png), I think it is a valid way to describe what the API is doing.

**Comment by mikemaccana** [comment]
Yep, it's not as much of a problem for other RPC methods, but `sendTransaction()` is one of the more popular methods though. I see what you're saying re: sending a request to an HTTP endpoint from a JSON-RPC point of view, but from a Solana point of view, we're executing transactions.

**Comment by mcintyre94** [comment]
I don't have a strong view on send vs exec TBH, I think both would be fine. One point I'd make though is that because `sendTransaction` is popular and its inputs are complex, it might be one of the methods that is interacted with mostly through higher level helpers. That might mean that devs mostly don't see `sendTransaction(...).send()` in practice. Definitely a bit speculative/hypothetical though!

**Comment by mikemaccana** [comment]
While people may use higher level wrappers, even people wanting to interact with RPC methods directly should see a logical API - with 'send' have a consistent definition between:

 - create an objects that asks the RPC to do process a transaction with a given configuration
 - actually get the blockchain to run that transaction
 
I hope this issue doesn't nitpicky - my main concern is to:
- avoid user confusion. "You always need to `exec()`" is better than "`You always need to `send()`, and `sendTransaction()`  doesn't `send()`.
- make the API stable by avoiding changes after such a major refactor.

**Comment by steveluscher** [comment]
I actually don't mind the idea of changing this.

* `rpc` is an `Rpc<...>`
* `rpc.someMethod()` is an `RpcPendingRequest<...>`

So at the point that you have an `RpcPendingRequest<...>`, what's the verb that makes it not pend. Put another way, what do you _do_ to a ‘request?’

* send it?
* execute it?
* make it?
* dispatch it?
* do it?

| send | exec | make | dispatch | do |
|---|---|---|---|---|
| `rpc.getAccountInfo().send({abortSignal});` | `rpc.getAccountInfo().exec({abortSignal});` | `rpc.getAccountInfo().make({abortSignal});` | `rpc.getAccountInfo().dispatch({abortSignal});` | `rpc.getAccountInfo().do({abortSignal});` |
| `rpc.isBlockhashValid().send({abortSignal});` | `rpc.isBlockhashValid().exec({abortSignal});` | `rpc.isBlockhashValid().make({abortSignal});` | `rpc.isBlockhashValid().dispatch({abortSignal});` | `rpc.isBlockhashValid().do({abortSignal});` |
| `rpc.minimumLedgerSlot().send({abortSignal});` | `rpc.minimumLedgerSlot().exec({abortSignal});` | `rpc.minimumLedgerSlot().make({abortSignal});` | `rpc.minimumLedgerSlot().dispatch({abortSignal});` | `rpc.minimumLedgerSlot().do({abortSignal});` |
| `rpc.requestAirdrop().send({abortSignal});` | `rpc.requestAirdrop().exec({abortSignal});` | `rpc.requestAirdrop().make({abortSignal});` | `rpc.requestAirdrop().dispatch({abortSignal});` | `rpc.requestAirdrop().do({abortSignal});` |
| `rpc.sendTransaction().send({abortSignal});` | `rpc.sendTransaction().exec({abortSignal});` | `rpc.sendTransaction().make({abortSignal});` | `rpc.sendTransaction().dispatch({abortSignal});` | `rpc.sendTransaction().do({abortSignal});` |
| `rpc.simulateTransaction().send({abortSignal});` | `rpc.simulateTransaction().exec({abortSignal});` | `rpc.simulateTransaction().make({abortSignal});` | `rpc.simulateTransaction().dispatch({abortSignal});` | `rpc.simulateTransaction().do({abortSignal});` |

**Comment by lorisleiva** [comment]
I think `.send()` reads better and makes the most sense for 99% of the RPC methods. It's only awkward for `sendTransaction` due to the double "send" which is confusing. However, that's a pattern we're already identifying with the RPC method that requests an airdrop. Following the same naming convention here would make the API more predictable.

```ts
// Reading from the cluster.
rpc.getAccountInfo().send();
rpc.isBlockhashValid().send();

// Writing to the cluster.
rpc.requestAirdrop().send();
rpc.requestTransaction().send(); // "requestSendTransaction" if it's not clear enough.
```

What do you think?

**Comment by steveluscher** [comment]
I would sort of prefer not to special case method names now, since the RPC is a pass-through that doesn't make _any_ modifications right now.

Also, this might end up being sort of a moot point with the advent of #1753.

**Comment by steveluscher** [comment]
So yeah, tl;dr developers will typically not even call this method directly (#1753).
