### ISSUE TITLE
createTransaction() should default to a version (probably 0)

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#1695]
## Motivation

Specifying the transaction version explicitly every time `createTransaction()` is called seems unnecessary. 

Since address lookup tables reduces the size of transactions and allows for more accounts to be used in a single transaction, it seems reasonable to default to version 0. 

### before

```
createTransaction({ version: 0 }),
```

After:

```
createTransaction(),
```

or if a user wishes to specify a non-default value, or just be explicit:

```
createTransaction({version: 'legacy'}),
```

**Comment by buffalojoec** [comment]
The only thing that comes to mind for me is the way the RPC works for `maxSupportedTransactionVersion`.

If you check out my comment in the `getBlock` method, I tried to elaborate a bit more on what the docs say.

https://github.com/solana-labs/solana-web3.js/blob/8a4cd990cd67bfee4b363280be0ed2d535ab98ad/packages/rpc-core/src/rpc-methods/getBlock.ts#L52-L59

This would kind of hint at maybe defaulting to `legacy` instead?

**Comment by mcintyre94** [comment]
I think for that, unless you know everything in a block you should just be passing `maxSupportedTransactionVersion: 0`. Even if you use `legacy` for your own transactions for legibility, you can't control what else is in the block so you can still hit that error if you don't specify `maxSupportedTransactionVersion`.

**Comment by buffalojoec** [comment]
Yeah, it might not even be relevant for this discussion anyway. I'm good with 0 as a default

**Comment by steveluscher** [comment]
I don't think we should do this.

What happens when we release version 1?

Do we move the default to 1?

Is that a patch release of `@solana/web3.js`, or do we have to make it a breaking release?

😬

**Comment by buffalojoec** [comment]
> I don't think we should do this.
> 
> What happens when we release version 1?
> 
> Do we move the default to 1?
> 
> Is that a patch release of `@solana/web3.js`, or do we have to make it a breaking release?
> 
> 😬

Technically we could stay on 0 as the default, and consider `legacy` as "next to deprecated".

**Comment by lorisleiva** [comment]
IMO, it depends how often we're adding new transaction versions. Based on historical data, I'd say it's infrequent enough to make it default to v0. When we add a new version, we simply release a breaking change bump and mention in the upgrade guide that the `createTransaction` function now uses version x by default.

**Comment by steveluscher** [comment]
Forgive me for being heavy handed here but I think making people be explicit is best. Someone can always release the `left-pad` of transaction creators that defaults to `version: 0` and open source it. :)
