### ISSUE TITLE
VoteProgram.createAccount doesn't work properly on v1.16 validator

### ISSUE THREAD

**Issue by buffalu** [solana-labs/solana-web3.js#1711]
## Overview
There's a new, yet unactivated (as of Oct 9, 2023) feature called timely vote credits which changes the layout of VoteAccounts. This feature is activated automatically on test validators/development clusters, but not on testnet or mainnet.

When trying to create a new vote account through the library, the validator will reject it.

## Steps to reproduce
Note: I am not a JS/TS developer, but was running into this during some testing:
```ts
  const validatorIdentityKeypair = await generateAccount(10000000000000);
  const validatorVoteAccount = anchor.web3.Keypair.generate();

  // Create validator's vote account.
  const voteInit = new VoteInit(
    validatorIdentityKeypair.publicKey,
    validatorIdentityKeypair.publicKey,
    validatorIdentityKeypair.publicKey,
    0
  );
  const lamports = await provider.connection.getMinimumBalanceForRentExemption(
    VoteProgram.space // 3731, should be 3762
  );
  const tx = VoteProgram.createAccount({
    fromPubkey: validatorIdentityKeypair.publicKey,
    votePubkey: validatorVoteAccount.publicKey,
    voteInit,
    lamports: lamports,
  });

 await sendAndConfirmTransaction(provider.connection, tx, [
      validatorIdentityKeypair,
      validatorVoteAccount,
      validatorIdentityKeypair,
    ]);
```

When running the above against a solana-test-validator, it will fail.

I tried messing around with TEST_LIVE, but it didn't work very well with `anchor test`. Ideally there's a way to parse vote accounts similar to how the validator handles it with VoteStateVersion, in addition to specifying what type of account you'd like to create.

For now, I'm overwriting the 0th index instruction in tx to properly allocate the space.

**Comment by mcintyre94** [comment]
Is this resolved by https://github.com/solana-labs/solana-web3.js/pull/1306 or is that something else?

**Comment by buffalojoec** [comment]
> Is this resolved by #1306 or is that something else?

I think that will do it. Been digging around a bit on this.

**Comment by buffalojoec** [comment]
> will be a PITA to manage this function until its settled across all clusters :(

Yup. I think we might need to introduce some way to dictate which vote state you want to use, as you mentioned in your description.

**Comment by steveluscher** [comment]
How much longer do you think until this feature activation, @AshwinSekar?

**Comment by steveluscher** [comment]
This rolls to testnet next epoch (553).
