### ISSUE TITLE
[experimental] program derived address assertion and type guard functions don't actually assert that the address is off the curve

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1764]
`assertIsProgramDerivedAddress` and `isProgramDerivedAddress` don't actually check to see if the address is off the curve. All they do is validate the _format_ of the tuple.

Someone _could_ supply a regular on-curve address there and have those guards pass.

The job is to add in the off-curve check, and to write tests.

**NOTE**: This _still_ does nothing to assert that the bump seed is the correct one given the address supplied. Thoughts?

**Comment by lorisleiva** [comment]
Sure I can make that change. Both methods will become async functions but I don't think that's an issue.

RE the bump: it's only valid in conjunction with an array of seeds so there would be no way to assert it's valid unless we require the seeds. Maybe that's the job for another helper method like `verifyProgramDerivedAddress(pda, seeds)`?

**Comment by steveluscher** [comment]
> Both methods will become async functions but I don't think that's an issue.

🪦 https://github.com/microsoft/TypeScript/issues/37681#issuecomment-1650605236
