### ISSUE TITLE
[experimental] Figure out how to write an assertion function for fully signed transactions while TypeScript does not support async assertions and typeguards

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1773]
See https://github.com/microsoft/TypeScript/issues/37681#issuecomment-1650605236.

Essentially you can write an assertion function ([playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAcgrgWwEYQE4BkIGcsBUAWAhgHa4TFQC8UxiKqUAZFAN5SoSEAmA9sQDYgoSVCS4AuKHGIBLAI5xoWEMh78oAXwDcUALAAoAwDNpAY2Ay+UQjjTAAklkw4CJAIwAGABS0Ek3-QAlJI2WHZYNIhQMhHwyGjOeESk5KwGUNFGUD5RAHzUnoFp+hkZwPioPADuNBA1AKKolaheAOS4PDzCMgDmrYFa6ZoGGgamfFjAkQhUUACcg-qhdo6JrsSeOQgDBr5QWIQWWEYy2LB0CdhJJGTEWkA))…

```ts
type NumberLessThanTen = number & { readonly brand: unique symbol }; 

function assertIsLessThan10(num: number): asserts num is NumberLessThanTen {
  if (num >= 10) {
    throw new Error('Too big');
  }
}
const num = 9;
assertIsLessThan10(num);
num satisfies NumberLessThanTen;
```

…but as soon as you [make that assertion function async](https://www.typescriptlang.org/play?#code/C4TwDgpgBAcgrgWwEYQE4BkIGcsBUAWAhgHa4TFQC8UxiKqUAZFAN5SoSEAmA9sQDYgoSVCS4AuKHGIBLAI5xoWEMh78oAXwDcAWABQ+wsuIBjKADNpJ4DL5QjWNMACSWTDgIkAjAAYAFLQIkoH0AJTi+lBQAPTRUAACwFgAtDIA5sQ8HJH2OE5YNIhQMgXwyGjueESk5Kw5MuZQAUUAfNS+oXV6UVHA+Kg8AO40EMMAoqgDqH4A5Lg8PMLpM6G63Zr6Gvp+RiCmTZ2ULV1RJnxYwIUIVFAAnGtRhIOEMpcOTq6VnsS+zQirOUCUCwhBsWHMMmwsDoFWwVRIZGIaw0oT8qyAA) it stops working.

Options:

1. We could write an `assertIsFullySignedTransaction()` function that _just_ checks to see if there _is_ a signature for each signer, without actually performing any verification
2. We could break from the existing pattern of `assertFoo`/`isFoo` and make a function that both asserts _and_ returns the transaction with the `IFullySignedTransaction` type added.

Neither of these are great, and both are really hard to take back (ie. deprecate) once we've released them.

**Comment by lorisleiva** [comment]
I'd argue we don't need this assert method to be async in the first place. Since the goal is the ensure it is "fully signed", we just need to go through the account metas that are required to sign, deduplicate the addresses and ensure the amount of unique signers required matches the amount of signatures in the transaction.

I'm assuming the async part would be to also verify each of these signatures match the expected set of signers but IMO that's a bit overkill when all we want is ensure we've not missed one signature.

**Comment by mcintyre94** [comment]
Agreed. I think it'd be okay to have the type assertion just assert there's a signature for each expected signer, and then optionally to have a function(s) that asserts/checks signature validity

Arguably those are separate operations anyway, eg you might want to check the validity of the current signatures on a partially signed transaction.

**Comment by steveluscher** [comment]
`assertIsFullyButPossiblyBadlySignedTransaction()`
