### ISSUE TITLE
CI/CD workflow doesn't work with Node 20

### ISSUE THREAD

**Issue by mcintyre94** [solana-labs/solana-web3.js#1786]
The CICD workflow started failing when the `lts/*` node version bumped from 18.x to 20.x: https://github.com/solana-labs/solana-web3.js/actions/runs/6640521649/job/18041101940

This is temporarily resolved by locking the Node version on this workflow to 18.x

This is caused by code in `version-from-git` that doesn't work on Node 20: https://github.com/compulim/version-from-git/issues/16

`version-from-git` is unmaintained, with the last commit 4 years ago and a PR fixing this issue open since 31st August

We will need to fork it, or find an updated fork, and use that instead. Then we can bump our CICD workflow to Node 20.

**Comment by steveluscher** [comment]
We no longer use `version-from-git`. Problem solved.
