### ISSUE TITLE
[graphql] BigInt variables cause runtime fatal when passed to `isFinite()`

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1986]
This query:

```graphql
query GetTransactionsInBlock($block: BigInt!) {
  block(slot: $block) {
    blockhash
    blockHeight
    blockTime
    parentSlot
    previousBlockhash
  }
}
```

Generates this error

```
{
  "errors": [
    {
      "message": "Cannot convert a BigInt value to a number",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "block"
      ]
    }
  ],
  "data": {
    "block": null
  }
}
```

[Repro link](https://graphql.solana.com/#q:0:0:I4VwpgTgngBA4mALgFQgQwHYGc0GNECWA9tgJIYBCANkbgNYAUAJAEY30BcMFBA5uYgCEAShgBvAFAwYbWoyw1EXVuzqjJ06bPoALNFh1TN2ugAkwfHYiNbVyAgFswNmAAc0EMBkQBlRS9dPADdiECxqOT0DIwBfCRigA:N4KABGBEBGA2D2BjA1pAXFATAZgOyYFYCBOY3SEAXyA).

**Comment by buffalojoec** [comment]
Is this just through the playground or the resolver itself?

**Comment by steveluscher** [comment]
I think it's the resolver.
