### ISSUE TITLE
Solana swap transactions fail because block height is exceeded... no matter how many times I retry

### ISSUE THREAD

**Issue by michaelessiet** [solana-labs/solana-web3.js#1987]
No matter how many times I retry to send the transaction that I get from the Jupiter swap API I keep getting an error telling me that the block height has been exceeded. From what I gathered online I should just retry the transaction, however, that doesn't fix it, I just get the error repeated over and over again. Is there a way I can increate transaction priority, pay higher fee to get placed in the block or something? 
The error is below
```
[TransactionExpiredBlockheightExceededError: Signature CFAGYcJesvueTRMtbJBXwBXP3GAdvpD4xfauoG4XfJCvgGLt5chCurSVqgpCSEygeJFC6d46VAgJyNwNq7Z6voT has expired: block height exceeded.]
```
Here's what the routes look like
```
[{"amount": "34892178", "inAmount": "34892178", "marketInfos": [[Object], [Object]], "otherAmountThreshold": "9706785", "outAmount": "9716501", "priceImpactPct": 0.003581409927264523, "slippageBps": 10, "swapMode": "ExactIn"}, {"amount": "34892178", "inAmount": "34892178", "marketInfos": [[Object], [Object], [Object]], "otherAmountThreshold": "9698066", "outAmount": "9707773", "priceImpactPct": 0.0043228319552641725, "slippageBps": 10, "swapMode": "ExactIn"}, {"amount": "34892178", "inAmount": "34892178", "marketInfos": [[Object], [Object], [Object]], "otherAmountThreshold": "9674055", "outAmount": "9683738", "priceImpactPct": 0.013760941264121307, "slippageBps": 10, "swapMode": "ExactIn"}]
```
I go through the process of serializing the this then signing it, then sending it using `sendRawTransaction` then I use the `confirmTransaction` function 

```ts
await solanaService().provider.confirmTransaction({
    signature: txid,
    blockhash: blockData.blockhash,
    lastValidBlockHeight: blockData.lastValidBlockHeight
})
```

**Comment by mcintyre94** [comment]
This isn't a bug in web3js. You're probably correct that you need to increase the priority of your transaction. [See Jupiter's documentation on that here.](https://station.jup.ag/docs/apis/swap-api#setting-priority-fee-for-your-transaction)

If you're still having trouble please open a question on solana.stackexchange.com, we can't provide support through Github issues.
