### ISSUE TITLE
onSignature infinite loop

### ISSUE THREAD

**Issue by crispheaney** [solana-labs/solana-web3.js#1989]
## Overview

We use onSignature to listen for tx confirmations

## Steps to reproduce

If you have a bot that is sending a lot of tx, especially when network is congested, it is more likely to happen. I think rpc needs to reject initial subscribe.

## Description of bug

Calling signatureSubscribe with `_rpcWebSocket.call` throws an [error](https://github.com/solana-labs/solana-web3.js/blob/a1fafee840589e493b215dc2c9ec5ae9ba44ca13/packages/library-legacy/src/rpc-websocket.ts#L53), it's [caught](https://github.com/solana-labs/solana-web3.js/blob/a1fafee840589e493b215dc2c9ec5ae9ba44ca13/packages/library-legacy/src/connection.ts#L6129) and then `_updateSubscription` recursively [calls](https://github.com/solana-labs/solana-web3.js/blob/a1fafee840589e493b215dc2c9ec5ae9ba44ca13/packages/library-legacy/src/connection.ts#L6145) itself again, causing an infinite loop.

Attaching screenshot of the logs we're seeing
<img width="1244" alt="Screen Shot 2023-12-26 at 9 51 01 PM" src="https://github.com/solana-labs/solana-web3.js/assets/15279102/06a89581-db93-4f25-8c66-7c1fa51732bd">

**Comment by steveluscher** [comment]
What version of web3.js?

See also:

* #1426
* #1177
* #25322
* #29130

But most importantly 

* #1106
* https://github.com/elpheria/rpc-websockets/pull/138

**Comment by steveluscher** [comment]
More importantly, though, let's get you on the new version of web3.js!

Start here: https://www.youtube.com/watch?v=JUJtAPhES5g
More reading: https://github.com/solana-labs/solana-web3.js/blob/master/packages/library/README.md

If you're down, I will give you 1:1 support to upgrade your transaction making/confirming code.
