### ISSUE TITLE
How to disable log this in node.js? Failed to load bindings, pure JS will be used (try npm run rebuild?)

### ISSUE THREAD

**Issue by damartripamungkas** [solana-labs/solana-web3.js#1998]
## Overview
its not bug but is little nuisance

## Steps to reproduce
```javascript
// just import it this package
import web3 from "@solana/web3.js"
```

## Description of bug
log that cannot be turned off in node.js not browser.
error : Failed to load bindings, pure JS will be used (try npm run rebuild?)

**Comment by buffalojoec** [comment]
Did any of these steps work for you?

https://solana.stackexchange.com/questions/4077/bigint-failed-to-load-bindings-pure-js-will-be-used-try-npm-run-rebuild-whe

**Comment by damartripamungkas** [comment]
> Did any of these steps work for you?
> 
> https://solana.stackexchange.com/questions/4077/bigint-failed-to-load-bindings-pure-js-will-be-used-try-npm-run-rebuild-whe

Before opening this issue, I went to that page and followed everyone's suggestions but it still didn't work

**Comment by steveluscher** [comment]
See https://github.com/trufflesuite/ganache/issues/1080#issuecomment-906550239.
