### ISSUE TITLE
Signature verification failed does not specify which signature

### ISSUE THREAD

**Issue by ChewingGlass** [solana-labs/solana-web3.js#2001]
## Motivation

To make things easier to debug

## Example use case

I form a transaction with two signers. I'm either (a) missing a signer or (b) signed incorrectly. I get "Signature verification failed." Which one? Why?

**Comment by buffalojoec** [comment]
Yeah, this is awful honestly. @mcintyre94 have we broached this issue with `@solana/transactions`?

**Comment by mcintyre94** [comment]
@buffalojoec I don't think we have a function to verify signatures there yet. Should probably take this issue to mean that we need to add one. 

We do have `assertTransactionIsFullySigned` though, so you can check for a specific missing signer. That currently bails on the first missing signature though which isn't great - should list all. https://github.com/solana-labs/solana-web3.js/blob/974fa305502a4a109dad48035f9906c00b44c5b1/packages/transactions/src/signatures.ts#L72-L86

If we added a verify function then it'd be a separate function and you'd be able to distinguish them.

**Comment by buffalojoec** [comment]
> If we added a verify function then it'd be a separate function and you'd be able to distinguish them.

OK I think that's a good approach. I agree we should add this. I'll leave this hanging around for now, maybe I'll self-assign when I get a chance.

**Comment by buffalojoec** [comment]
Heh, there's also this: #2002

**Comment by steveluscher** [comment]
Reopening this because we still need to do this for `assertTransactionIsFullySigned`. cc/ @cryptopapi997 if you want to be a hero.
