### ISSUE TITLE
A better way to load keypairs

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#2021]
## Motivation

Dev Education and DevRel also see a lot of copy-paste efforts to add secret keys to env files, and to load keys from the environment.

It would be good to provide some guidance here:
 - People frequently use `node` along with `esrun`, `ts-node`, `tsx` etc to run js/ts files on the command line when learning. 
 - People need a good way to persistently save and load keys they've previously generated 
 - We want to push people to use `.env` 
 - We want to push people to `.gitignore` their env files.  

## Example use case

The DevRel [`helpers`](https://github.com/solana-developers/helpers?tab=readme-ov-file#nodejs-specific-helpers) package has these. You can steal the code.

To load the default keypair ~/.config/solana/id.json, just run:
```
const keyPair = await getKeypairFromFile();
```
or to load a specific file:

```
const keyPair = await getKeypairFromFile("somefile.json");
```
or using home dir expansion:

```
const keyPair = await getKeypairFromFile("~/code/solana/demos/steve.json");
```

For the environment:

```
const keyPair = await getKeypairFromEnvironment("SECRET_KEY");
```

Saves a keypair to the environment file.

```
await addKeypairToEnvFile(testKeypair, "SECRET_KEY");
```
or to specify a file name:

```
await addKeypairToEnvFile(testKeypair, "SECRET_KEY", ".env.local");
```

## Details

[Code](https://github.com/solana-developers/helpers/blob/main/src/index.ts#L31C6-L31C6)

Interesting, the exciting world of ES6 seems to means that node specific functions (eg, that call `node:fs/promises` or similar) seem to not prevent a module being used in the browser.

**Comment by steveluscher** [comment]
We have four examples [here](https://github.com/solana-labs/solana-web3.js/blob/master/examples/signers/src/example.ts#L114-L195), now. I think that's about as far as we want to go in the core library.

See also https://github.com/solana-labs/solana-web3.js/issues/1607#issuecomment-2427782960
