### ISSUE TITLE
Make new Connection("clusterName")work 

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#2030]
## Motivation

Even Foundation and Labs people people call `clusterApiURL()` or have [little helpers to match cluster names to connections](https://github.com/solana-labs/wallet-standard/blob/master/packages/core/util/src/endpoint.ts). It would useful to allow Connection to just use a cluster name, if someone wants to connect to one of the official cluster URLs.

## Example use case

Someone wants to connect to devnet.

They run:

```
const connection - new Connection("devnet");
```

And don't have to worry about matching the name to a network URL.

## Details

Just check for a few magic values for the official clusters, anything outside those should be assumed to be a URL.

**Comment by steveluscher** [comment]
This runs up against the principle of greatest package efficiency. If you _use_ the feature that exercises the `clusterApiUrl` logic, then you use some or all of that code. If you don't (ie. you supply your own RPC URL) then you use 0% of it, and waste those 628 gzipped bytes.

It's never a big deal in isolation, but if we allow this sort of pre-bundled-but-optional functionality everywhere (see #2115) then package efficiency goes way down.
