### ISSUE TITLE
node-gyp failed to rebuild bigint-buffer

### ISSUE THREAD

**Issue by Taha-daboussi** [solana-labs/solana-web3.js#2081]
I have an electron application that uses electron-react-boilerplate, 
and when I run the npm install command after install @solana/web3.js in the ./release/app

I am getting an error of node-gyp failed to rebuild bigint-buffer.

tried downloading a different version of node, and downloading the latest of node-gyp as well as electron-builder
but none seems to fix the issue , tried deleting package-lock.json and  node modules and reinstall them but with no luck 
as well as using npm rebuild

the error message that am getting : 

`Error: node-gyp failed to rebuild 'C:\Users\Taha_\OneDrive\Desktop\nftsminter\nftsminter-ui\release\app\node_modules\bigint-buffer`

@solana/web3.js version : "^1.89.1"
node version : v21.6.1
node-gyp version : "^10.0.1"
electron-builder version : "^24.9.1"

**Comment by dtmrc** [comment]
@Taha-daboussi i have fixed this in the past by installing `npm i bigint-buffer --save && npm rebuild`. 
there was a case where i had to download, reconfigure & rebuild [`node-gyp`](https://github.com/nodejs/node-gyp). looks like you're on windows, so there are probably going to be some dependencies for `node-gyp` (whatever is equivalent of `gcc`, `build-essentials`, `python3`)
