### ISSUE TITLE
How to send multi signed versioned transaction in one signature?

### ISSUE THREAD

**Issue by lovelyrrg51** [solana-labs/solana-web3.js#2114]
## Overview

Got failed when try to send multi signed versioned transaction(v0) in one signature

## Steps to reproduce
Gm guys. Recently, I've tried to call multi signed versioned transaction(v0) in one signature but got failed. got this issue.
```
...cannot sign with non signer key on solana...
```
How could I handle it? Hope to got answer from you guys asap. Thanks.

**Comment by buffalojoec** [comment]
Hello, please elaborate on the issue some more and explain why you think this may be a bug with `@solana/web3.js`. I am not able to infer what you mean by "send multi signed versioned transaction in one signature".

If this is not a bug, please defer to the Solana Stack Exchange, and provide more details there as well.
