### ISSUE TITLE
Feature: allow more types to be specified in findProgramAddressSync() or equivalent

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#2115]
## Motivation

Right now, with `findProgramAddressSync()` we have to remember the different methods to convert the seed inputs to bytes. This makes frontend code unnecessarily noisy.

Instead, the PDA getter (whatever it is called in web3.js 2 \*) should just allow strings, publickeys, BigInts, etc and do the conversion to bytes as necessary. 

### Before

```typescript
const pdaAndBump = findProgramAddressSync(
  [Buffer.from("somestring"), userKeypair.publicKey.toBuffer(), id.toBuffer("le", 8)],
  programKeypair.publicKey
);
```
### After 
```typescript
const pdaAndBump = getPDAAndBump(
  ["somestring", userKeypair.publicKey, id],
  programKeypair.publicKey
);
```

\* I called this `getPDAAndBump()` because it returns a PDA and a bump. Main thing is I didn't want to switch between 'ProgramAddress' and 'ProgramDerivedAddress' which means the same thing. 

Drawbacks: this means we need to be opinionated about BigInt, ie decide to always use LE encoding if a BigInt is supplied. That seems reasonable though.

### Implementation

```typescript
// A generic function to take strings, publickeys, and BNs
// does whatever work is necessary to turn them into PDAs
export const getPDAAndBump = (
  // @ts-ignore this type exists
  inputs: Array<string | PublicKey | BN>,
  programId: PublicKey
) => {
  const buffers = inputs.map((input) => {
    if (typeof input === "string") {
      return Buffer.from(input);
    }
    // TODO: not sure why instanceof occasionally doesn't work
    // fix it and get rid of the constructor hack
    if (input instanceof PublicKey || input.constructor.name === "PublicKey") {
      return input.toBuffer();
    }
    // @ts-ignore this type exists
    if (input instanceof BN) {
      return input.toBuffer("le", 8);
    }
    throw new Error("getPDAAndBump: unsupported type");
  });
  const programAddressAndBump = PublicKey.findProgramAddressSync(
    buffers,
    programId
  );
  return programAddressAndBump;
};

```

### Test

Using native node test runner, eg:

```typescript
import { before, describe, test } from "node:test";
import assert from "node:assert/strict";
```
```
describe("getPDA", async () => {
  test("getPDAAndBump works", async () => {
    const id: typeof BN = new BN(randomBytes(8));
    const [userKeypair, programKeypair] = makeKeypairs(2);

    const pdaAndBump = PublicKey.findProgramAddressSync(
      [
        Buffer.from("somestring"),
        userKeypair.publicKey.toBuffer(),
        id.toBuffer("le", 8),
      ],
      programKeypair.publicKey
    );

    const pdaAndBump2 = getPDAAndBump(
      ["somestring", userKeypair.publicKey, id],
      programKeypair.publicKey
    );

    assert.deepEqual(pdaAndBump, pdaAndBump2);
  });
});
```

**Comment by steveluscher** [comment]
> Instead, the PDA getter (whatever it is called in web3.js 2 *) should just allow strings, publickeys, BigInts, etc and do the conversion to bytes as necessary.

`createProgramDerivedAddress()` already converts strings to `Uint8Arrays` and accepts `Uint8Arrays` as-is.

https://github.com/solana-labs/solana-web3.js/blob/b2c1b82d0da512ad485e9b81c2d9db12e3ce3588/packages/addresses/src/program-derived-address.ts#L90-L91

> …this means we need to be opinionated about BigInt, ie decide to always use LE encoding if a BigInt is supplied.

We can't do this.

1. We would have to hard-require code to convert a `BigInt` to a byte array. This would penalize the vast majority of people that don't use `BigInts` as seeds.
2. Three seconds after we released this, someone would come along and ask for a config flag to change from LE to BE byte order. Now in addition to hard-requiring code that most people don't need, we'd have config that few understand.

If folks need BigInt encoding, they can import `@solana/codecs-numbers` and use something like `getU64Encoder().encode(int, {endian: Endian.BIG})` to their hearts' content.

**Comment by steveluscher** [comment]
Maybe, _maybe_, we could change the `Seed` type from this:

```ts
type Seed = string | Uint8Array;
```

…to this

```ts
type Seed = string | Uint8Array | {toBytes: () => Uint8Array};
```

And then #yolo call the `toBytes()` method of anything you pass in, but this makes me feel uncomfortable because now seeds aren't serializable, and may produce side effects when read.

Yeah, let's not do that either.
