### ISSUE TITLE
Update the TP2 changelog with all changes since TP1

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#2117]
Draft here: https://github.com/solana-labs/solana-web3.js/releases/tag/untagged-a52bc4f981a71051575b

**Comment by buffalojoec** [comment]
I believe I've added anything relevant I've committed in TP2.

**Comment by buffalojoec** [comment]
Just FYI whenever you modify the draft it seems to change the URL (😡).
