### ISSUE TITLE
[experimental] Convert all thrown errors to `SolanaError`

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#2118]
1. Search everywhere except for `packages/library-legacy` for `throw new Error`
2. Convert the error to a coded `SolanaError`
    a. Create a code for it in `packages/errors/src/codes.ts`
    b. Optionally allow the caller to add typed context to the error by defining the type in `packages/errors/src/context.ts`
    c. Create a message for it in `packages/errors/src/messages.ts`
    d. Replace the callsite with `throw new SolanaError(SOLANA_ERROR__MY_NEW_ERROR, {/* optional context */})`
3. Make sure that the generated Kinobi clients throw `ProgramErrors` from on-chain programs in the same way (include the logs, message, program address, error code, etc in the error's context)

**Comment by buffalojoec** [comment]
I want you guys to know I cried when I self-assigned this.

**Comment by lorisleiva** [comment]
Thank you @buffalojoec 🫡

I can tackle the errors inside the `@solana/programs` package since the error resolution will have to change anyway such that we don't need to provide the array of programs as we do now.

**Comment by lorisleiva** [comment]
@buffalojoec Actually you might also want to avoid tackling all RPC errors right now as I'm working on a massive refactoring stack.

**Comment by buffalojoec** [comment]
> @buffalojoec Actually you might also want to avoid tackling all RPC errors right now as I'm working on a massive refactoring stack.

You got it, just throw a flag here whenever I'm good to go.

**Comment by steveluscher** [comment]
We can split this up if you want! Want to work from A-Z and I'll work from Z-A @buffalojoec?

**Comment by buffalojoec** [comment]
> We can split this up if you want! Want to work from A-Z and I'll work from Z-A @buffalojoec?

Sure! Are you just basing off of Loris's stack?
