### ISSUE TITLE
[experimental] Add monolithic rpc/transport creators

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#2119]
The wish is this:

* `solanaRpcFactory(clusterUrl)`
* `solanaRpcSubscriptionsFactory(clusterUrl)`

These essentially do double duty:

* Create an appropriate default transport
* Return a compatible RPC client

**Comment by lorisleiva** [comment]
Unless I'm misunderstanding the signature of these functions, I don't think we should suffix them with `Factory` here because, unlike the `airdropFactory` for instance, it doesn't return a function but the RPC proxy directly.

I think using `solanaRpc()` and `solanaRpcSubscriptions()` is sufficient.

**Comment by steveluscher** [comment]
Hey @buffalojoec, is there a reason that `RpcFromTransport` is:

```ts
export type RpcFromTransport<TRpcMethods, TRpcTransport extends RpcTransport> = TRpcTransport extends RpcTransportDevnet
    ? RpcDevnet<TRpcMethods>
    : TRpcTransport extends RpcTransportTestnet
      ? RpcTestnet<TRpcMethods>
      : TRpcTransport extends RpcTransportMainnet
        ? RpcMainnet<TRpcMethods>
        : Rpc<TRpcMethods>;
```

…instead of

```ts
export type RpcFromTransport<TRpcTransport extends RpcTransport> = TRpcTransport extends RpcTransportDevnet
    ? RpcDevnet<SolanaRpcApiFromTransport<TRpcTransport>>
    : TRpcTransport extends RpcTransportTestnet
      ? RpcTestnet<SolanaRpcApiFromTransport<TRpcTransport>>
      : TRpcTransport extends RpcTransportMainnet
        ? RpcMainnet<SolanaRpcApiFromTransport<TRpcTransport>>
        : Rpc<SolanaRpcApiFromTransport<TRpcTransport>>;
```

(and same for the subscriptions version)

**Comment by buffalojoec** [comment]
> Hey @buffalojoec, is there a reason that `RpcFromTransport` is:
> 
> ```ts
> export type RpcFromTransport<TRpcMethods, TRpcTransport extends RpcTransport> = TRpcTransport extends RpcTransportDevnet
>     ? RpcDevnet<TRpcMethods>
>     : TRpcTransport extends RpcTransportTestnet
>       ? RpcTestnet<TRpcMethods>
>       : TRpcTransport extends RpcTransportMainnet
>         ? RpcMainnet<TRpcMethods>
>         : Rpc<TRpcMethods>;
> ```
> 
> …instead of
> 
> ```ts
> export type RpcFromTransport<TRpcTransport extends RpcTransport> = TRpcTransport extends RpcTransportDevnet
>     ? RpcDevnet<SolanaRpcApiFromTransport<TRpcTransport>>
>     : TRpcTransport extends RpcTransportTestnet
>       ? RpcTestnet<SolanaRpcApiFromTransport<TRpcTransport>>
>       : TRpcTransport extends RpcTransportMainnet
>         ? RpcMainnet<SolanaRpcApiFromTransport<TRpcTransport>>
>         : Rpc<SolanaRpcApiFromTransport<TRpcTransport>>;
> ```
> 
> (and same for the subscriptions version)
> 
> EDIT: I guess it's to support custom mixins?

This is in `@solana/rpc-transport` which isn't supposed to be Solana-specific. Plus those Solana API methods are in `@solana/rpc-core`, so that would be a circular dependency.
