### ISSUE TITLE
[experimental] getSignaturesForAddress(...).send() does not return Object in RpcResponse format

### ISSUE THREAD

**Issue by Akim-Personal** [solana-labs/solana-web3.js#2143]
## Overview and Description of bug

This applies to **2.0.0-experimental.56103b0**

In Typescript, the response of **getSignaturesForAddress(...).send()** is expected to have the form of **RpcResponse** like e.g. _tx.value.signature_. However, at runtime (js code), the send() function actually returns the result in the legacy format, e.g. _tx.signature_

Either this is now producing an "Intellisense" error in Visual Code and the program has to be forced-run when using _tx.signature_, or this is causing a runtime error if the RpcResonse hierarchy is being used like _tx.value.signature_.

## Steps to reproduce

The following example works with devnet.
```
const signatures = await this.rpc.getSignaturesForAddress(address("4UTjuiHzKaBgZsahAMfB71HgjXbTX7dBLXnRy4Gby5tg")).send()
signatures!.forEach((tx, i) => {
  console.log(tx) // tx does not have the expected context/value structure from RpcResponse
  console.log(tx.signature) // TS validation error, but delivers correct result if forced-run
  console.log(tx.value.signature) // TS validation ok, but this is a runtime error
})
```

**Comment by buffalojoec** [comment]
Hey there, according to the [Solana JSON RPC docs](https://solana.com/docs/rpc/http/getsignaturesforaddress), this method should not return an `RpcResponse`. It returns an array of objects.

Looks like the method's definition in `@solana/rpc-core` checks out.

```ts
const rpc = null as unknown as Rpc<GetSignaturesForAddressApi>;

async () => {
    {
        const result = await rpc.getSignaturesForAddress(
            "Joe111111" as Address,
        ).send();
        result satisfies readonly { signature: Signature }[]
    }
};
```

**Comment by buffalojoec** [comment]
> you are right, inside `@solana\rpc-core\dist\types\rpc-methods\getSignaturesForAddress.d.ts` removing the **RpcResponse** from the code will make "Intellisense" work and code works as expected. I assume you guys fix that on your end or does it require a pull request from my side?
> 
> ![image](https://private-user-images.githubusercontent.com/23012666/306405352-7a97cb7e-57ac-4e0f-bc63-364818408d02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NjIwNzIsIm5iZiI6MTcwODQ2MTc3MiwicGF0aCI6Ii8yMzAxMjY2Ni8zMDY0MDUzNTItN2E5N2NiN2UtNTdhYy00ZTBmLWJjNjMtMzY0ODE4NDA4ZDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDIwNDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMjc4NzlhNjAwZmI4NzE3N2YzMjBlYzk2MWE4MmFlNDEyMDYxY2JiNzE2NDAyYmQ0MmJiODFhOGRmOWYxYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IjJmOJ6d3rKXYudF_kVvcqR3ZFml10XbdBDG1es-sM) _[Edit: The import of the RpcResponse at the top of the image can of course also be removed]_
> 
> Thanks for the instant help! Kind regards

Ohh yeah maybe you are using an older version? It definitely does not have `RpcResponse` on master.
https://github.com/solana-labs/solana-web3.js/blob/4a3c533fd1b5f972b0bca6b9d84f92ca476ce887/packages/rpc-core/src/rpc-methods/getSignaturesForAddress.ts#L7-L22

We must have fixed it!

**Comment by Akim-Personal** [comment]
oh god, thanks! I will make sure to update my library - I just looked into the experimental solana-web3.js today for the first time and had been using
`npm install --save @solana/web3.js@tp` as described in the installation guide for
`https://github.com/solana-labs/solana-web3.js/tree/bb65ba9774d7bbd80d3b37a3c61c6342b83539b8/packages/library`

Thanks a lot! Ticket can be resolved/closed.

**Comment by buffalojoec** [comment]
> oh god, thanks! I will make sure to update my library - I just looked into the experimental solana-web3.js today for the first time and had been using `npm install --save @solana/web3.js@tp` as described in the installation guide for `https://github.com/solana-labs/solana-web3.js/tree/bb65ba9774d7bbd80d3b37a3c61c6342b83539b8/packages/library`
> 
> Thanks a lot! Ticket can be resolved/closed.

That tag may actually be a bit dated at this point! We are releasing TP2 soon, but in the meantime just using the most recent version of `experimental` should do you right.
