### ISSUE TITLE
bug: 0.0041 * LAMPORTS_PER_SOL 

### ISSUE THREAD

**Issue by EdogawaDenji** [solana-labs/solana-web3.js#2282]
0.0041 * LAMPORTS_PER_SOL equal to 4100000.0000000005?

RangeError: The number 4100000.0000000005 cannot be converted to a BigInt because it is not an integer

**Comment by buffalojoec** [comment]
That's weird. The math should evaluate to `4_100_000`.

```ts
/**
 * There are 1-billion lamports in one SOL
 */
export const LAMPORTS_PER_SOL = 1000000000;
```

Do you have some repro code?
