### ISSUE TITLE
crash due to this log

### ISSUE THREAD

**Issue by philsong** [solana-labs/solana-web3.js#2288]
I found that someone report this issue before, but that bug was closed.

I check the code in connection.ts, line 6124:

and I found your guys wrote a log "// TODO: Maybe add an 'errored' state or a retry limit?".....

please tell us how to fix, because it will enter dead cycyle and eat all of memory and make the machine crash...

`                  } catch (e) {
                    if (e instanceof Error) {
                      console.error(`${unsubscribeMethod} error:`, e.message);
                    }
                    if (!isCurrentConnectionStillActive()) {
                      return;
                    }
                    // TODO: Maybe add an 'errored' state or a retry limit?
                    this._setSubscription(hash, {
                      ...subscription,
                      state: 'subscribed',
                    });
                    await this._updateSubscriptions();
                    return;
                  }`

logs below:

accountUnsubscribe error: write EPIPE
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)
accountUnsubscribe error: Tried to call a JSON-RPC method `accountUnsubscribe` but the socket was not `CONNECTING` or `OPEN` (`readyState` was 2)

**Comment by lithdew** [comment]
I guess `isCurrentConnectionStillActive` could be amended to also check the `readyState` of the underlying WebSocket instance to see if it is `WebSocket.CONNECTED`.

**Comment by steveluscher** [comment]
What version of `@solana/web3.js` are you running? Something similar was fixed in 1.17.3. Read this for details. https://github.com/solana-labs/solana-web3.js/issues/1106

The important question is, what version of `rpc-websockets` is installed?

**Comment by philsong** [comment]
> What version of `@solana/web3.js` are you running? Something similar was fixed in 1.73.3. Read this for details. #1106
> 
> The important question is, what version of `rpc-websockets` is installed?

"@solana/web3.js": "1.87.6"

**Comment by philsong** [comment]
"rpc-websockets": "^7.5.1",

**Comment by philsong** [comment]
thanks! I got the reason, it seems that the a lib refer a old version!
