### ISSUE TITLE
Introduce literal enum codec.

### ISSUE THREAD

**Issue by lithdew** [solana-labs/solana-web3.js#2296]
As of right now, we have both `getScalarEnumCodec` and `getDataEnumCodec` for specifying enums.

It would be useful to be able to specify enum codecs with string/number literals as its input/output, similar to Zod's `z.enum([])`.

Example:
```ts
const currencyCodec = getLiteralEnumCodec(["sol", "like", "usdc"]);
const bytes = currencyCodec.encode("sol"); // 0x00
const decoded = currencyCodec.decode(Uint8Array.of(0x01)); // "sol" | "like" | "usdc"
```

**Comment by lorisleiva** [comment]
Oh that's interesting. Technically you can use `getScalarEnumCodec` with an enum that uses string variants to achieve a similar result but that would be a nice way to bypass the `enum` lookup object altogether.

Thanks for all your codec feedback btw, it's much appreciated.

**Comment by lithdew** [comment]
Right - to bypass the `enum` lookup object altogether, the code is a bit manual. Might you have any suggestions on improving how the codec is mapped?

```ts
export enum Currency {
  sol,
  like,
  usdc,
}

export const CURRENCY_CODEC = mapCodec(
  getScalarEnumCodec(Currency),
  (v: "sol" | "like" | "usdc") => {
    switch (v) {
      case "sol":
        return Currency.sol;
      case "like":
        return Currency.like;
      case "usdc":
        return Currency.usdc;
    }
  },
  (v: ScalarEnumFrom<typeof Currency>) => {
    switch (v) {
      case 0:
      case Currency.sol:
        return "sol";
      case 1:
      case Currency.like:
        return "like";
      case 2:
      case Currency.usdc:
        return "usdc";
    }

    throw new Error("Invalid currency");
  }
);
```

**Comment by lorisleiva** [comment]
Oh no I meant that you can use a scalar enum with string variants like so:

```ts
export enum Currency {
    sol = 'sol',
    like = 'like',
    usdc = 'usdc',
}

const codec = getScalarEnumCodec(Currency);
codec.encode('sol'); // 0x00
codec.decode(new Uint8Array([1])); // 'like'
```

**Comment by lithdew** [comment]
Ah got it. Thought the values had to be numbers as there are some cases where we can't rely on the enum's key ordering to figure out an enum's byte representation/value (if, say, we wanted to define a scalar enum codec schema in JSON).

Based on the way the types are defined for `getScalarEnum` also btw, noticed that an object could be passed in as well.

```ts
const codec = getScalarEnumCodec({
  sol: "sol",
  like: "like",
  usdc: "usdc"
});
```

**Comment by lorisleiva** [comment]
Knowing that, do you still think there is a need for `getLiteralEnumCodec(["sol", "like", "usdc"])`?

**Comment by lithdew** [comment]
> Knowing that, do you still think there is a need for `getLiteralEnumCodec(["sol", "like", "usdc"])`?

Hmm I still think it would be a nice-to-have - Zod for example has separate `nativeEnum` and `enum` validators.

I think it would be better for `getScalarEnumCodec` to encode enum literals directly to the values it maps to (meaning the enum's values must be of a literal type that can be encoded to bytes).

**Comment by lorisleiva** [comment]
Do you mean this?

```ts
export enum Currency {
    sol,
    like,
    usdc,
}

const codec = getScalarEnumCodec(Currency);
codec.encode('sol'); // 0x00
codec.encode('like'); // 0x01
codec.encode('usdc'); // 0x02
```

Because that's already possible. It's just that when you decode, you'll get the values of the enum.

```ts
codec.decode(new Uint8Array([0])); // Currency.sol (same as 0)
codec.decode(new Uint8Array([1])); // Currency.like (same as 1)
codec.decode(new Uint8Array([2])); // Currency.usdc (same as 2)
```

[Here's another example](https://github.com/solana-labs/solana-web3.js/tree/master/packages/codecs-data-structures#scalar-enum-codec).

**Comment by lithdew** [comment]
I mean like this:

```ts
import { getScalarEnumCodec } from "@solana/web3.js";

export enum Currency {
    sol = 3,
    like = 5,
    usdc = 9,
}

const codec = getScalarEnumCodec(Currency);
console.log(codec.encode('sol')); // Should be 0x03
console.log(codec.encode('like')); // Should be 0x05
console.log(codec.encode('usdc')); // Should be 0x09
```

**Comment by lorisleiva** [comment]
Oh wait is that not the case?! If so that's a bug then. Do you want to raise a separate issue for it?

**Comment by lithdew** [comment]
If we are to reference how types are named in C or Zig, the naming convention would be the following:

```ts
getEnumCodec(); // Enums are available in C and Zig. Should support both JavaScript unions and an array of literals.
getDiscriminatedUnionCodec(); // Discriminated unions are available in C and Zig.
```

**Comment by lorisleiva** [comment]
Since the encoded/decoded types are actually represented as TypeScript type, I think it makes more sense to follow a naming convention that's idiomatic with the JavaScript/TypeScript language instead of C, Rust or Zig.

It is up to the designer of these codecs to decide how they want to represent these byte arrays in something that fits in TypeScript land.

Related: I'm also thinking of renaming `getStructCodec` to `getObjectCodec` to stay consistent in that regard ([See discord message](https://discord.com/channels/428295358100013066/976527749973942374/1218129669853941780)). So the proposed API here would become `getObjectUnionCodec` instead of `getStructUnionCodec`, _or_ `getDiscriminatedUnionCodec` as you suggested since there will be a common discriminator attribute to these objects.

**Comment by lithdew** [comment]
Hmm if we are to follow TypeScript's naming conventions, what about these?

```ts
getRecordCodec(); // Represents a Record<string, any>.
getLiteralEnumCodec(); // Represents a literal enum expression.
getDiscriminatedUnionCodec(); // Represents a union that is discriminated by an expression.
```

**Comment by lorisleiva** [comment]
In the end, I went for:

```ts
getEnumCodec();
getLiteralEnumCodec();
getDiscriminatedUnionCodec();
```

As you suggested initially.
