### ISSUE TITLE
Feature suggestion: allow more seed types to be provided to getProgramDerivedAddress()

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#2312]
For https://github.com/solana-labs/solana-web3.js/blob/273bc9e5087fb17097aab5e47a215b5196e7e906/packages/addresses/src/program-derived-address.ts#L80 , if I read this correctly, I don't have to do `Buffer.from("someString")` when running `getProgramDerivedAddress()`  since `ProgramDerivedAddressInput` includes strings so I can just provide the string directly, avoiding the need to write boilerplate.

**What if we allowed Addresses, BigInts etc?** If an Address is provided as a seed, encode it as a byte array. 

## Motivation + Example use case

When working with web3.js 1.x code, I notice a lot of boilerplate encoding code:

### Before

```ts
const pdaAndBump = PublicKey.findProgramAddressSync(
  [
    Buffer.from("somestring"),
    userKeypair.publicKey.toBuffer(),
    id.toBuffer("le", 8),
  ],
  programKeypair.publicKey
);
```

So wrote a little wrapper that follows this technique, checking for different types end consistently encoding them:

### After

```ts
const pdaAndBump = getPDAAndBump(
   ["somestring", userKeypair.publicKey, id],
   programKeypair.publicKey
);
```

## Details

For your own reference, this is what my own `getPDAAndBump()`looked like, I'm sure you could write something better though:

```ts
// A generic function to take strings, publickeys, and BNs
// does whatever work is necessary to turn them into PDAs
export const getPDAAndBump = (
  // @ts-ignore this type exists
  inputs: Array<string | PublicKey | BN>,
  programId: PublicKey
) => {
  const buffers = inputs.map((input) => {
    if (typeof input === "string") {
      return Buffer.from(input);
    }
    // TODO: not sure why instanceof occasionally doesn't work
    // fix it and get rid of the constructor hack
    if (input instanceof PublicKey || input.constructor.name === "PublicKey") {
      return input.toBuffer();
    }
    // @ts-ignore this type exists
    if (input instanceof BN) {
      return input.toBuffer("le", 8);
    }
    throw new Error("getPDAAndBump: unsupported type");
  });
  const programAddressAndBump = PublicKey.findProgramAddressSync(
    buffers,
    programId
  );
  return programAddressAndBump;
};
```

**Comment by PoulavBhowmick03** [comment]
We can firstly change the type Seed to
`type Seed = Uint8Array | string | Address | bigint | number;`
Then we can write a function where we implement checking and implementing the conversion based on the seed
```
function encodeSeed(seed: Seed): Uint8Array {
  if (typeof seed === 'string') {
    return Buffer.from(seed);
  }
  if (seed instanceof Uint8Array) {
    return seed;
  }
  if (seed instanceof Address) {
    return seed.toBytes();
  }
  if (typeof seed === 'bigint') {
    return Buffer.from(seed.toString(16).padStart(16, '0'), 'hex');
  }
  if (typeof seed === 'number') {
    return Buffer.from(BigInt(seed).toString(16).padStart(16, '0'), 'hex');
  }
  throw new Error('Unsupported seed type');
}
```

**Comment by steveluscher** [comment]
> What if we allowed Addresses, BigInts etc

`Address` is already allowed since it's a supertype of `string`. In general, APIs that allow large unions of inputs like this are Bad Actually™ because they require that the implementation handle all possible inputs, even if they won't be called upon to.

For instance, if we accepted `bigint`, we'd have to hard-require the u64 codec inside `getProgramDerivedAddress()`. If the developer never passed a bigint into that function, the codec would never be used, leading to poor package efficiency (ratio of **code used** to **code shipped** in the bundle). I think the only reason this function accepts strings is that we didn't have to bundle a codec – `TextEncoder()` is available in the runtime.
