### ISSUE TITLE
getBalance() method got error: fetch failed

### ISSUE THREAD

**Issue by blockchainlee** [solana-labs/solana-web3.js#2327]
I tried to use getBalance() method, but I got an error: 
Error: failed to get balance of account GAcD...Di9xp: TypeError: fetch failed
I found that I call any method under Connection, I got the same error.
![image](https://github.com/solana-labs/solana-web3.js/assets/122244941/7aa57225-d561-42c1-bd26-a0f03a2ebc93)
![image](https://github.com/solana-labs/solana-web3.js/assets/122244941/6b010bc2-039a-4d5c-a008-bb925d907b8b)

I guess maybe I should use agent, so I change my code to
const connection = new Connection(clusterApiUrl('devnet'), {httpAgent: agent})
But I got another error:
![image](https://github.com/solana-labs/solana-web3.js/assets/122244941/2f758f3e-65d1-4d21-9a00-d5a10d289ea9)
![image](https://github.com/solana-labs/solana-web3.js/assets/122244941/e293aa3a-d8c2-427c-be5e-8de2c39ed33a)

What should I do? Please help me, thanks.

**Comment by yarcowang** [comment]
Yes, I do have similar problem. 
[https://github.com/anza-xyz/agave/issues/311](https://github.com/anza-xyz/agave/issues/311)
And for now, axio seems the only solution.
