### ISSUE TITLE
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)

### ISSUE THREAD

**Issue by aylizhiyuan** [solana-labs/solana-web3.js#2328]
package.json

"dependencies": {
    "@solana-developers/helpers": "^2.1.0",
    "@solana/web3.js": "^1.91.1",
    "dotenv": "^16.4.5"
  }

node v21.6.2

how to fix ?

**Comment by FranklysG** [comment]
+1

**Comment by buffalojoec** [comment]
https://solana.stackexchange.com/questions/4077/bigint-failed-to-load-bindings-pure-js-will-be-used-try-npm-run-rebuild-whe

**Comment by FranklysG** [comment]
> https://solana.stackexchange.com/questions/4077/bigint-failed-to-load-bindings-pure-js-will-be-used-try-npm-run-rebuild-whe

I have tried this before, but the problem continues on macos
