### ISSUE TITLE
What is the workaround for the "TransactionExpiredBlockheightExceededError" error when transferring "spl-tokens"?

### ISSUE THREAD

**Issue by devwonjun** [solana-labs/solana-web3.js#2337]
I changed the node endpoint to try to resolve the error in the link below, 
adding fee costs, and adding blockhash values, but I still get the following error. 

Is this a node issue? Or is it an SDK issue? Or is there an error in some part of the source?

When I run it, the transfer fails 7-8 times out of 10 and I get the following error. 

Error issues : 
https://solana.stackexchange.com/questions/12063/what-is-the-workaround-for-the-transactionexpiredblockheightexceedederror-erro

**Comment by ctapang** [comment]
I am experiencing this exact same issue. This is not a question: it's a problem that needs to be fixed.
