### ISSUE TITLE
[experimental] RPC error code leaks to `@solana/errors decode` command

### ISSUE THREAD

**Issue by mcintyre94** [solana-labs/solana-web3.js#2357]
## Overview

- I'm debugging a transaction, and tried to send it using `rpc.sendTransaction`
- I got this CLI message: "SolanaError: Solana error #-32003; Decode this error by running `npx @solana/errors decode -32003`"
- When I run that I get the error "error: unknown option '-32003'"
- This error code is coming from the RPC response:
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32003,
        "message": "Transaction signature verification failure"
    },
    "id": "165e9fc6-d535-4e27-9a3e-5704e6df035f"
}
```
- But I don't think it should be coming through as the code to decode in the error message

## Steps to reproduce

Stackblitz repro: https://stackblitz.com/edit/stackblitz-starters-gqi19c?file=index.mjs

Basically just create + try to send a transaction with a fake signature
Code from the repro: 
```
import {
  createSolanaRpc,
  createTransaction,
  getBase64EncodedWireTransaction,
  pipe,
  setTransactionFeePayer,
  setTransactionLifetimeUsingBlockhash,
} from '@solana/web3.js';

async function main() {
  // wallet with some devnet sol
  const feePayer = 'Fkc4FN7PPhyGsAcHPW3dBBJ4BvtYkDr2rBFBgFpvy3nB';

  const rpc = createSolanaRpc('https://api.devnet.solana.com');

  const { value: blockhashResponse } = await rpc.getLatestBlockhash().send();

  const transaction = pipe(
    createTransaction({ version: 0 }),
    (tx) => setTransactionFeePayer(feePayer, tx),
    (tx) => setTransactionLifetimeUsingBlockhash(blockhashResponse, tx)
  );

  const fakeSignature = new Uint8Array(64);
  fakeSignature.fill(255);

  const signedTransaction = {
    ...transaction,
    signatures: {
      [feePayer]: fakeSignature,
    },
  };

  const serializedTransaction =
    getBase64EncodedWireTransaction(signedTransaction);

  await rpc
    .sendTransaction(serializedTransaction, { encoding: 'base64' })
    .send();
}

main().catch(console.error);
```

**Comment by steveluscher** [comment]
Nah, I knew this would happen. It's 100% supposed to work this way, it's just the hyphen is throwing it off. I need to surround the error code in quotes or something.

**Comment by steveluscher** [comment]
https://github.com/tj/commander.js/issues/1556
