### ISSUE TITLE
Unusual SEO and Redirection Issues After Solana Wallet Integration (SEO "hacking"?)

### ISSUE THREAD

**Issue by LFerronato** [solana-labs/solana-web3.js#2378]
## Overview

Hello Solana team,

We've recently encountered two significant issues upon integrating Solana wallet functionality into our dApp (domain: gray.market), and we're hoping for some guidance or a resolution.

1. **Unexpected Redirection**:
   Some of our users have reported that when they attempt to access our dApp, they are being redirected to https://solanamobile.com/wallets. This behavior is unexpected and has not been coded into our dApp by our team.
   (video)

https://github.com/solana-labs/solana-web3.js/assets/43012047/1b1f7030-1e6a-4a5d-b7dd-608c85c5f17d

2. **SEO Content Overwrite**:
   The more critical issue is a mysterious change in our Google SEO data. Since the integration, the title and description in Google's search results have been replaced with content that does not exist on our site and has never been part of our codebase. Here are the changes observed:
   - Title: "Choose The Best Wallet"
   - Description: "Discover top Solana wallets and their unique features. Compare and choose the best one for your needs. Check out Phantom, Solflare, and more wallets now."

   These changes are only appearing in Google's search results and not on other search engines like Bing.

We have not made any changes that would cause either of these issues, and they only began after the Solana wallet integration. We are concerned about a potential library or dependency that might be affecting our dApp's behavior and SEO metadata.

Any assistance or insights you can provide would be greatly appreciated. Attached is a screenshot from Google's search results highlighting the SEO issue.

Thank you for your time and help.

## Steps to reproduce

just search "gray.market" on google
![image](https://github.com/solana-labs/solana-web3.js/assets/43012047/83033040-4dde-4fcb-be83-105206dd186a)

## Description of bug

Dependencies:
```
    "@solana/spl-token": "^0.4.0",
    "@solana/wallet-adapter-react": "^0.15.35",
    "@solana/wallet-adapter-react-ui": "^0.9.34",
    "@solana/wallet-adapter-wallets": "^0.19.25",
    "@solana/web3.js": "^1.89.1",
    "bs58": "^5.0.0",
    "next": "14.0.4",
```

**Comment by LFerronato** [comment]
sry... adding description, type CTRL+Enter early

**Comment by LFerronato** [comment]
I'm just not terribly worried, because the redirect link goes to the correct site... but still

**Comment by mcintyre94** [comment]
Please could you open this issue against the https://github.com/anza-xyz/wallet-adapter repo? I'm unable to transfer it because it's in a different github org but that's where this should be. I assume this is something to do with the mobile wallet adapter integration in wallet-adapter. When you open the issue there could you also clarify which OS/browser you're seeing this on?
