### ISSUE TITLE
[GraphQL]: Optimize cache-key function

### ISSUE THREAD

**Issue by buffalojoec** [solana-labs/solana-web3.js#2405]
#### Problem
Since `fast-stable-stringify` doesn't support `bigint` natively, we've had to use `json-stable-stringify` in the GraphQL library.

However, [`json-stable-stringify`](https://www.npmjs.com/package/json-stable-stringify), is _huge_, and we shouldn't introduce this bloat to the codebase.

#### Proposed Solution
We can do one of three things:
1. Find a very lightweight cache-key function library that supports `bigint`.
2. Fork `fast-stable-stringify` and add `bigint` support.
3. PR `bigint` support into `fast-stable-stringify`.

**Comment by Hrushi20** [comment]
Hey! I'm interested in working on this issue. Do I replace [json-stable-stringify](https://www.npmjs.com/package/json-stable-stringify) with [fast-stable-stringify](https://www.npmjs.com/package/fast-stable-stringify) in package.json file?

**Comment by buffalojoec** [comment]
> Hey! I'm interested in working on this issue. Do I replace [json-stable-stringify](https://www.npmjs.com/package/json-stable-stringify) with [fast-stable-stringify](https://www.npmjs.com/package/fast-stable-stringify) in package.json file and update the code usage?

Hey, I've added some more context to the issue! Let me know if you still have questions.

**Comment by Hrushi20** [comment]
What is the definition of cache-key function? Also I see that `stringify` in [json-stable-stringify](https://www.npmjs.com/package/json-stable-stringify) converts the object into JSONString.

**Comment by Hrushi20** [comment]
We can try option 3, `fast-stable-stringify` has not been updated since 7years. Not sure if the project is active. We can fallback to option 2 as our next option.

**Comment by Hrushi20** [comment]
[json-stringify-deterministic](https://github.com/kikobeats/json-stringify-deterministic) also looks like a very good option. There is a 50% reduction in size of dependency.

**Comment by buffalojoec** [comment]
Yeah that's not bad. I'm a bit biased, though because `fast-stable-stringify` is < 1 kB minified.
https://bundlephobia.com/package/fast-stable-stringify@1.0.0

I think if we forked it into our monorepo here and just added `bigint` support we could still capture ~1 kB minified size, which is awesome, especially for anywhere else we use it.

What do you think of going the fork route? `@solana/fast-stable-stringify`?

**Comment by Hrushi20** [comment]
Sounds good to me. I'm working on it.

**Comment by Hrushi20** [comment]
I've [forked and updated](https://github.com/Hrushi20/fast-stable-stringify) the package to support BigInt. I've also added some tests to ensure correct behavior.

**Comment by buffalojoec** [comment]
> Can the forked package be in javascript?

Yes!

> I've [forked and updated](https://github.com/Hrushi20/fast-stable-stringify) the package to support BigInt. I've also added some tests to ensure correct behavior.

Are you planning to open a pull request to add it to this monorepo? That would be the ideal place for us!

**Comment by Hrushi20** [comment]
> > Can the forked package be in javascript?
> 
> Yes!
> 
> > I've [forked and updated](https://github.com/Hrushi20/fast-stable-stringify) the package to support BigInt. I've also added some tests to ensure correct behavior.
> 
> Are you planning to open a pull request to add it to this monorepo? That would be the ideal place for us!

Working on adding it to monorepo.
