### ISSUE TITLE
[GraphQL]: Token-2022 Extension Instructions

### ISSUE THREAD

**Issue by buffalojoec** [solana-labs/solana-web3.js#2406]
## Motivation

Token-2022 extensions are live and gaining popularity on all clusters. The GraphQL library must offer support for these extension instructions within the schema.

- [x] `ConfidentialTransferFee`
  - [x] `InitializeConfidentialTransferFeeConfig`
  - [x] `WithdrawWithheldTokensFromMint`
  - [x] `WithdrawWithheldTokensFromAccounts`
  - [x] `HarvestWithheldTokensToMint`
  - [x] `EnableHarvestToMint`
  - [x] `DisableHarvestToMint`
- [x] `ConfidentialTransfer`
  - [x] `InitializeMint`
  - [x] `UpdateMint`
  - [x] `ConfigureAccount`
  - [x] `ApproveAccount`
  - [x] `EmptyAccount`
  - [x] `Deposit`
  - [x] `Withdraw`
  - [x] `Transfer`
  - [x] `ApplyPendingBalance`
  - [x] `EnableConfidentialCredits`
  - [x] `DisableConfidentialCredits`
  - [x] `EnableNonConfidentialCredits`
  - [x] `DisableNonConfidentialCredits`
  - [x] `TransferWithSplitProofs`
- [x] `CpiGuardInstruction`
  - [x] `Enable`
  - [x] `Disable`
- [x] `DefaultAccountStateInstruction`
  - [x] `Initialize`
  - [x] `Update`
- [x] `GroupMemberPointerInstruction`
  - [x] `Initialize`
  - [x] `Update`
- [x] `GroupPointerInstruction`
  - [x] `Initialize`
  - [x] `Update`
- [x] `InterestBearingMintInstruction`
  - [x] `Initialize`
  - [x] `Update`
- [x] `RequiredMemoTransfersInstruction`
  - [x] `Enable`
  - [x] `Disable`
- [x] `MetadataPointerInstruction`
  - [x] `Initialize`
  - [x] `Update`
- [x] `InitializeMintCloseAuthority`
- [x] `InitializePermanentDelegate`
- [x] `Reallocate`
- [x] `TokenGroupInstruction`
  - [x] `InitializeGroup`
  - [x] `UpdateGroupMaxSize`
  - [x] `UpdateGroupAuthority`
  - [x] `InitializeMember`
- [ ] `TokenMetadataInstruction`
  - [x] `Initialize`
  - [x] `UpdateField`
  - [x] `RemoveKey`
  - [ ] `UpdateAuthority`
  - [ ] `Emit`
- [x] `TransferFeeInstruction`
  - [x] `InitializeTransferFeeConfig`
  - [x] `TransferCheckedWithFee`
  - [x] `WithdrawWithheldTokensFromMint`
  - [x] `WithdrawWithheldTokensFromAccounts`
  - [x] `HarvestWithheldTokensToMint`
- [x] `TransferHookInstruction`
  - [x] `Initialize`
  - [x] `Update`

**Comment by Hrushi20** [comment]
Hey! I'm interested in working on this issue. Can I get more context on getting started?

**Comment by buffalojoec** [comment]
Basically we need to add schema support for Token-2022 extensions. These will appear in a JSON-parsed instruction from an RPC-retrieved transaction or block.

I've marked a little placeholder in the instructions schema module where they can live:
https://github.com/solana-labs/solana-web3.js/blob/acd929d95124df0f5b3e9d22fa97e7d870fe947f/packages/rpc-graphql/src/schema/instruction.ts#L515-L529

I think the easiest way to roll each of these is to grab their layouts from the Solana Transaction Status crate:
https://github.com/anza-xyz/agave/blob/master/transaction-status/src/parse_token.rs

That file should have all the Token-2022 extensions that are parseable by the RPC's JSON-parsed, and we can just adapt them into GraphQL schema types!

The tricky bit is going to be querying the RPC manually (likely via CLI or something) and finding transaction payloads that have some of these instructions and using them in tests. You can just copy-paste them into the `__setup__` module as we've done already:
https://github.com/solana-labs/solana-web3.js/blob/master/packages/rpc-graphql/src/__tests__/__setup__.ts

**Comment by Hrushi20** [comment]
Looking into it.

**Comment by Hrushi20** [comment]
Hey! I was going through `transfer_fee.rs` file. I see that `mint` field is [stored as a String in json](https://github.com/anza-xyz/agave/blob/master/transaction-status/src/parse_token/extension/transfer_fee.rs#L17). In rpc-grpc module, in some places `mint`[ is used as Account type.](https://github.com/solana-labs/solana-web3.js/blob/master/packages/rpc-graphql/src/schema/instruction.ts#L189). Not sure what is the right data type to use

**Comment by Hrushi20** [comment]
I'm unable to tick the checkbox in the PR.

**Comment by buffalojoec** [comment]
> pidof: command not found

You don't want to run that script yourself. Jest will run it when you run `pnpm test:unit:node`. As a side note, maybe you don't have the `pidof` command.

**Comment by Hrushi20** [comment]
Thanks it works now, however I get the following error while running the test. 
```
 FAIL   Unit Test (Node)  src/__tests__/account-test.ts
  ● Test suite failed to run

    Cannot find module '@solana/rpc' from 'src/__tests__/__setup__.ts'

    Require stack:
      src/__tests__/__setup__.ts
      src/__tests__/account-test.ts

      56 |             'Program Vote111111111111111111111111111111111111111 success',
      57 |         ],
    > 58 |         postBalances: [1007369134736714, 100000000000, 1],
         |              ^
      59 |         postTokenBalances: [],
      60 |         preBalances: [1007369134741714, 100000000000, 1],
      61 |         preTokenBalances: [],

      at Resolver._throwModNotFoundError (../../node_modules/.pnpm/jest-resolve@30.0.0-alpha.3/node_modules/jest-resolve/build/index.js:927:11)
      at Object.<anonymous> (src/__tests__/__setup__.ts:58:14)
      at Object.<anonymous> (src/__tests__/account-test.ts:6:19)



```

I've done an `pnpm install` at root directory level. Still 5 tests are failing. 
Due to this I'm unable to check the build passing locally.

**Comment by buffalojoec** [comment]
> Thanks it works now, however I get the following error while running the test.
> 
> ```
>  FAIL   Unit Test (Node)  src/__tests__/account-test.ts
>   ● Test suite failed to run
> 
>     Cannot find module '@solana/rpc' from 'src/__tests__/__setup__.ts'
> 
>     Require stack:
>       src/__tests__/__setup__.ts
>       src/__tests__/account-test.ts
> 
>       56 |             'Program Vote111111111111111111111111111111111111111 success',
>       57 |         ],
>     > 58 |         postBalances: [1007369134736714, 100000000000, 1],
>          |              ^
>       59 |         postTokenBalances: [],
>       60 |         preBalances: [1007369134741714, 100000000000, 1],
>       61 |         preTokenBalances: [],
> 
>       at Resolver._throwModNotFoundError (../../node_modules/.pnpm/jest-resolve@30.0.0-alpha.3/node_modules/jest-resolve/build/index.js:927:11)
>       at Object.<anonymous> (src/__tests__/__setup__.ts:58:14)
>       at Object.<anonymous> (src/__tests__/account-test.ts:6:19)
> ```
> 
> I've done an `pnpm install` at root directory level. Still 5 tests are failing. Due to this I'm unable to check the build passing locally.

Hm, I'm not able to reproduce it locally. I can see that your error is saying the dependency isn't found. Maybe try this from root.

```
pnpm i
pnpm turbo compile:js compile:typedefs
cd packages/rpc-graphql
pnpm test:unit:node
```

**Comment by Hrushi20** [comment]
What is the node.js, npm and turbo version you are using?

**Comment by buffalojoec** [comment]
> What is the node.js, npm and turbo version you are using?

```
$ node --version
v20.8.1

$ npm --version
10.1.0

$ pnpm turbo --version
1.13.3
```

**Comment by Hrushi20** [comment]
I tried this on a new machine. I installed node & npm using [nvm](https://github.com/nvm-sh/nvm). I tried install pnpm in below image and I get this error. 

<img width="921" alt="Screenshot 2024-05-04 at 9 40 02 PM" src="https://github.com/solana-labs/solana-web3.js/assets/65367566/c772e53c-a753-44d4-8c51-8d8be4e49cd8">

**Comment by buffalojoec** [comment]
Ohh I've installed `pnpm` with Homebrew on MacOS. I should have posted that version as well.

```
$pnpm --version
9.0.6
```

**Comment by Hrushi20** [comment]
Thanks mate. Was trying since forever. Got it to work now.

**Comment by nasjuice** [comment]
Hello, could I help with this also? I can start InterestBearingMintInstruction

**Comment by Hrushi20** [comment]
> Hello, could I help with this also? I can start InterestBearingMintInstruction

I already started working on it. Feel free to start with another extension.

**Comment by nasjuice** [comment]
Sounds good, I'll start with this extension then ConfidentialTransfer

**Comment by nasjuice** [comment]
I believe InitializeMint has been done for ConfidentialTransfer

https://github.com/nasjuice/solana-web3.js/blob/d275ba641b3d65f81c7a2c200824f195583b0c9c/packages/rpc-graphql/src/schema/instruction.ts#L745

**Comment by nasjuice** [comment]
Also just noticed this

https://github.com/solana-labs/solana-web3.js/blob/16bb0b86410fe326d2f617f6ee800ce68f918864/packages/rpc-graphql/src/schema/instruction.ts#L626

I believe that should be a BigInt since is a u64
https://github.com/nasjuice/agave/blob/a645d07e06a5b2da8076539d5799a5087c5cff52/transaction-status/src/parse_token/extension/transfer_fee.rs#L21

**Comment by buffalojoec** [comment]
> Also just noticed this
> 
> 
> 
> https://github.com/solana-labs/solana-web3.js/blob/16bb0b86410fe326d2f617f6ee800ce68f918864/packages/rpc-graphql/src/schema/instruction.ts#L626
> 
> 
> 
> I believe that should be a BigInt since it is a u64
> 
> https://github.com/anza-xyz/agave/blob/a645d07e06a5b2da8076539d5799a5087c5cff52/transaction-status/src/parse_token/extension/transfer_fee.rs#L21

Thanks I'll look into this. I think _all_ `Int` fields in the instructions may need to become `BigInt`, but I can make that change.

**Comment by buffalojoec** [comment]
@Hrushi20 @nasjuice Hey guys, let's make sure to use the type aliases, such as `Slot`, `Epoch` and `Lamports` wherever appropriate.

I've added more of them in this PR: https://github.com/solana-labs/solana-web3.js/pull/2634.

**Comment by buffalojoec** [comment]
@Hrushi20 @nasjuice Thank you both for an awesome effort and hammering out all of these extensions!! I'll be sure to shout you guys out in the release.

If there's anything else you're interested in working on, feel free to tag me and ask any questions. As I continue to build the GraphQL demo application, I'll uncover more issues and things that need to be done in the GraphQL library.

The repository is public, and if you have ideas on stuff you want to add/showcase in the demo app, go ahead and dive in! Maybe we can work in the issues here, and over there as well!

https://github.com/buffalojoec/graphql-wallet
