### ISSUE TITLE
Unable to confirm transaction in Deno

### ISSUE THREAD

**Issue by livthomas** [solana-labs/solana-web3.js#2461]
## Overview

Since #1120 was closed, I assume this library now supports Deno runtime. Some use cases work but not the `Connection.confirmTransaction` method.

## Steps to reproduce

https://github.com/rockawayx-labs/bug-reproducers/tree/dev/solana-labs/solana-web3.js/deno

## Description of bug

The following warning and error is being printed to the console:
```
Warning: Not implemented: ClientRequest.options.createConnection
ws error: Invalid WebSocket frame: invalid UTF-8 sequence
```

It looks like it is a missing feature in Deno: https://github.com/denoland/deno/issues/19507 However, other libraries were able to work around it as you can see in the discussion (e.g. [discord.js](https://github.com/denoland/deno/pull/19412)).

Repro for 2.x line: https://codesandbox.io/p/devbox/flamboyant-villani-f4kgd7

**Comment by benjiqq** [comment]
thanks for reporting, getting the same. so would need to patch web3.js?

**Comment by steveluscher** [comment]
Awesome report. Thank you.

We won't be fixing this for the 1.x library (accepting PRs though) but I will use this issue to track the bug for the 2.x line.

**Comment by jcardama** [comment]
Just tested with v1.91.6 on Deno, and the issue still persists.

```
Warning: Not implemented: ClientRequest.options.createConnection
ws error: Invalid WebSocket frame: invalid UTF-8 sequence
```

The issue was fixed for v2.x so until v2.x is released or it gets fixed for 1.x the issue will remain.

**Comment by steveluscher** [comment]
That's right. We're generally not working on the 1.x line any longer, but I'll happily review a PR if a Deno user would like to propose one.

It might be easier to send a PR to the `rpc-websockets` project, but again I haven't looked into it.
