### ISSUE TITLE
Hash collision with bigint and string in `@solana/fast-stable-stringify`

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#2496]
#2482 added native bigint support to the hasher, but now these two datastructures produce the same hash:

```ts
stringify({foo: 10n});
stringify({foo: "10n"});
```

We need a solution for this. Since the hash doesn't have to be valid JSON, we should be able to use a prefix/suffix on the key/value pair. 

Test case: https://codesandbox.io/p/devbox/goofy-shadow-jsnpv3

**Comment by Hrushi20** [comment]
Do I prefix it with `__bigint`?

**Comment by steveluscher** [comment]
I would do a single glyph, to keep the size of the hash down.
