### ISSUE TITLE
When constructing and serializing a versioned transaction, if you don't pass blockhash error is "Expected String"

### ISSUE THREAD

**Issue by ChewingGlass** [solana-labs/solana-web3.js#2526]
## Overview
When constructing and serializing a versioned transaction, if you don't pass blockhash error is "Expected String". This error is very difficult to debug, and not obvious what the issue is

## Steps to reproduce

Construct and serialize a versionedtx without passing a blockhash

## Description of bug

The error thrown is not helpful.

**Comment by steveluscher** [comment]
TypeScript should prevent you from omitting the blockhash when constructing a V0 message. Do you have TypeScript enabled, and if so, why is a type error not being raised?

**Comment by steveluscher** [comment]
For completeness, `Expected String` is being thrown from `bs58#decodeUnchecked` because the argument is `undefined`.

**Comment by ChewingGlass** [comment]
```
export type TransactionDraft = {
  recentBlockhash?: string;
  feePayer: PublicKey;
  instructions: TransactionInstruction[];
  addressLookupTableAddresses?: PublicKey[];
  // Result from loooking up lookup table addresses
  addressLookupTables?: AddressLookupTableAccount[];
  signers?: Signer[];
};

function toVersionedTx(tx: TransactionDraft): VersionedTransaction {
  const messageV0 = new TransactionMessage({
    payerKey: tx.feePayer,
    recentBlockhash: tx.recentBlockhash!,
    instructions: tx.instructions,
  }).compileToV0Message(tx.addressLookupTables!);
  return new VersionedTransaction(messageV0);
}
```

This does not throw a type error

**Comment by steveluscher** [comment]
```
    recentBlockhash: tx.recentBlockhash!,
```

The TypeScript non-null assertion operator strikes again.
