### ISSUE TITLE
[experimental] Use optimized base16 encode strategy

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#2527]
This is apparently way faster than what [we're doing here](https://github.com/solana-labs/solana-web3.js/blob/b8f006d6fe1837231b854ea8d3054ac6a630f305/packages/codecs-strings/src/base16.ts#L17-L22): https://github.com/paulmillr/noble-curves/pull/83

**Comment by steveluscher** [comment]
Are you interested in fixing this one too @arobsn?

**Comment by tibi77** [comment]
@steveluscher i did push a pr for this Issue, but i m unsure how we can test it

**Comment by tibi77** [comment]
i m not reffering to the correctness of the code, but rather to the improve in speed

**Comment by arobsn** [comment]
> Are you interested in fixing this one too @arobsn?

Oh, didn't see the notification, sorry. Happy you guys have this fixed now :)
