### ISSUE TITLE
Cascade Bumping of dependencies after release cause typing error while rebuilding

### ISSUE THREAD

**Issue by vallhallalm** [solana-labs/solana-web3.js#2533]
## Overview

Hi,
While trying to reinstall the packages of my typescript application using npm v10.5.0 (node v20.12.1) I came across an issue that led me not to be able to build (using ./node_modules/typescript/bin/tsc). solana-web3.js has had a really recent release and it seems like the update of solana-web3.js create a cascade of dependencies update that leads me to the following kind of error: 
```
node_modules/@solana/codecs-data-structures/dist/types/data-enum.d.ts:72:44 - error TS1139: Type parameter declaration expected.

72 export declare function getDataEnumEncoder<const TVariants extends Variants<Encoder<any>>>(variants: TVariants, config?: DataEnumCodecConfig<NumberEncoder>): Encoder<GetEncoderTypeFromVariants<TVariants>>;
                                              ~~~~~

node_modules/@solana/codecs-data-structures/dist/types/data-enum.d.ts:72:60 - error TS1005: ',' expected.

72 export declare function getDataEnumEncoder<const TVariants extends Variants<Encoder<any>>>(variants: TVariants, config?: DataEnumCodecConfig<NumberEncoder>): Encoder<GetEncoderTypeFromVariants<TVariants>>;
                                                              ~~~~~~~

node_modules/@solana/codecs-data-structures/dist/types/data-enum.d.ts:72:76 - error TS1005: ',' expected.

72 export declare function getDataEnumEncoder<const TVariants extends Variants<Encoder<any>>>(variants: TVariants, config?: DataEnumCodecConfig<NumberEncoder>): Encoder<GetEncoderTypeFromVariants<TVariants>>;
```

## Steps to reproduce

In a typescript app that contains "@solana/web3.js" as a dependencies in the package.json and which was not already updated after the recent release: 
delete node_modules folder,
delete package-lock.json file,
run npm i,
run ./node_modules/typescript/bin/tsc

You should obtain the same kind of error as shown before.

## Description of bug

When running ./node_modules/typescript/bin/tsc after installing back my node_modules I got the errors provided earlier. I expect not to get these errors just by installing back my packages 

Thanks in advance for your help

**Comment by lolelu** [comment]
Same bug here.

**Comment by TiaLanzi** [comment]
Same bug here

**Comment by lolelu** [comment]
For now, adding an override in package.json seems to be enough to solve the issue.

` "overrides": {
    "@solana/spl-token": "0.3.5"
  }`
  
  spl-token library got updated in the last realease and it brings some broken references in.

**Comment by steveluscher** [comment]
Help me understand a bit more about what's going on here:

* `@solana/web3.js` doesn't have `@solana/codecs-data-structures` in its dependency tree, so where is that coming from?
* I did a fresh install of web3.js here and TypeScript typechecks just fine: https://codesandbox.io/p/devbox/frosty-thunder-lj7pjy

Things I know:

* I screwed up the publish of `@solana/spl-token` yesterday; the versions [0.4.4](https://www.npmjs.com/package/@solana/spl-token/v/0.4.4) and [0.4.5](https://www.npmjs.com/package/@solana/spl-token/v/0.4.5) have been deprecated on NPM. If you were unlucky enough to get one of those stuck in your package lockfile, move to 0.4.6.

**Comment by lolelu** [comment]
As far as i managed to understand, `@solana/codecs-data-structures` is a dependency of `@solana/codecs`, which is 
 somehow a dependency of `@solana/spl-token`, but only in version 0.4.5. Also, it doesn't bring in a stable version of @solana-codecs, but an unstable/preview one: [@solana/codecs-data-structures](https://www.npmjs.com/package/@solana/codecs-data-structures/v/2.0.0-preview.2.20240419044947.ed79e690caa5d0d65cd9300113a4078e349e931f)

**Comment by lolelu** [comment]
Additionally, the package got updated litterally 4 hours ago, so it might be fixed by now.

**Comment by steveluscher** [comment]
I tried typechecking with `@solana/spl-token@0.4.6` and [it works](https://codesandbox.io/p/devbox/sparkling-dream-p5l325). I'm pretty sure this is just my mistake from yesterday, and you all were unlucky enough to install 0.4.4 or 0.4.5 in your apps. Sorry about that. Please upgrade to 0.4.6.

**Comment by steveluscher** [comment]
Also possible: The TypeScript feature (const type parameters) in the OP was introduced in TypeScript 5. If you're on 4 you should upgrade.

**Comment by statikdev** [comment]
I am running into this same issue.

```
project:build: ../node_modules/.pnpm/@solana+codecs-data-structures@2.0.0-preview.2/node_modules/@solana/codecs-data-structures/dist/types/data-enum.d.ts(72,44): error TS1139: Type parameter declaration expected.
project:build: ../node_modules/.pnpm/@solana+codecs-data-structures@2.0.0-preview.2/node_modules/@solana/codecs-data-structures/dist/types/data-enum.d.ts(72,60): error TS1005: ',' expected.
project:build: ../node_modules/.pnpm/@solana+codecs-data-structures@2.0.0-preview.2/node_modules/@solana/codecs-data-structures/dist/types/data-enum.d.ts(72,76): error TS1005: ',' expected.
project:build: ../node_modules/.pnpm/@solana+codecs-data-structures@2.0.0-preview.2/node_modules/@solana/codecs-data-structures/dist/types/data-enum.d.ts(72,90): error TS1109: Expression expected.
project:build: ../node_modules/.pnpm/@solana+codecs-data-structures@2.0.0-preview.2/node_modules/@solana/codecs-data-structures/dist/types/data-enum.d.ts(72,100): error TS1005: ')' expected.
project:build: ../node_modules/.pnpm/@solana+codecs-data-structures@2.0.0-preview.2/node_modules/@solana/codecs-data-structures/dist/types/data-enum.d.ts(72,120): error TS1109: Expression expected.
project:build: ../node_modules/.pnpm/@solana+codecs-data-structures@2.0.0-preview.2/node_modules/@solana/codecs-data-structures/dist/types/data-enum.d.ts(72,156): error TS1005: ';' expected.
```

> As far as i managed to understand, @solana/codecs-data-structures is a dependency of @solana/codecs, which is
somehow a dependency of @solana/spl-token, but only in version 0.4.5. Also, it doesn't bring in a stable version of @solana-codecs, but an unstable/preview one: [@solana/codecs-data-structures](https://www.npmjs.com/package/@solana/codecs-data-structures/v/2.0.0-preview.2.20240419044947.ed79e690caa5d0d65cd9300113a4078e349e931f)

The dependency resolution for me was to:

https://www.npmjs.com/package/@solana/codecs-data-structures/v/2.0.0-preview.2

> Also possible: The TypeScript feature (const type parameters) in the OP was introduced in TypeScript 5. If you're on 4 you should upgrade.

what options do we have if we cannot upgrade to typescript 5?

**Comment by steveluscher** [comment]
You could consider `patch-package` to codemod out the const keyword, but you should upgrade to TypeScript 5 if at all possible.
