### ISSUE TITLE
I tried typechecking with `@solana/spl-token@0.4.6` and [it works](https://codesandbox.io/p/devbox/sparkling-dream-p5l325). I'm pretty sure this is just my mistake from yesterday, and you all were unlucky enough to install 0.4.4 or 0.4.5 in your apps. Sorry about that. Please upgrade to 0.4.6.

### ISSUE THREAD

**Issue by 0xkumo** [solana-labs/solana-web3.js#2543]
I tried typechecking with `@solana/spl-token@0.4.6` and [it works](https://codesandbox.io/p/devbox/sparkling-dream-p5l325). I'm pretty sure this is just my mistake from yesterday, and you all were unlucky enough to install 0.4.4 or 0.4.5 in your apps. Sorry about that. Please upgrade to 0.4.6.

_Originally posted by @steveluscher in https://github.com/solana-labs/solana-web3.js/issues/2533#issuecomment-2067358517_

**Comment by 0xkumo** [comment]
still not work with my code. help me.
bellow is error. 
and used     "@solana/spl-token": "0.4.6" 

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
   Linting and checking validity of types  .Failed to compile.

./node_modules/@solana/codecs-data-structures/dist/types/data-enum.d.ts:72:44
Type error: Type parameter declaration expected.

  70 |  * @param config - A set of config for the encoder.
  71 |  */
> 72 | export declare function getDataEnumEncoder<const TVariants extends Variants<Encoder<any>>>(variants: TVariants, config?: DataEnumCodecConfig<NumberEncoder>): Encoder<GetEncoderTypeFromVariants<TVariants>>;
     |                                            ^
  73 | /**
  74 |  * Creates a data enum decoder.
  75 |  *
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by steveluscher** [comment]
What version of TypeScript are you using, and is it >=5?

**Comment by 0xkumo** [comment]
4.8.2 Is it not good?

**Comment by steveluscher** [comment]
Constant type params were added in typescript 5.
