### ISSUE TITLE
upgrading minor version breaks 

### ISSUE THREAD

**Issue by theDefiBat** [solana-labs/solana-web3.js#2568]
## Overview

Build failed when upgrading minor version 

## Description of bug

<img width="1124" alt="image" src="https://github.com/solana-labs/solana-web3.js/assets/29819481/074590df-7c96-427f-a2ae-bbbb1a0a3f74">

**Comment by theDefiBat** [comment]
might be this commit : https://github.com/solana-labs/solana-web3.js/commit/c95ff266248fb831143102eb555bcf34a0143645

**Comment by steveluscher** [comment]
Minor version meaning that you went from where to where? `2.0.0-preview.2` to `2.0.0-preview.3`?

**Comment by steveluscher** [comment]
Without a repro or more information, the best I can suggest is to rock up with a `yarn upgrade --scope @solana` to bump all versions in your lockfile to the newest.

**Comment by steveluscher** [comment]
Another thing to check: if you're on TypeScript >=4, you have to upgrade to >=5.

**Comment by steveluscher** [comment]
If you're still having problems and have answers to the questions above, feel free to open a new issue!
