### ISSUE TITLE
[experimental] `[object Object]` in error context (websocket failed to connect)

### ISSUE THREAD

**Issue by mcintyre94** [solana-labs/solana-web3.js#2572]
## Overview

- I created an `rpcSubscriptions` object with a `ws://` URL instead of `wss://` by mistake
- When I tried to use it, I got an error thrown
- When I decode it, it includes `"errorEvent": "[object Object]"` in the context
- I'm not sure if we have other cases where we're stringifying objects like this

## Steps to reproduce

```js
import { createSolanaRpc, createSolanaRpcSubscriptions } from '@solana/web3.js';
import { createRecentSignatureConfirmationPromiseFactory } from '@solana/transaction-confirmation';

const rpc = createSolanaRpc('https://api.devnet.solana.com');

const rpcSubscriptions = createSolanaRpcSubscriptions(
  'ws://api.devnet.solana.com' // bad url, should be wss://
);

const getRecentSignatureConfirmationPromise =
  createRecentSignatureConfirmationPromiseFactory({
    rpc,
    rpcSubscriptions,
  });

await getRecentSignatureConfirmationPromise({
  signature:
    '4W8HheCp1QGFVXXT3skxpZazjo9ajyFyAFfLSJaLKdmJqjFYJweKU5Agzyf9rRyDBBKGRSdanocmsJrUsamYUotT',
  commitment: 'confirmed',
  abortSignal: new AbortController().signal,
});
```

Run this, and you get:

```
Error: Solana error #8190004; Decode this error by running `npx @solana/errors decode -- 8190004 'ZXJyb3JFdmVudD0lNUJvYmplY3QlMjBPYmplY3QlNUQ='`
```

Run the `npx @solana/errors` command and you get:

```
[Decoded] Solana error code #8190004
    - WebSocket failed to connect

[Context]
    {
        "errorEvent": "[object Object]"
    }
```

[Stackblitz repro](https://stackblitz.com/edit/node-2swmxz?file=index.mjs)

## Description of bug

In this case the error name is clear enough to know what went wrong. But flagging because we might have other cases where we're putting objects in context and they're not getting stringified to anything useful.

**Comment by steveluscher** [comment]
Yeah, this is generally a ‘flaw,’ in big quotation marks. I didn't program in a way to exclude context properties from the serializer. They're not used in the message, so they're harmless, but it creates mental overhead – the kind that made you file this issue.

One reason that I didn't do this is that it would rely on a blocklist that would have to be built into the _production_ error serializer. We'd be forcing people to download that blocklist, and it would include every error in existence, whether you can even hit them or not. We already ship a [god awful allowlist of stuff](https://github.com/solana-labs/solana-web3.js/blob/a29bfeeb2119d99906a31fb1e5103d8ebf783ceb/packages/rpc-api/src/index.ts#L199-L376) to patch around deficiencies in the RPC, we don't want to do it here too.

**Comment by steveluscher** [comment]
I think the best we could do here is something like this:

```ts
new SolanaError(CODE, {
  foo: 'bar',
  __hideThisFromTheMessageFormatter: {
    baz: 'bat',
  },
})
```

…and then have the code merge `__hideThisFromTheMessageFormatter` into `e.context`, but otherwise not pass it to the message formatter.
