### ISSUE TITLE
Descriptive error message for rate limits

### ISSUE THREAD

**Issue by jim4067** [solana-labs/solana-web3.js#2592]
## Motivation
Getting this error message using the public endpoint

```bash
Error: failed to get recent blockhash: TypeError: fetch failed
    at Connection.getLatestBlockhash (/home/jimii/Documents/crew/test-web/node_modules/@solana/web3.js/src/connection.ts:4593:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async testConnection (/home/jimii/Documents/crew/test-web/src/main.ts:10:13)
```

## Example use case
When using RPC methods like `getLatestBlockhash` that might fail if a user is rate limited, it'll be useful to alert the user about that failure being because or a rate-limit

## Details

Having HTTP status codes in the error response/why the `getLatestBlockhash` method failed will be helpful in alerting the developer when an error arises from the RPC and not the code

**Comment by steveluscher** [comment]
We have this in the forthcoming version of web3.js. Take a look!

```ts
try {
  const latestBlockhash = await rpc.getLatestBlockhash().send();
} catch (e) {
  if (isSolanaError(e, SOLANA_ERROR__RPC__TRANSPORT_HTTP_ERROR)) {
    if (e.context.code === 429) {
      // We got rate limited!
    }
  }
}
```

I would love for you to build / rebuild whatever you're making using the new web3.js, and give us feedback!

https://github.com/solana-labs/solana-web3.js/releases/tag/tp3
