### ISSUE TITLE
Missing edge runtime support

### ISSUE THREAD

**Issue by etodanik** [solana-labs/solana-web3.js#2595]
Trying to compile code that uses `@solana/web3.js` to run on Vercel Edge or CloudFlare Workers will fail because the `rpc-websockets` dependency relies on a babel regenerator runtime for polyfills of async code.

Here's an example of a build error:
```

./node_modules/@babel/runtime/regenerator/index.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime 
Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation

Import trace for requested module:
./node_modules/@babel/runtime/regenerator/index.js
./node_modules/rpc-websockets/dist/lib/client.js
./node_modules/@solana/web3.js/lib/index.browser.esm.js


> Build failed because of webpack errors

```

**Comment by etodanik** [comment]
@steveluscher does it work with wallet adapter and SIWS?

**Comment by steveluscher** [comment]
Not yet. I didn't mention that because you were talking about Vercel Edge. I presumed you were writing a backend service (where neither Wallet Adapter nor SIWS are relevant).

**Comment by etodanik** [comment]
Well, for my immediate need (Actually I do SIWS, backend verification on an edge function) I ended up just using bs58 directly to encode/decode public keys. My only dependency was `PublicKey`. 

But it's nice to see the new preview version!

**Comment by steveluscher** [comment]
1. You should 1000% use the new web3.js for this backend service, and send us feedback!
2. We should fork `rpc-websockets` and build a version targeting EsNext. We could probably save a ton of bundle size by not consuming their downcompiled version wholesale.

**Comment by steveluscher** [comment]
Can you give v1.91.8 on Vercel Edge Runtime, @etodanik?

**Comment by praskoson** [comment]
> Can you give v1.91.8 on Vercel Edge Runtime, @etodanik?

Hi, I'm making a backend service where I'm thinking of using the edge runtime that would also be signing transactions. Google led me here, so I'm going to be trying the new web3.js. Any chance you can point me to any docs or instructions? And is it possible to use it in parallel with the old web3.js?

**Comment by steveluscher** [comment]
You definitely want to use the new web3.js if you're signing transactions @praskoson. Cheaper, faster, and ultimately lower latency for your signing service.

> Any chance you can point me to any docs or instructions?

Start [here](https://github.com/solana-labs/solana-web3.js/tree/master/packages/library#readme), and ask questions [here](https://sola.na/sse).
