### ISSUE TITLE
ws error shows 503 instead of 404

### ISSUE THREAD

**Issue by dwampa** [solana-labs/solana-web3.js#2683]
## Overview

I've tested the library on different RPCs and some of them require explicitly adding a WSS endpoint along the HTTPS one. If one does not explicitly add a WSS endpoint they will run into errors described below. 

## Steps to reproduce

1. Write a code with a method that requires ws connection (for example sendTransaction)
2. Use only HTTP RPC endpoint
3. Execute the code

Feel free to use the code below, it was made for testing purposes and includes the secret key.

```
const web3 = require('@solana/web3.js');
const rpcEndpoint = 'https://nd-111-531-680.p2pify.com/30ecedeba2bef81ada49a34b6d966556';

async function sendSol(fromSecretKey, toPublicKeyStr, amount) {
    const connection = new web3.Connection(rpcEndpoint);
    const fromKeypair = web3.Keypair.fromSecretKey(new Uint8Array(fromSecretKey));
    const toPublicKey = new web3.PublicKey(toPublicKeyStr);
    const transaction = new web3.Transaction().add(
        web3.SystemProgram.transfer({
            fromPubkey: fromKeypair.publicKey,
            toPubkey: toPublicKey,
            lamports: amount * web3.LAMPORTS_PER_SOL // Convert SOL to lamports
        })
    );
    try {
        const signature = await web3.sendAndConfirmTransaction(connection, transaction, [fromKeypair]);
        console.log('Transaction successful with signature:', signature);
    } catch (error) {
        console.error('Transaction failed:', error);
    }
}

// Example usage:
const fromSecretKey = [181, 243, 230, 124, 233, 187, 147, 136, 128, 130, 90, 198, 217, 39, 4, 158, 187, 252, 87, 12, 101, 228, 43, 49, 161, 155, 220, 102, 52, 12, 54, 159, 68, 119, 111, 76, 152, 123, 24, 132, 180, 77, 109, 186, 130, 200, 92, 200, 127, 84, 18, 206, 219, 220, 118, 25, 247, 181, 238, 68, 3, 57, 129, 194];
const toPublicKeyStr = 'tKeYE4wtowRb8yRroZShTipE18YVnqwXjsSAoNsFU6g';
const amount = 0.1; // Amount of SOL to send

// Call the function
sendSol(fromSecretKey, toPublicKeyStr, amount);

```

## Description of bug

The transaction is sent successfully, an example is 5g6uNCxhvYgPCrQo6sAyyAbGjrTR289WKAbxKacX5o3knbp3LRUJihH5119LVgE3cG7upUJ6uTvxgfnpQJ6hPtTe.

While in the logs I receive `ws error: Unexpected server response: 503`.

The expected error would be `ws error: Unexpected server response: 404`.

503 error is misleading as signalizes an issue with the destination, while the issue is with the correctness of WSS endpoint.

**Comment by steveluscher** [comment]
When `wsEndpoint` is not supplied, the library replaces the scheme `http(s)` -> `ws(s)`. Your URL as wss://nd-111-531-680.p2pify.com/30ecedeba2bef81ada49a34b6d966556 is not available, and returned a 503 Service Unavailable error. To be clear, this is p2pify.com returning this error.
