### ISSUE TITLE
I use vue to operate solana wen3.js. Why can’t I get the balance? Can anyone help me?

### ISSUE THREAD

**Issue by Dato-0208** [solana-labs/solana-web3.js#2708]
import { Connection, Keypair, PublicKey, clusterApiUrl } from "@solana/web3.js" 
const connection = new Connection(clusterApiUrl('devnet'), 'confirmed')
  let balance = await connection.getBalance(new PublicKey("ABEwKn1vy688qkJrLnAm5nVo9huaBYsWxdq1gskAYdbb"))

**Comment by Dato-0208** [comment]
![image](https://github.com/solana-labs/solana-web3.js/assets/87691763/ea2cff5a-5334-4792-9e49-436488ef84d6)

**Comment by Dato-0208** [comment]
![image](https://github.com/solana-labs/solana-web3.js/assets/87691763/8a1970c2-e18e-4140-b8b7-a9c38a93b1c1)

**Comment by Dato-0208** [comment]
![image](https://github.com/solana-labs/solana-web3.js/assets/87691763/9c59e99a-c38a-4bbc-ba88-dc0d6b64b1d3)

**Comment by Dato-0208** [comment]
![image](https://github.com/solana-labs/solana-web3.js/assets/87691763/71955230-af35-441f-83d5-e49c8e6aa074)

**Comment by irisroyaltyf** [comment]
你的地址在mainnet上有余额， dev上没余额啊

**Comment by Dato-0208** [comment]
> 你的地址在mainnet上有余额， dev上没余额啊

主网上的嘛  dev是指哪 可以详细点嘛

**Comment by Dato-0208** [comment]
> > 你的地址在mainnet上有余额， dev上没余额啊
> 
> 主网上的嘛 dev是指哪 可以详细点嘛

请问 我应该如何查询主网上的钱包余额呢  可以指点一下吗 开发网络上余额确实没有
