### ISSUE TITLE
WSS method onAccountChange doesn't support custom encoding

### ISSUE THREAD

**Issue by slyofzero** [solana-labs/solana-web3.js#2725]
## Motivation
The Solana RPC method `accountSubscribe` does provide a way to pass encoding so should the JS SDK

## Example use case
```ts
solanaConnection.onAccountChange(
  publicKey,
  (updatedProgramInfo, context) =>
    console.log(updatedProgramInfo.data),
  "confirmed"
);
```

The way this function has the commitment arguement it should have one for encoding too. Maybe just make the third arguement take an object with commitment and encoding as two fields of it.

Right now the data the above code logs is like -

```
<Buffer 06 00 00 00 00 00 00 00 fe 00 00 00 00 00 00 00 07 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00 09 00 00 00 00 00 00 00 09 00 00 00 00 00 00 00 01 00 ... 702 more bytes>
```

This data can't be much used and JSON data will be much more appreciated like the `accountSubscribe` method returns.

**Comment by NotoriousPyro** [comment]
You can just unpack the account using @solana/spl-token if its an ATA

Or you can just use AccountInfo?

I think this is not an enhancement. You are not using the library correctly.

You can see an example here that is using the properties of the account, such as lamports, here: https://gist.github.com/NotoriousPyro/c169f2dd455ce0fe5d2c6854cd0364e4
