### ISSUE TITLE
bug in ComputeBudgetProgram.setComputeUnitPrice 

### ISSUE THREAD

**Issue by amit221** [solana-labs/solana-web3.js#2738]
## Overview

sometimes when trying to swap I get an error

## Description of bug
Error in buy RangeError: The number 87612.5 cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at ComputeBudgetProgram.setComputeUnitPrice \@solana\web3.js\lib\index.cjs.js:9289:22)
    at addComputeBudget (node_modules\@raydium-io\raydium-sdk\lib\cjs\base\instrument.js:10:49)
    at @raydium-io\raydium-sdk\lib\cjs\common\web3.js:294:49
    at Generator.next (<anonymous>)
    at fulfilled @raydium-io\raydium-sdk\lib\cjs\common\web3.js:6:58)

**Comment by NotoriousPyro** [comment]
That isn't a bug. Fractional numbers are not integers. This is a bug in _your_ code
