### ISSUE TITLE
Cannot find module 'rpc-websockets/dist/lib/client'

### ISSUE THREAD

**Issue by uafrontender** [solana-labs/solana-web3.js#2762]
## Overview

I tried to use the Solana web3.js library in my dApp and encountered an issue where the module rpc-websockets/dist/lib/client could not be found. This error prevents the script from running.

## Steps to reproduce

1. Create a new NPM project:
`npm init -y`

2. Set "type": "module" in package.json.

3. Install the Solana web3.js library:
`npm install @solana/web3.js`

4. Create an index.js file with the following content:
```
import {} from "@solana/web3.js";
console.log("Hello world");
```

5. Run the script:
`node index.js`

## Description of bug
This results in the following error:

```
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
node:internal/modules/cjs/loader:1077
  const err = new Error(message);
              ^

Error: Cannot find module 'rpc-websockets/dist/lib/client'
Require stack:
- /path/to/project/node_modules/@solana/web3.js/lib/index.cjs.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/path/to/project/node_modules/@solana/web3.js/lib/index.cjs.js:17:32)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path/to/project/node_modules/@solana/web3.js/lib/index.cjs.js'
  ]
}

Node.js v18.18.0
```

Attempting to run a script that imports the @solana/web3.js library results in a MODULE_NOT_FOUND error for rpc-websockets/dist/lib/client. This issue seems to arise due to an incompatibility or missing dependency in the @solana/web3.js package, which relies on rpc-websockets.

**Comment by uafrontender** [comment]
**How to solve:**

Update imports in `node_modules/@solana/web3.js/lib/index.cjs.js` with

```
var RpcWebSocketCommonClient = require('rpc-websockets/dist/lib/client.cjs');
var WebsocketFactory = require('rpc-websockets/dist/lib/client/websocket.cjs');
```

**Comment by uafrontender** [comment]
Fixed by https://github.com/solana-labs/solana-web3.js/pull/2758

**Comment by plustokens** [comment]
The way you communicate about this issue and provide suggestions is perfect. Thank you!

Do you think we still need to fix rpc-websockets version to prevent any upcoming issues like this.

**Comment by uafrontender** [comment]
@plustokens thanks. As for me, I prefer to use strict versions of packages in package.json, like "5.35.1" and not "^5.35.1". I don't know how can we fix rpc-websockets in our case

**Comment by plustokens** [comment]
We can still fix it on our own project package.json file, developer using solana-web3.js version 1.91.9
```
npm install rpc-websockets@7.11.1
```

Else for previous solana-web3.js versions:
```
npm install rpc-websockets@7.11.0
```

**Comment by nvm-delete** [comment]
@uafrontender @plustokens 
I am also facing this problem, how can I fix this problem?

I am using Nextjs 12 Pages router with Electron.js and facing this problem, this same thing is working completely fine on my Nodejs project. But when I imported all the things into Nextjs it started bugging.


Thanks for Help in advance!

**Comment by uafrontender** [comment]
> @uafrontender @plustokens I am also facing this problem, how can I fix this problem?
> 
> I am using Nextjs 12 Pages router with Electron.js and facing this problem, this same thing is working completely fine on my Nodejs project. But when I imported all the things into Nextjs it started bugging.
> 
> Thanks for Help in advance!

Check what package has problem with rpc-websockets imports. If it's solana-web3.js, just update to latest version
