### ISSUE TITLE
JSON-RPC batching and request retries

### ISSUE THREAD

**Issue by lithdew** [solana-labs/solana-web3.js#2770]
## Motivation

I noticed in the library README for the experimental SDK that two of the motivations for the API design are:

> - Solana developer ‘epicfaace’ wanted first-class support for automatic time-windowed batching in the RPC transport. https://github.com/solana-labs/solana/pull/23628.
> - Multiple folks have expressed the need for custom retry logic for failed requests or transactions. https://github.com/solana-labs/solana/pull/11811 and https://github.com/solana-labs/solana-web3.js/issues/1041 attempting to modify retry logic to suit their individual use cases.

However, it is somewhat rather unclear on how i.e. batching or retrying can be implemented with the current experimental SDK.

1. How do I have the HTTP transport automatically merge together specific multiple JSON-RPC payloads into a batch request?
2. How do I synchronously (explicitly) invoke a batch JSON-RPC request with multiple JSON-RPC payloads crafted via. the SDK?
3. How do I pass individual timeouts/retry options for a single scalar/JSON-RPC request via. the SDK?

## Example use case

I currently manually perform fetch calls myself to perform explicit batch JSON-RPC requests. This, however, is error-prone as it would require types and validation to be handled by myself (i.e. how do I handle the case that a response field overflows Number.MAX_SAFE_INTEGER?).

```ts
export async function getTokenBalances(ownerPublicKey: string) {
  const sol = {
    jsonrpc: "2.0",
    id: 0,
    method: "getAccountInfo",
    params: [
      ownerPublicKey,
      { commitment: "confirmed", encoding: "jsonParsed" },
    ],
  };

  const usdc = {
    jsonrpc: "2.0",
    id: 1,
    method: "getTokenAccountsByOwner",
    params: [
      ownerPublicKey,
      {
        mint: USDC_TOKEN_PUBLIC_KEY,
      },
      {
        commitment: "confirmed",
        encoding: "jsonParsed",
      },
    ],
  };

  const like = {
    jsonrpc: "2.0",
    id: 2,
    method: "getTokenAccountsByOwner",
    params: [
      ownerPublicKey,
      {
        mint: LIKE_TOKEN_PUBLIC_KEY,
      },
      {
        commitment: "confirmed",
        encoding: "jsonParsed",
      },
    ],
  };

  const request = [sol, usdc, like];

  const response = await fetch(SOLANA_SERVER_RPC_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(request),
  });
  if (!response.ok) {
    throw new Error(`RPC request failed: ${response.statusText}`);
  }

  const json = await response.json();
  if (!checkSchema(getTokenBalancesResponse, json)) {
    throw new Error(`Malformed RPC response: ${JSON.stringify(json)}`);
  }

  const balances = {
    sol: BigInt(json[0].result.value?.lamports ?? 0),
    usdc: json[1].result.value.reduce(
      (
        acc,
        {
          account: {
            data: {
              parsed: { info },
            },
          },
        },
      ) => {
        if (info.state !== "initialized") {
          return acc;
        }
        return acc + BigInt(info.tokenAmount.amount);
      },
      BigInt(0),
    ),
    like: json[2].result.value.reduce(
      (
        acc,
        {
          account: {
            data: {
              parsed: { info },
            },
          },
        },
      ) => {
        if (info.state !== "initialized") {
          return acc;
        }
        return acc + BigInt(info.tokenAmount.amount);
      },
      BigInt(0),
    ),
  };

  return balances;
}
```

## Details

Preliminarily, the only way I can imagine having such a granularity of level of options for retries/timeouts is to expose custom options on `.send()`. The custom options can be provided via the `RpcTransport` interface.

To support explicit batching, I can imagine a syntax i.e:

```ts
rpc.batch(rpc => [
  rpc.getAccountInfo(),
  rpc.getTokenAccountsByOwner(),
  rpc.getTokenAccountsByOwner(),
]).send()
```

The batch method can either be directly exposed on top of the `Rpc` interface, or otherwise be provided as a separate exported helper that takes in a `Rpc` instance.

**Comment by steveluscher** [comment]
Happy to answer this over at Stack Exchange. Comment with a link to your question when you post it!
