### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated. 

### ISSUE THREAD

**Issue by arose26** [solana-labs/solana-web3.js#2781]
## Overview
solana/web3.js@1.92.2 depends on node-fetch@2.7.0 which triggers the punycode warning with the latest node (21.7.3)

## Steps to reproduce

Use any of the @solana/web3.js functions which do a fetch. 
`node --trace-deprecation filename.js` gives the exact code line which triggers the warning.

## Description of bug
The code `@solana/web3.js/node_modules/whatwg-url/lib/url-state-machine.js:2:18`
Triggers a warning:
`(node:9843) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.`
The latest versions of node-fetch have solved this issue. Need to update dependency to a version higher than 2.7.0.

**Comment by steveluscher** [comment]
We can't go to the 3.x line of `node-fetch` because of their decision to go ESM-only.

This problem will go away completely in the 2.x line of `@solana/web3.js` because we don't use `node-fetch` at all.

Read more here, and try it out! https://github.com/solana-labs/solana-web3.js/releases/tag/tp3
