### ISSUE TITLE
issue faced

### ISSUE THREAD

**Issue by dinesh-10123maticz** [solana-labs/solana-web3.js#2782]
## Overview

when ever i install solana/web3.js ,i faced this error.

## Steps to reproduce

 no such file or directory, /node_modules/@solana/web3.js/dist/index.browser.js

## Description of bug

your all npm version are only bug

**Comment by GauravAgarwal009** [comment]
did you try installing the the package ???

command: npm i @solana/web3.js

**Comment by dinesh-10123maticz** [comment]
i am installed that package . this error is come when i import inside module
