### ISSUE TITLE
 Class extends value /{PATH}/ is not a constructor or null  at ./node_modules/@solana/web3.js/lib/index.browser.esm.js

### ISSUE THREAD

**Issue by GauravAgarwal009** [solana-labs/solana-web3.js#2783]
Getting this error when running the react application 

 Class extends value /static/media/client.98866d67.cjs is not a constructor or null
    at ./node_modules/@solana/web3.js/lib/index.browser.esm.js

<img width="1438" alt="Screenshot 2024-06-06 at 6 03 04 PM" src="https://github.com/solana-labs/solana-web3.js/assets/65541324/7deb77c1-02a0-4d7e-ba69-4342a5ed0efa">

Node version: v16.20.2
NPM version: 8.19.4

**Comment by steveluscher** [comment]
You're using Create React App, aren't you?

Solution [here](https://github.com/elpheria/rpc-websockets/issues/163#issuecomment-2150791994)!
