### ISSUE TITLE
`setTransactionMessageFeePayerSigner` does not accept a `CompilableTransactionMessage` as input

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#2854]
```
Argument of type 'CompilableTransactionMessage' is not assignable to parameter of type '(Readonly<{ instructions: readonly IInstruction<string, readonly (IAccountMeta<string> | IAccountLookupMeta<string, string>)[]>[]; version: TransactionVersion; }> & TransactionMessageWithBlockhashLifetime) | (ITransactionMessageWithFeePayer<...> & ... 1 more ... & TransactionMessageWithBlockhashLifetime)'.
  Type 'Readonly<{ instructions: readonly IInstruction<string, readonly (IAccountMeta<string> | IAccountLookupMeta<string, string>)[]>[]; version: TransactionVersion; }> & ITransactionMessageWithFeePayer<...> & TransactionMessageWithDurableNonceLifetime<...>' is not assignable to type '(Readonly<{ instructions: readonly IInstruction<string, readonly (IAccountMeta<string> | IAccountLookupMeta<string, string>)[]>[]; version: TransactionVersion; }> & TransactionMessageWithBlockhashLifetime) | (ITransactionMessageWithFeePayer<...> & ... 1 more ... & TransactionMessageWithBlockhashLifetime)'.
    Type 'Readonly<{ instructions: readonly IInstruction<string, readonly (IAccountMeta<string> | IAccountLookupMeta<string, string>)[]>[]; version: TransactionVersion; }> & ITransactionMessageWithFeePayer<...> & TransactionMessageWithDurableNonceLifetime<...>' is not assignable to type 'ITransactionMessageWithFeePayer<string> & Readonly<{ instructions: readonly IInstruction<string, readonly (IAccountMeta<string> | IAccountLookupMeta<string, string>)[]>[]; version: TransactionVersion; }> & TransactionMessageWithBlockhashLifetime'.
      Type 'Readonly<{ instructions: readonly IInstruction<string, readonly (IAccountMeta<string> | IAccountLookupMeta<string, string>)[]>[]; version: TransactionVersion; }> & ITransactionMessageWithFeePayer<...> & TransactionMessageWithDurableNonceLifetime<...>' is not assignable to type 'TransactionMessageWithBlockhashLifetime'.
        Types of property 'lifetimeConstraint' are incompatible.
          Type 'Readonly<{ nonce: Nonce<string>; }>' is missing the following properties from type 'Readonly<{ blockhash: Blockhash; lastValidBlockHeight: bigint; }>': blockhash, lastValidBlockHeight
```

[Sandbox link](https://codesandbox.io/p/sandbox/solana-web3-js-2384-9xxgqq?file=%2Fsrc%2Findex.ts%3A10%2C42&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxvconq700063b6ntqsmnjuc%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxvconq700023b6n7tdvius6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxvconq700033b6nc4nze03y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxvconq700053b6nsfvf9kx2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxvconq700023b6n7tdvius6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxvconq700013b6nlqg1nm6b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A42%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A42%257D%255D%257D%255D%252C%2522id%2522%253A%2522clxvconq700023b6n7tdvius6%2522%252C%2522activeTabId%2522%253A%2522clxvconq700013b6nlqg1nm6b%2522%257D%252C%2522clxvconq700053b6nsfvf9kx2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxvconq700043b6ny7eoiutn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxvconq700053b6nsfvf9kx2%2522%252C%2522activeTabId%2522%253A%2522clxvconq700043b6ny7eoiutn%2522%257D%252C%2522clxvconq700033b6nc4nze03y%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxvconq700033b6nc4nze03y%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by lorisleiva** [comment]
This error seems to also occur with the `setTransactionMessageFeePayer` function.

```ts
import {
  CompilableTransactionMessage,
  setTransactionMessageFeePayer,
} from "@solana/web3.js";

const payer = null as unknown as Address;
const compilableMessage = null as unknown as CompilableTransactionMessage;

setTransactionMessageFeePayer(payer, compilableMessage);
```

Whilst `CompilableTransactionMessage` satisfies `BaseTransactionMessage`, I think TypeScript isn't able to resolve infer the `TTransaction` type parameter properly using the following signature:

```ts
export function setTransactionMessageFeePayer<
    TFeePayerAddress extends string,
    TTransaction extends BaseTransactionMessage,
>(
    feePayer: Address<TFeePayerAddress>,
  transaction: TTransaction | (ITransactionMessageWithFeePayer<string> & TTransaction),
): ITransactionMessageWithFeePayer<TFeePayerAddress> & TTransaction;
```

The following change seems to make TypeScript happy but I guess by doing this we are no longer telling TS to remove the existing `ITransactionMessageWithFeePayer` flag if any exists.

```diff
  export function setTransactionMessageFeePayer<
      TFeePayerAddress extends string,
      TTransaction extends BaseTransactionMessage,
  >(
      feePayer: Address<TFeePayerAddress>,
-     transaction: TTransaction | (ITransactionMessageWithFeePayer<string> & TTransaction),
+     transaction: TTransaction,
  ): ITransactionMessageWithFeePayer<TFeePayerAddress> & TTransaction;
```

**Comment by steveluscher** [comment]
> EDIT: perhaps something like this could do the trick?

Yeah, that 100% works. I'll PR that.
