### ISSUE TITLE
Eliminate deprecated RPC methods

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#2859]
The following deprecated methods are [being removed in Agave 2.0](https://github.com/anza-xyz/agave/pull/1886):

* confirmTransaction
* getSignatureStatus
* getSignatureConfirmation
* getTotalSupply
* getConfirmedSignaturesForAddress
* getConfirmedBlock
* getConfirmedBlocks
* getConfirmedBlocksWithLimit
* getConfirmedTransaction
* getConfirmedSignaturesForAddress2
* getRecentBlockhash
* getFees
* getFeeCalculatorForBlockhash
* getFeeRateGovernor
* getSnapshotSlot
* getStakeActivation

Clean all references and code for these from web3.js.

**Comment by steveluscher** [comment]
I've started to have a few second thoughts here.

1. Responsibly removing these methods would require a major version bump, which would take legacy web3.js to 2.0.
2. The new library that we _actually_ intend on releasing as web3.js 2.0 already has these methods gone.

I think maybe we just cut our losses for legacy, and close #2859 by releasing the new library. Two birds, one stone.

**Comment by sekaieth** [comment]
> I've started to have a few second thoughts here.
> 
> 1. Responsibly removing these methods would require a major version bump, which would take legacy web3.js to 2.0.
> 2. The new library that we _actually_ intend on releasing as web3.js 2.0 already has these methods gone.
> 
> I think maybe we just cut our losses for legacy, and close #2859 by releasing the new library. Two birds, one stone.

Hi Steve,

Is there an estimate on when the new library will be released?  Or, if it is already released, can you help me with a link?

**Comment by steveluscher** [comment]
Hey @sekaieth; you can follow along with the Release Candidates [here](https://github.com/solana-labs/solana-web3.js/releases/tag/v2.0.0-rc.1). It's looking like the final will come shortly after Solana Breakpoint this year.

**Comment by sekaieth** [comment]
Thanks!  

I'm on a wallet team.  Will the Agave 2.0 fork break my application if we don't upgrade this sdk immediately?

**Comment by steveluscher** [comment]
The versions aren't related. `@solana/web3.js` 2.0 breaks all APIs from the application perspective, not the network perspective. There are no RPC API changes between the network at 1.18 or 2.0, _except_ that some long-deprecated methods have been permanently removed.

**Comment by sekaieth** [comment]
Thanks!

**Comment by steveluscher** [comment]
This is done in 2.0. We're not going to remove them in the 1.x line.
