### ISSUE TITLE
 Module `assert` does not exist in the Haste module map

### ISSUE THREAD

**Issue by YukunLee** [solana-labs/solana-web3.js#287]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios) with error:(Unable to resolve module `assert` from `/Users/lee/Desktop/React/node_modules/@solana/web3.js/lib/index.cjs.js`: Module `assert` does not exist in the Haste module map

**Comment by mvines** [comment]
Hi thanks for reporting this.   Can you please share more details on how to reproduce this issue?

**Comment by YukunLee** [comment]
Running on iOS  with React Native, 'yarn add @solana/web3.js' and  import web3 from '@solana/web3.js',then arise the issue.

    "dependencies": {
        "@solana/web3.js": "^0.14.18",
        "react": "16.8.3",
        "react-native": "^0.59.4"
    }
import  web3 from '@solana/web3.js';

I'm a beginner.  Feel guilty for causing  your trouble.

**Comment by mvines** [comment]
Oh React Native.  We don't currently support React Native.  It would be possible to add support RN but I imagine it would be a bit of work, possibly with adding some native bindings for the crypto libraries we make use of

**Comment by YukunLee** [comment]
I see,Thank you very much for  your answer.

**Comment by mvines** [comment]
Next steps on this issue would be to investigate adding React Native support by somebody who is motivated to do so :)

**Comment by bachlongkocanh** [comment]
Follow https://gist.github.com/bachlongkocanh/1617f339c779db36b6f1528dc68b5d96 to install web3, ethers, solana/web3 for React Native.

**Comment by steveluscher** [comment]
We're now compatible with React Native!
