### ISSUE TITLE
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?) when importing @solana/web3.js

### ISSUE THREAD

**Issue by rixhy-cyd** [solana-labs/solana-web3.js#2916]
import { SystemProgram } from '@solana/web3.js';

doing this throws me 
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?) 
on the terminal 

No luck trying this: https://solana.stackexchange.com/questions/4077/bigint-failed-to-load-bindings-pure-js-will-be-used-try-npm-run-rebuild-whe

How to fix it.

**Comment by buffalojoec** [comment]
https://github.com/solana-labs/solana-web3.js/issues/2328
