### ISSUE TITLE
Uncaught rejection on RPC request error in packages/library-legacy/src/connection.ts:1679

### ISSUE THREAD

**Issue by YipCyun** [solana-labs/solana-web3.js#2933]
## Overview

There is an issue in the packages/library-legacy/src/connection.ts file at line 1679. Whenever an RPC request encounters an error, it results in an uncaught rejection. This means that even if the outer call is wrapped in a try-catch block, the error cannot be caught and handled properly.

## Steps to reproduce

Make an RPC request using the solana-web3.js library.
Force an error condition for the request.
Wrap the request call in a try-catch block.
Observe that the error is not caught by the try-catch block and results in an uncaught rejection.

## Description of bug

There is an issue in the packages/library-legacy/src/connection.ts file at line 1679. Whenever an RPC request encounters an error, it results in an uncaught rejection. This means that even if the outer call is wrapped in a try-catch block, the error cannot be caught and handled properly.

## Expected Behavior:
The error should be caught and handled properly within the try-catch block surrounding the RPC request call.

## Actual Behavior:
The error results in an uncaught rejection, bypassing the try-catch block.

## Proposed Solution:
Add a try-catch block around the RPC request in packages/library-legacy/src/connection.ts at line 1679 to handle errors properly and prevent uncaught rejections.

**Comment by buffalojoec** [comment]
Hm, strange, I might be missing something obvious, but line 1679 _is_ in a try-catch block.

https://github.com/solana-labs/solana-web3.js/blob/c1c217262c31b2752b839bad8789bd9dd24adc55/packages/library-legacy/src/connection.ts#L1647-L1684

```ts
import { Connection } from "@solana/web3.js";

async function main() {

    const connection = new Connection("https://api.devnet.solana.com");

    try {
        const res = await connection.getBlockTime(Number.MAX_VALUE);
    } catch (error) {
        console.error("o no");
    }
}

main();
```

> Force an error condition for the request.

I think maybe you need to be more specific about the type/location of the error condition.

**Comment by YipCyun** [comment]
hi, sorry maybe we are using the different version, the line I meant in your version would be 1676 to 1680:
```typescript
      if (res.ok) {
        callback(null, text);
      } else {
        callback(new Error(`${res.status} ${res.statusText}: ${text}`));
      }
```
the `callback` func above may get rejected so better to have a try catch here

**Comment by steveluscher** [comment]
`callback` is not ours, it comes from the `jayson` dependency, [here](https://github.com/tedeh/jayson/blob/master/lib/client/browser/index.js#L102-L104).

If `callback` is throwing an error, it's throwing it from somewhere in here:

https://github.com/tedeh/jayson/blob/master/lib/client/browser/index.js#L117-L163

Can you get us a sample stacktrace so we can know where?

**Comment by YipCyun** [comment]
thank you @steveluscher .
yup we will establish connections and do some requests like, for example, getLatestBlockhash. The uncaught rejections on RPC request occur and we cannot catch them in our codes if somehow the connection met some error.
```
demo_app:unhandle rejection'reason: Error: 500 Internal Server Error: {"error": {"code": -32603' "message": "internal server error"}' "jsonrpc": "2.0"'"id":"658310f3-5ce4-xxxx-xxxx-42bc24cfc0fc"' "project": "16dfxxxxxxxxxxxxxxxxxxxxxxxxxa3a189"}    at ClientBrowser.callServer (/app/node_modules/@solana/web3.js/src/connection.ts:1649:18)    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by steveluscher** [comment]
Can you show me the call site where you make the request, and try to catch any errors?

**Comment by steveluscher** [comment]
To put a fine point on it, here is an RPC request which always results in an HTTP 403 error. You can see that try/catch works as expected.

[Codesandbox repro](https://codesandbox.io/p/sandbox/catching-rpc-errors-in-solana-web3-js-gvlp88?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyomwhta00063b6gfcidv3te%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyomwht900023b6g3j7u3yod%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyomwhta00033b6ghrdqils3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyomwhta00053b6g4f91s1rc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyomwht900023b6g3j7u3yod%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyomwht900013b6g6nabdibd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%257D%255D%252C%2522id%2522%253A%2522clyomwht900023b6g3j7u3yod%2522%252C%2522activeTabId%2522%253A%2522clyomwht900013b6g6nabdibd%2522%257D%252C%2522clyomwhta00053b6g4f91s1rc%2522%253A%257B%2522id%2522%253A%2522clyomwhta00053b6g4f91s1rc%2522%252C%2522activeTabId%2522%253A%2522clyomzvgf002p3b6ggze8b1j2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyomwhta00043b6gvw30kveq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522isCloud%2522%253Afalse%252C%2522id%2522%253A%2522clyomzvgf002p3b6ggze8b1j2%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clyomwhta00033b6ghrdqils3%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyomwhta00033b6ghrdqils3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Show us what's different about your call that's causing the error to bubble up uncaught.

**Comment by steveluscher** [comment]
Will reopen this when we get a repro case from @YipCyun.

**Comment by YipCyun** [comment]
thank you so much for the reply @steveluscher , let me check on my side again.
