### ISSUE TITLE
Could not resolve rpc-websockets/dist/lib/client" when using Solana Web3 in React application

### ISSUE THREAD

**Issue by rtomas** [solana-labs/solana-web3.js#2951]
## Overview

I am encountering an issue when using the Solana Web3 library in my React application. The application throws an error during the build process.

## Steps to reproduce

trying to implement a very simple version of "@solana/web3.js": "1.95",

## Description of bug
![image](https://github.com/user-attachments/assets/2098e3d6-34d2-4709-b050-92b61a3b1278)

## Solution
Install an older version of rpc-websockets (instead of 7.11.2 that is using @solana/web3.js)
`pnpm i rpc-websockets@7.11.0`

**Comment by steveluscher** [comment]
Look in your lockfile to determine which version of `rpc-websockets` is actually installed. You're going to have a bad version in there. You need all instances of it to be `>=7.11.1`.

Duplicate: #2777.
