### ISSUE TITLE
[Docs] How to Retrieve Token Metadata in 2024?

### ISSUE THREAD

**Issue by mahnunchik** [solana-labs/solana-web3.js#2979]
## Motivation

It would be nice to have official documentation for: what is the simplest way to retrieve token metadata such as name, symbol, and decimals in 2024?

* The `@solana/spl-token-registry` is deprecated and lacks new tokens.
* The `@metaplex-foundation/mpl-token-metadata` has been updated from version 2 to version 3, resulting in complex dependencies to obtain minimal token information.

## Details

For example, tokens:
* `2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo` - PYUSD
* `Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB` - USDT

**Comment by steveluscher** [comment]
You might like to encourage an answer on this topic on Stack Exchange, or to ask for an addition to https://github.com/solana-developers/solana-cookbook.

**Comment by mahnunchik** [comment]
@steveluscher thanks 

https://github.com/solana-developers/solana-cookbook/issues/611
