### ISSUE TITLE
Update package readmes to point at rc instead of @experimental

### ISSUE THREAD

**Issue by mcintyre94** [solana-labs/solana-web3.js#3007]
I just noticed that our package readmes all point at `@experimental`, eg from the accounts one:

> This package contains types and helper methods for representing, fetching and decoding Solana accounts. It can be used standalone, but it is also exported as part of the Solana JavaScript SDK [@solana/web3.js@experimental](https://github.com/solana-labs/solana-web3.js/tree/master/packages/library).

We should probably change them all to `@rc` at some point

**Comment by steveluscher** [comment]
Some point very soon after #3011.
