### ISSUE TITLE
createAccountWithSeed duplicates keys unnecessarily 

### ISSUE THREAD

**Issue by amiryadid-fb** [solana-labs/solana-web3.js#3118]
In `createAccountWithSeed` there is a check whether the `fromPubkey` and the `basePubkey` are the same key to determine whether we need to add the `basePubKey` to the keys array.
In this method, the key objects are being compared but since they are objects the thing that is compared is their reference, meaning it will only resolve to `false` when they are exactly the same object.
This causes issues if the instruction is being decoded and later recompiled to a new transaction, as the public keys are the same but the objects are not, resolving this check incorrectly.

Solution suggested: compare the actual value of the keys, and not the objects

https://github.com/solana-labs/solana-web3.js/blob/4124b49fa74214dd46e0e60b6d2ecff3349283ba/src/programs/system.ts#L863

**Comment by buffalojoec** [comment]
Thanks! See linked PR.
