### ISSUE TITLE
Types have separate declarations of a private property 'getCancellationPromise'.

### ISSUE THREAD

**Issue by developer-otto** [solana-labs/solana-web3.js#3138]
node v20.15.1
pnpm V8.14.0
next v14.0.4
@solana/web3.js v1.95.3

When I execute pnpm build it throws the error:
<img width="1713" alt="image" src="https://github.com/user-attachments/assets/a2f06957-9486-41b1-a32f-24117cf6e453">

**Comment by steveluscher** [comment]
This is owing to the fact that you have two copies of `@solana/web3.js` in your project (search term: dual package hazard). Check the lockfile of your project to figure out why, and where the second version is coming from.

**Comment by developer-otto** [comment]
Just installing @solana/web3.js and @project-serum/anchor in my project will cause this problem. How can I solve it?

**Comment by Manice18** [comment]
> Just installing @solana/web3.js and @project-serum/anchor in my project will cause this problem. How can I solve it?

I was having the same issue with yarn so I just removed the yarn lock file and did a fresh install with npm.
It seems to be working fine now.
