### ISSUE TITLE
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)

### ISSUE THREAD

**Issue by shankiflang** [solana-labs/solana-web3.js#3325]
Hey guys,

I open an other issue cause I still have this issue on windows : https://github.com/solana-labs/solana-web3.js/issues/2328#issue-2189987020

Has anyone managed to solve the problem?

**Comment by steveluscher** [comment]
The new version of web3.js (2.0) will no longer use `bigint-buffer`. In the meantime, seek a solution here: https://solana.stackexchange.com/questions/4077/bigint-failed-to-load-bindings-pure-js-will-be-used-try-npm-run-rebuild-whe
