### ISSUE TITLE
add svelte wallet example

### ISSUE THREAD

**Issue by xcaptain** [solana-labs/solana-web3.js#3408]
I want to use `web3.js` v2 in my sveltekit app, but you only provide react example app, could you provide an official svelte wallet example app?

I have originally posted my question at https://github.com/anza-xyz/wallet-adapter/issues/1027 but no one answers. So I followed the react demo app made a simple sveltekit app.

source code: https://github.com/xcaptain/solana-wallet-demo
demo website: https://solana-wallet-demo.pages.dev/

If welcome, I can make a pull request to submit this demo app

**Comment by xcaptain** [comment]
https://github.com/solana-labs/solana-web3.js/blob/3ea78d8c49a52460198cf82749ca2b932d8e5215/examples/react-app/src/context/SelectedWalletAccountContext.tsx#L40-L44

The localStorage in the react-app is not working, because `useWallets()`  doesn't returns `accounts`

![image](https://github.com/user-attachments/assets/3e48f955-390d-4e7a-90ae-f3b4c5f7886b)

so everytime refresh browser, I will be recgonized as not connected

![image](https://github.com/user-attachments/assets/fac6cce5-f653-49c3-ad82-34fad1319c6c)

@steveluscher can you take a look at this?

**Comment by xcaptain** [comment]
I have a workaround to solve the problem when loading walletAccount from localStorage wallet accounts is empty.


https://github.com/xcaptain/solana-wallet-demo/blob/281a8d421aeeb26307cd225706ce2bc3ab4e7988/src/routes/%2Bpage.svelte#L138-L150

this walletAccount can't be used to sign and send transaction, so to send transaction, must connect again

https://github.com/xcaptain/solana-wallet-demo/blob/281a8d421aeeb26307cd225706ce2bc3ab4e7988/src/routes/%2Bpage.svelte#L247-L251

**Comment by steveluscher** [comment]
1. This GitHub is not suitable for technical support. I will paste in the link for that at the bottom – please re-ask your question about wallet autoconnecting there, paste the link here, and I will answer it.
2. The `@solana/web3.js` repository is not meant to warehouse a compendium of framework examples, but you should feel free to make one, and to find the most authoritative [awesome- list](https://github.com/search?q=awesome-solana&type=repositories) that you can, to have it added there! If you find a particularly good list of example apps, consider sending us a pull request to have it _linked_ to from our `examples/README.md`.

**Comment by xcaptain** [comment]
Well, 3 days ago it's a question because I don't know how to implement a wallet button in svelte, but now I know it and made a workable demo app and I think there is a bug in the react-app because localStorage is not working, after refresh browser my last used wallet account doesn't show up.

**Comment by steveluscher** [comment]
> …I think there is a bug in the react-app because localStorage is not working, after refresh browser my last used wallet account doesn't show up.

It is a bug, but not in the way you might think. Throw up a question on Stack Exchange, and I'll answer it there so that the entire community of Solana developers can benefit from the answer going in to the future.

**Comment by xcaptain** [comment]
I posted my question at: https://solana.stackexchange.com/questions/17070/how-to-implement-a-wallet-button-using-web3-js-v2

I have some basic understandings to web3.js, but need someone to help me sort out my thoughts

**Comment by steveluscher** [comment]
That post asks too many questions at once. If you ask one question at a time, it's more likely to get answered. If you want to post one _just_ asking why `accounts` is empty for a previously connected wallet upon refresh, I'll be happy to lay out the answer there.

Sorry to be pedantic, and not just answer it here. It's important.
