### ISSUE TITLE
Add getHealth method

### ISSUE THREAD

**Issue by DaniSchenk** [solana-labs/solana-web3.js#3416]
## Motivation

I monitor connected services and third parties in my application. So I would like to monitor my RPC node connection. 

## Example use case

```ts
// await rpc.getHealth()

// report unhealthy state in case of 
  // connectivity issues (e.g. 5xx)
  // unhealthy response
```

## Details

[According to the docs](https://solana.com/docs/rpc/http/gethealth) there's a health endpoint. I suggest providing it like `Connection.getHealth()` - similar to all other provided endpoints.

**Comment by steveluscher** [comment]
This API method is available in `@solana/web3.js` version 2.0. https://github.com/solana-labs/solana-web3.js/blob/d0adee1582368bcd6ae636af69a3bd019e23d9c8/packages/rpc-api/src/getHealth.ts#L3-L11

If there are barriers to upgrading, let us know what those are in a separate issue!

**Comment by DaniSchenk** [comment]
Oh! I missed the new RC versions, sorry. That's helpful, thx for the hint 👍
