### ISSUE TITLE
setComputeUnitPrice param asks for microlamports when in reality the function requires lamports/

### ISSUE THREAD

**Issue by mrpathfindr** [solana-labs/solana-web3.js#3434]
## Overview

Trying to set setComputeUnitPrice

```ts
ComputeBudgetProgram.setComputeUnitPrice({
    microLamports: priority_fee, 
});
```

## Steps to reproduce

Try to make a transaction and add an instruction

```ts
ComputeBudgetProgram.setComputeUnitPrice({
    microLamports: priority_fee, 
});
```
  
  The value will ask you for the amount you want to set in micro lamports. 
  
  But this is not correct as the actual result of the transaction shows to use lamports
  
  I.e If I want to set 0.01 sol as unit price I need to send $$0.01 {\times} 10^9$$ not $$10^{15}$$

## Description of bug

The wrong term has been used as the parameter for 

```ts
ComputeBudgetProgram.setComputeUnitPrice({
    microLamports: priority_fee, 
});
```  
  
It should be
  
  
```ts
ComputeBudgetProgram.setComputeUnitPrice({
   lamports: priority_fee, 
});
```

**Comment by steveluscher** [comment]
> But this is not correct as the actual result of the transaction shows to use lamports

Can you explain this further?

Related: https://github.com/anza-xyz/agave/blob/b7bbe36918f23d98e2e73502e3c4cba78d395ba9/sdk/src/compute_budget.rs#L52-L55

**Comment by steveluscher** [comment]
Feel free to reopen this if you are convinced that there is a bug here. Be aware that the value in question is measured in microlamports per compute unit. That is if you set `10` and the transaction consumes 100,000 compute units, the priority fee paid will be one Lamport.
