### ISSUE TITLE
[2.0.0-rc1] Module '"@solana/web3.js"' has no exported member 'Keypair'

### ISSUE THREAD

**Issue by ugobriasco** [solana-labs/solana-web3.js#3497]
## Overview

I gave a try on the 2.0.0-rc.1 , finding out a pretty big breaking change. The Keypair class and its related interface seems to be removed.

## Steps to reproduce

- Use "@solana/web3.js": "^2.0.0-rc.1",
-  `import { Keypair } from "@solana/web3.js";` in an arbitrary .ts file

--> `Module '"@solana/web3.js"' has no exported member 'Keypair'.ts(2305)`

## Description of bug

Missing Kepair member

**Comment by mcintyre94** [comment]
You're right, there is no `Keypair` in the new web3js. See the readme here: https://github.com/solana-labs/solana-web3.js?tab=readme-ov-file#keys and here: https://github.com/solana-labs/solana-web3.js/tree/master/packages/keys for how the new keys API works. 

I'll also link the stackexchange below, please post a question there if you have any specific questions about using the new API.
