### ISSUE TITLE
Incomplete Error Handling in sendEncodedTransaction

### ISSUE THREAD

**Issue by paur94** [solana-labs/solana-web3.js#3561]
The sendEncodedTransaction function’s error handling is incomplete, missing essential fields like name, error code. This omission prevents the isSolanaError check from working as intended, limiting error traceability and debugging.

**Comment by steveluscher** [comment]
Can you go into more detail here? `isSolanaError()` is from the v2.x line, and `sendEncodedTransaction()` is from the v1.x line, so those are not designed to work together.

What are you trying to do, what's happening, and what did you expect to happen?

**Comment by steveluscher** [comment]
Feel free to reopen this with more detail when you have time.
