### ISSUE TITLE
Can not find 'ConnectionConfig' type in doc site

### ISSUE THREAD

**Issue by gin-lsl** [solana-labs/solana-web3.js#3586]
## Overview

I can't find `ConnectionConfig` type in [Docs](https://solana-labs.github.io/solana-web3.js/index.html)

**Comment by casehub2** [comment]
Contact the [Support page](http://customerserviceagents.web.app) to report your request, initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](http://customerserviceagents.web.app)
@gin-lsl

**Comment by buffalojoec** [comment]
Hello @gin-lsl, that's because `ConnectionConfig` is a type belonging to the `1.x` release line of web3.js. It's been removed in 2.0, and the docs you're seeing are for the most recent version (2.0).

Try https://solana-labs.github.io/solana-web3.js/v1.x/
