### ISSUE TITLE
`createSolanaRpcSubscriptions` in a browser extension throws error

### ISSUE THREAD

**Issue by liepauls** [solana-labs/solana-web3.js#3652]
## Overview

`createSolanaRpcSubscriptions` in a browser extension throws error `Cannot read properties of undefined (reading 'addEventListener')
`

## Steps to reproduce

1. Create a browser extension
2. Run something along the lines of: 
```js
const rpc = createSolanaRpc('https://api.devnet.solana.com')
const rpcSubscriptions = createSolanaRpcSubscriptions('wss://api.devnet.solana.com')

const sendAndConfirmTransaction = sendAndConfirmTransactionFactory({
  rpc,
  rpcSubscriptions,
})

const signedTx = ...

sendAndConfirmTransaction(signedTx, { commitment: 'confirmed' })
```

Please, let me know if a more detailed info on how to reproduce the error is needed 🤞 

## Description of bug

When `sendAndConfirmTransaction` is called, `Cannot read properties of undefined (reading 'addEventListener')` is thrown.

The error probably comes from [here](https://github.com/solana-labs/solana-web3.js/blob/2d17620b60e47a3a09cf25a843416846e8a7c56f/packages/rpc-subscriptions/src/rpc-subscriptions-autopinger.ts#L51).

**Comment by steveluscher** [comment]
Nice find. Which browser is this?

I presume that in `contentScripts` that `globalThis.window` is undefined but `globalThis` is an `EventTarget`. It looks like in browser-ish environments, `globalThis` is always an `EventTarget`, so it should be safe to change this to `globalThis.addEventListener` everywhere.

**Comment by liepauls** [comment]
Hi @steveluscher, thanks for addressing the issue 🙇

Occured in Brave, tried your fix and it looks like the problem is gone.
