### ISSUE TITLE
Incomplete Error Handling in sendTransaction

### ISSUE THREAD

**Issue by paur94** [solana-labs/solana-web3.js#3668]
The sendTransaction function’s error handling is incomplete, missing essential fields like name, and error code. This omission prevents the isSolanaError check from working as intended, limiting error traceability and debugging.
![Image](https://github.com/user-attachments/assets/1b5c443e-5c86-42f8-9048-54ce262d2285)

**Comment by steveluscher** [comment]
https://github.com/solana-labs/solana-web3.js/issues/3561#issuecomment-2474675697

This is a usage question. You will get results faster if you post a question on Stack Exchange. Make sure to include source code, and a minimal repro, so that folks can help get you going again.
