### ISSUE TITLE
Invalid property for VoteAccountLayout

### ISSUE THREAD

**Issue by whb07** [solana-labs/solana-web3.js#481]
In line https://github.com/solana-labs/solana-web3.js/blob/master/src/vote-account.js#L82 there is an accessing call to the property `nodePubkey` which is not a defined property for the class Structure from the library buffer-layout.

Whats going on here or is this dead code/hasn't been used yet?

**Comment by mvines** [comment]
It comes from https://github.com/solana-labs/solana-web3.js/blob/6aa5db83480e532e1c074888430847090884f0f0/src/vote-account.js#L40

Example usage here: https://github.com/solana-labs/tour-de-sol/blob/bab7ac6fa30bb8eaea632ec2eaeb95809d5c6285/dash/main.js#L26

**Comment by whb07** [comment]
Right.... you’re chaining a call to an integer or something that looks like it. So effectively you’re calling that method in a js `number`

**Comment by whb07** [comment]
As a heads up, this is the typescript’s inference complaining at me. I’ll write up a test later

**Comment by mvines** [comment]
I’m pretty sure it works but maybe there’s a minor refactoring that we can do to get the tooling happy about it.   Happy to land anything along those lines to make your life easier, just lmk what you need

**Comment by sunnygleason** [comment]
In case it helps, I'm building out some TS examples here:

https://github.com/solana-labs/solana-web3.js/pull/484

Let me know if there's any examples that would help specifically
for your use case! (feel free to attach code/pseudocode)

**Comment by whb07** [comment]
I've effectively close to rewritten most of the codebase in typescript. as it turns out the community and mindshare behind types isn't with flow but with ts and as such many of the external deps are typed for ts.

**Comment by mvines** [comment]
Nice!  We aren’t zealous about flow or any other js-based tech.  Happy for them both to coexist and/or even switch over entirely to ts
