### ISSUE TITLE
Synchronize VoteAccount deserialization with solana/6072

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana-web3.js#490]
https://github.com/solana-labs/solana/pull/6072

**Comment by t-nelson** [comment]
I think https://github.com/t-nelson/solana-web3.js/commit/9820cae350f63e04f1353b325e89cb93d84866e3 is most of the way there.  Got frustrated with yarn and decided to move on 🙃

**Comment by CriesofCarrots** [comment]
I can take this over, @t-nelson

**Comment by mvines** [comment]
We might want to bring part of that change into 0.19?  To keep 0.19 and 0.20 vote account deserialization the same

**Comment by CriesofCarrots** [comment]
> We might want to bring part of that change into 0.19? To keep 0.19 and 0.20 vote account deserialization the same

Yes, I like that plan @mvines,  I was thinking about that when I saw your SOL/lamports auto-pr conflict on v0.19. I think both of Rob's Authority prs can be cherry-picked pretty easily, and it might be nice to have the stake account consistency as well. I'll PR.
