### ISSUE TITLE
Add commitment level params to connection apis

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-web3.js#546]
A new commitment param was added to most JSON-RPC api methods here: https://github.com/solana-labs/solana/pull/6759/files#diff-4834fdf4219df45e9abb8f640a372897

**Comment by jstarry** [comment]
(the lack of these params is what's causing test:live failures on CI)

**Comment by CriesofCarrots** [comment]
To be more specific, if not present, the default commitment config uses a rooted bank. So transactions take longer to confirm (likely longer than test:live polls). We can either add a “recent” commitment config to test requests, or extend the timeout on confirmation polling.

**Comment by jstarry** [comment]
Thanks @CriesofCarrots! I was thinking of going with the former to keep the tests from taking too long

**Comment by CriesofCarrots** [comment]
Lol, the shortest path to victory from a coding perspective is probably to bump the timeouts.
But the best complete solution is likely to make that param configurable for all relevant Connection methods. At which point  it would probably be nice to have one test that waits for rooted confirmation. What do you think, @jstarry ?

**Comment by jstarry** [comment]
Yeah good call, I'll add the param and add a rooted confirmation test 👍
