### ISSUE TITLE
Not possible to create transactions for external signers

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-web3.js#570]
#### Problem

We have a method for getting the data that needs to be signed called `_getSignData` but it is currently private. This means that a developer using the web3.js api is unable to send transaction data to a third party wallet for signing using something like https://walletconnect.org/

#### Solution

Expose `_getSignData` publicly

**Comment by jstarry** [comment]
@mvines is there any particular reason why `_getSignData` isn't a public API?

**Comment by mvines** [comment]
We just didn't have an external requirement at the time so it was made private to keep the API surface tight.   Making it public with docs and tests if needed seems fine to me
