### ISSUE TITLE
Migrate from esdoc to jsdoc

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-web3.js#706]
#### Problem
* esdoc hasn't been maintained in over 2 years
* esdoc isn't smart enough to generate types from flow type definitions in a lot of cases

#### Proposed Solution
* Migrate from esdoc to jsdoc
* Profit

**Comment by mvines** [comment]
oh sad, really?

**Comment by jstarry** [comment]
https://esdoc.org/manual/CHANGELOG.html :(

**Comment by jstarry** [comment]
Switched to TypeDoc
