### ISSUE TITLE
Remove check for 'AccountInUse' error in `sendAndConfirmTransaction`

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-web3.js#793]
#### Problem
Doesn't seem possible that `AccountInUse` errors are sent back to clients because we only save `InstructionError`s in the status cache and status history store

**Comment by garious** [comment]
Correct, see https://github.com/solana-labs/solana/pull/9950

A long time ago, the TPU used to reject transactions with `AccountInUse` instead of dropping the transaction back into the Gulf Stream for the next slot.
