### ISSUE TITLE
Lacking clear documentation on transaction creation params

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-web3.js#874]
Each `..Params` object should have a description for each param to help developers understand their usage.

ie [`CreateNonceAccountParams`](https://solana-labs.github.io/solana-web3.js/typedef/index.html#static-typedef-CreateNonceAccountParams) should explain what `noncePubkey` is for

**Comment by roccomuso** [comment]
This would be useful thanks.

**Comment by jstarry** [comment]
@roccomuso anything in particular that you found confusing?

**Comment by roccomuso** [comment]
Yeah like, there a bunch of methods listed but without examples you won't know the exact flow or how to concatenate them to achieve what you want.

It could be intuitive in some cases but for others it gets tricky. Like right now I'm trying to create a simple delegation transaction but I don't know what is the right "flow" to follow. (https://github.com/solana-labs/solana-web3.js/issues/993)

**Comment by jstarry** [comment]
@roccomuso got it, yeah examples would go be really helpful for instruction combinations like that. Thanks for bringing this issue up again!
