### ISSUE TITLE
requestAirdrop uses RPC instead of drone

### ISSUE THREAD

**Issue by garious** [solana-labs/solana-web3.js#900]
#### Problem

See https://github.com/solana-labs/solana/pull/10124

#### Proposed Solution

Go straight to the drone port for an airdrop transaction.

**Comment by mvines** [comment]
Drone needs to implement a http port for this to be viable.  Can't access raw TCP from the web

**Comment by mvines** [comment]
that is, we're still stuck on https://github.com/solana-labs/solana/pull/3403#issuecomment-475102947

**Comment by steveluscher** [comment]
Closing this since solana-labs/solana#3403 was punted on.
