### ISSUE TITLE
Subscriptions do not support commitment parameter

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana-web3.js#904]
Account, program, and signature subscriptions are made without a commitment parameter, which means all these subscriptions default to `'recent'` commitment with no way to customize.

**Comment by jstarry** [comment]
Thanks @CriesofCarrots did you start on this? If not, I can add

**Comment by CriesofCarrots** [comment]
@jstarry , not really. I just hacked something ugly together for account notifications to test out break. Feel free, or I'll do it tomorrow if you don't get to it
