### ISSUE TITLE
Difference between getParsedAccountInfo and getAccountInfoAndContext

### ISSUE THREAD

**Issue by 524119574** [solana-labs/solana-web3.js#981]
It seems like the two are returning the same results? The code that I tried is:
```
let connection = new Connection('https://api.mainnet-beta.solana.com');
// Serum market address
let address = new PublicKey('6ibUz1BqSD3f8XP4wEGwoRH4YbYRZ1KDZBeXmrp3KosD');
console.log((await connection.getParsedAccountInfo(address)).value)
console.log((await connection.getAccountInfoAndContext(address)).value)
```
The results are:
```
{
  executable: false,
  owner: PublicKey {
    _bn: <BN: 2b550e1769df3ef485b1ee49fb82df9a2595911e935489ba4dceca6a91f574c2>
  },
  lamports: 3535680,
  data: <Buffer 73 65 72 75 6d 03 00 00 00 00 00 00 00 54 f2 3c bc 4d 93 79 5c e7 5e cd 81 73 bc f4 36 92 31 12 f7 b6 b0 24 f3 af d9 b6 78 91 24 b9 68 00 00 00 00 00 ... 330 more bytes>
}

{
  executable: false,
  owner: PublicKey {
    _bn: <BN: 2b550e1769df3ef485b1ee49fb82df9a2595911e935489ba4dceca6a91f574c2>
  },
  lamports: 3535680,
  data: <Buffer 73 65 72 75 6d 03 00 00 00 00 00 00 00 54 f2 3c bc 4d 93 79 5c e7 5e cd 81 73 bc f4 36 92 31 12 f7 b6 b0 24 f3 af d9 b6 78 91 24 b9 68 00 00 00 00 00 ... 330 more bytes>
}
```
Is there any chance that the encoding for `parsedJson` is not implemented? Or am I missing anything? Thanks!

**Comment by jstarry** [comment]
@524119574 yeah unfortunately we don't have a way to generically parse account data. We only manually parse accounts like stake, vote, SPL Token, etc.

**Comment by 524119574** [comment]
So you're saying it is not parsed since the public key that I provided is parsable (since it's a custom program)? 

If so, can you provide me with an account that is parsable in the main net so that I can see the difference maybe? Thanks!

**Comment by jstarry** [comment]
Yup, that's exactly what I'm saying. Here's an example of a token account that is parsed: https://explorer.solana.com/address/GEwV7M8wpe8NpgroamHPT6w6BjJiL4QmZBmwspDLWpzE (Check out devtools to see the response data)

**Comment by 524119574** [comment]
Aha, I see. Many thanks!

**Comment by jstarry** [comment]
No problem!
