### ISSUE TITLE
Data slice parameters for getAccountInfo

### ISSUE THREAD

**Issue by leofisG** [solana-labs/solana-web3.js#983]
According to the JSON RPC documentation [here](https://docs.solana.com/apps/jsonrpc-api#getaccountinfo), it has an optional parameter `dataSlice` however this doesn't seem to be present in the web3 client. So I am wondering is this not implemented?

If so, how do we send the request with the `dataSlice` parameter using `curl`? 

I am looking for something similar to:
```
// Request
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0", "id":1, "method":"getAccountInfo", "params":["vines1vzrYbzLMRdu58ou5XTby4qAqVRLmqo36NKPTg",{"encoding": "base58"}]}' http://localhost:8899
```

Thanks!

**Comment by CriesofCarrots** [comment]
Here's a working example on mainnet-beta using `dataSlice`:
```
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0", "id":1, "method":"getAccountInfo", "params":["Memo1UhkJRfHyvLMcVucJwxXeuD728EqVDDwQDxFMNo",{"encoding":"base64", "dataSlice":{"offset":0,"length":8}}]}' api.mainnet-beta.solana.com
```

I discovered there's a small bug using `base58` encoding; if the account data is larger than 128 bytes, the request won't return, even if the requested slice is smaller than 128 bytes. But should work for small accounts, or `base64` works for all accounts.

**Comment by steveluscher** [comment]
This was added in https://github.com/solana-labs/solana/pull/28389.
