### ISSUE TITLE
Questions: where is the Vote Program, Config Program and Load Program 

### ISSUE THREAD

**Issue by leofisG** [solana-labs/solana-web3.js#984]
As described in [here](https://docs.solana.com/apps/builtins), where is the Vote Program, Config Program and Load Program in the client?

I see that we have `stake-program`([here](https://github.com/solana-labs/solana-web3.js/blob/master/src/stake-program.js)) and `system-program`([here](https://github.com/solana-labs/solana-web3.js/blob/master/src/system-program.js)) but where are the rest. Thanks!

**Comment by jstarry** [comment]
@524119574 good question! They should be here but we just haven't added support for them yet. Feel free to open a PR if you have time, otherwise we will get to it eventually!
