### ISSUE TITLE
How to distinguish between mint address and normal address?

### ISSUE THREAD

**Issue by bachlongkocanh** [solana-labs/solana-web3.js#988]

**Comment by jstarry** [comment]
@bachlongkocanh there isn't a really easy to do it from the web3 sdk yet but it's possible.

First, you'll use `Connection.getParsedAccountInfo` to fetch a json parsed response from the RPC API. You can execute the same request with `curl` like this:

```bash
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0", "id":1, "method":"getAccountInfo", "params":["SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt", {"encoding":"jsonParsed"}]}' http://api.mainnet-beta.solana.com
```
```json
{
  "jsonrpc": "2.0",
  "result": {
    "context": {
      "slot": 33314598
    },
    "value": {
      "data": {
        "parsed": {
          "info": {
            "decimals": 6,
            "freezeAuthority": null,
            "isInitialized": true,
            "mintAuthority": null,
            "supply": "10000000000000000"
          },
          "type": "mint"
        },
        "program": "spl-token",
        "space": 82
      },
      "executable": false,
      "lamports": 77009584000,
      "owner": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
      "rentEpoch": 78
    }
  },
  "id": 1
}
```

So after calling `connection.getParsedAccountInfo` you will first check if `accountInfo.data` is an object or buffer. If it's an object, then you're dealing with a parsed json response. From here, you'll need to manually check if the "program" is "spl-token" and if "type" is "mint".

Here's how the explorer does it: https://github.com/solana-labs/solana/blob/master/explorer/src/providers/accounts/index.tsx#L125
