### ISSUE TITLE
Is the BPF sdk mandatory?

### ISSUE THREAD

**Issue by roccomuso** [solana-labs/solana-web3.js#989]
Sorry for the silly questions.

Is the BPF sdk needed to run the js lib? Is it needed for the "message fee"? what is it exactly?
Can you shed some lights?

Would it be needed just to generate a pubKey, get an address and create and sign a transaction? Because I saw most of these operations are carried out by plain js, no rust libs involved.

**Comment by jstarry** [comment]
@roccomuso Hey! The BPF sdk is only for creating on-chain programs. You're right that all of those operations are handled in JS
