### ISSUE TITLE
Provide usage examples

### ISSUE THREAD

**Issue by roccomuso** [solana-labs/solana-web3.js#991]
Are there any usage example around?

For example on how to use the Transaction class to build a valid tx.

thanks

**Comment by joncinque** [comment]
Hi @roccomuso , it's true that we don't have a ton of examples here, but you can look at the JS clients in the Solana Program Library:
* token: https://github.com/solana-labs/solana-program-library/blob/master/token/js/client/token.js
* token-swap: https://github.com/solana-labs/solana-program-library/blob/master/token-swap/js/client/token-swap.js

The Serum DEX also has some great examples of how to use the web3 API: https://github.com/project-serum/serum-js

You'll see loads of examples of building a Transaction in those files.

**Comment by joncinque** [comment]
Feel free to re-open if you have any other questions.
