### ISSUE TITLE
get transactions rpc api

### ISSUE THREAD

**Issue by roccomuso** [solana-labs/solana-web3.js#992]
what's the RPC to get the list of transactions given an address?

I saw `getConfirmedSignaturesForAddress2` but I don't want only the list of signature, instead I'd like to get some basic info like amount received/sent and addresses involved. Something more verbose.

I assumed having the signatures and call `getConfirmedTransaction` would give me the txs details, but what if I want the timestamp of the tx instead of the `slot`?
Nesting rpc calls seems a wrong approach to me.

**Comment by CriesofCarrots** [comment]
Right now chaining those calls (`getConfirmedSignaturesForAddress2` and `getConfirmedTransaction`) is the way to go. `getBlockTime` will return the timestamp from the `slot`
