### ISSUE TITLE
Documentation and example to start delegating

### ISSUE THREAD

**Issue by roccomuso** [solana-labs/solana-web3.js#993]
Is there an example around that shows how to create a transaction to start delegating SOL?
I saw these methods in the documentation:

AuthorizeStakeParams
CreateStakeAccountParams
DeactivateStakeParams
DelegateStakeParams
InitializeStakeParams
SplitStakeParams

Cannot really say what I should use, or if more than one is needed.

Moreover, do you choose how much SOL to stake or you'd stake your whole account fund? (like in ADA/XTZ etc.)

**Comment by dractw** [comment]
bump this thread
