### ISSUE TITLE
sendAndConfirmTransaction not consistent with network.

### ISSUE THREAD

**Issue by NorbertBodziony** [solana-labs/solana-web3.js#998]
Currently, timeout when calling `sendAndConfirmTransaction` is based on `commitment` the problem is that if we use timeout that does not match solana network we may end up in case where promise will throw timeout but transaction will be confirmed on network. I think we should be able to specify timeout or make it static that matches solana network.

**Comment by joncinque** [comment]
Copying our conversation from Discord:

@Norbert you're totally right.  i think the current error message tries to convey that by not saying that it failed: Transaction was not confirmed in ${duration.toFixed(2)} seconds.  we might want to add to it, saying something like "Transaction was not confirmed in X seconds.  It is unknown if it succeeded or failed, so be sure to check Y in the Solana explorer."  What do you think?
@jon It would be better but still if somebody just wants to make sure that transaction is ok will be forced to use max or wrapping in additional check
@Norbert good point. so keeping in mind that a transaction may never get confirmed, it might be best to allow people to tune the timeout and also make the message more descriptive.  that way you can increase the timeout without increasing the commitment level. what do you think?
@jon yes for me best solution is flexibe timeout there should be also predefined timeout that matches network something like until txn expire

I'll add something for it to be configured and also add to the error message

**Comment by jstarry** [comment]
@joncinque thanks for digging into this! The timeout mechanism is just not the right tool for the job in my opinion. I wrote up this issue awhile back that proposed a more deterministic fix (waiting for the transaction's recent blockhash to expire): https://github.com/solana-labs/solana/issues/12103

**Comment by jstarry** [comment]
Maybe we can bump the default timeouts as a quick fix for now but I don't think we need to allow devs to specify a timeout

**Comment by joncinque** [comment]
@jstarry that makes sense, thanks for weighing in and tagging the other issue.  I'll do what you recommend
